### ISSUE TITLE
patch for display program basename (misplaced in conversion shuffle)

### ISSUE THREAD

**Issue by Jskud** [hishamhm/htop#1]
[[copy of earlier email to another mailing list]]

Hi.

It looks like the ticket creation is limited on SourceForge for htop (I could not create a feature request ticket or patch ticket), so I'm sending this patch to this mailing list [htop-general].  I hope you find it useful.

It provides the "display_base_name" feature, which will display the program basename if enabled.

FYI.  /J
From c801f276ec55baccaa8ffb3abe5875ccbc3ed8ae Mon Sep 17 00:00:00 2001
From: Jskud <Jskud@Jskud.com>
Date: Sun, 12 Jan 2014 11:55:07 -0800
Subject: [PATCH 1/1] add display_base_name support

Signed-off-by: Jskud <Jskud@Jskud.com>
---
 DisplayOptionsPanel.c | 1 +
 Process.c             | 9 ++++++++-
 ProcessList.c         | 2 ++
 ProcessList.h         | 1 +
 Settings.c            | 3 +++
 5 files changed, 15 insertions(+), 1 deletion(-)

diff --git a/DisplayOptionsPanel.c b/DisplayOptionsPanel.c
index 6153313..0feb665 100644
--- a/DisplayOptionsPanel.c
+++ b/DisplayOptionsPanel.c
@@ -84,6 +84,7 @@ DisplayOptionsPanel* DisplayOptionsPanel_new(Settings* settings, ScreenManager*
    Panel_add(super, (Object*) CheckItem_new(strdup("Hide userland threads"), &(settings->pl->hideUserlandThreads), false));
    Panel_add(super, (Object*) CheckItem_new(strdup("Display threads in a different color"), &(settings->pl->highlightThreads), false));
    Panel_add(super, (Object*) CheckItem_new(strdup("Show custom thread names"), &(settings->pl->showThreadNames), false));
+   Panel_add(super, (Object*) CheckItem_new(strdup("Display program \"basename\""), &(settings->pl->displayBaseName), false));
    Panel_add(super, (Object*) CheckItem_new(strdup("Highlight program \"basename\""), &(settings->pl->highlightBaseName), false));
    Panel_add(super, (Object*) CheckItem_new(strdup("Highlight large numbers in memory counters"), &(settings->pl->highlightMegabytes), false));
    Panel_add(super, (Object*) CheckItem_new(strdup("Leave a margin around header"), &(settings->header->margin), false));
diff --git a/Process.c b/Process.c
index 6765be7..4a39557 100644
--- a/Process.c
+++ b/Process.c
@@ -369,8 +369,15 @@ static void Process_printTime(RichString* str, unsigned long long t) {
 }
 
 static inline void Process_writeCommand(Process* this, int attr, int baseattr, RichString* str) {
+   char *cmdstring = this->comm;
+   if (this->pl->displayBaseName) {
+      for (char *cp = this->comm; *cp; cp++) {
+	 if (*cp == ' ') break;
+	 if (*cp == '/') cmdstring = cp+1;
+      }
+   }
    int start = RichString_size(str);
-   RichString_append(str, attr, this->comm);
+   RichString_append(str, attr, cmdstring);
    if (this->pl->highlightBaseName) {
       int finish = RichString_size(str) - 1;
       int space = RichString_findChar(str, ' ', start);
diff --git a/ProcessList.c b/ProcessList.c
index a0aed39..7d71fcf 100644
--- a/ProcessList.c
+++ b/ProcessList.c
@@ -144,6 +144,7 @@ typedef struct ProcessList_ {
    bool hideKernelThreads;
    bool hideUserlandThreads;
    bool treeView;
+   bool displayBaseName;
    bool highlightBaseName;
    bool highlightMegabytes;
    bool highlightThreads;
@@ -251,6 +252,7 @@ ProcessList* ProcessList_new(UsersTable* usersTable, Hashtable* pidWhiteList) {
    this->hideKernelThreads = false;
    this->hideUserlandThreads = false;
    this->treeView = false;
+   this->displayBaseName = false;
    this->highlightBaseName = false;
    this->highlightMegabytes = false;
    this->detailedCPUTime = false;
diff --git a/ProcessList.h b/ProcessList.h
index cabd68d..5d934fa 100644
--- a/ProcessList.h
+++ b/ProcessList.h
@@ -124,6 +124,7 @@ typedef struct ProcessList_ {
    bool hideKernelThreads;
    bool hideUserlandThreads;
    bool treeView;
+   bool displayBaseName;
    bool highlightBaseName;
    bool highlightMegabytes;
    bool highlightThreads;
diff --git a/Settings.c b/Settings.c
index 0a85d58..977596f 100644
--- a/Settings.c
+++ b/Settings.c
@@ -111,6 +111,8 @@ static bool Settings_read(Settings* this, char* fileName, int cpuCount) {
          this->pl->shadowOtherUsers = atoi(option[1]);
       } else if (String_eq(option[0], "show_thread_names")) {
          this->pl->showThreadNames = atoi(option[1]);
+      } else if (String_eq(option[0], "display_base_name")) {
+         this->pl->displayBaseName = atoi(option[1]);
       } else if (String_eq(option[0], "highlight_base_name")) {
          this->pl->highlightBaseName = atoi(option[1]);
       } else if (String_eq(option[0], "highlight_megabytes")) {
@@ -182,6 +184,7 @@ bool Settings_write(Settings* this) {
    fprintf(fd, "hide_userland_threads=%d\n", (int) this->pl->hideUserlandThreads);
    fprintf(fd, "shadow_other_users=%d\n", (int) this->pl->shadowOtherUsers);
    fprintf(fd, "show_thread_names=%d\n", (int) this->pl->showThreadNames);
+   fprintf(fd, "display_base_name=%d\n", (int) this->pl->displayBaseName);
    fprintf(fd, "highlight_base_name=%d\n", (int) this->pl->highlightBaseName);
    fprintf(fd, "highlight_megabytes=%d\n", (int) this->pl->highlightMegabytes);
    fprintf(fd, "highlight_threads=%d\n", (int) this->pl->highlightThreads);
-- 
1.8.1.2

**Comment by hishamhm** [comment]
No plans to add this feature, since we already have highlight basename

**Comment by Jskud** [comment]
Yes, we have the highlight basename feature, but it still shows the whole command pathname, taking up a lot of screen space -- and too often, the basename is obscured when I display the columns I want in a small window that is always showing.  With display basename, I can a;ways see the command, and that is what is so useful.  Please reconsider accepting this patch.  Thanks.  /Jskud

**Comment by jb55** [comment]
+1

this is barely readable: https://cloudup.com/ccVSs-HSV34

@Jskud do you have a nicer formatted patch somewhere? I'd like to apply it to my local fork

**Comment by Jskud** [comment]
Yes, I'll send you a clean patch later tonight.  Thanks for asking.  /Jskud

**Comment by Jskud** [comment]
Attached is the patch I think I submitted -- I hope this helps.  FYI.  /J

**Comment by jb55** [comment]
@Jskud sorry, I was messaging you from github and didn't get the attachment. Do you mind emailing it to me at bill@casarin.me?

Thanks again!

**Comment by jb55** [comment]
If anyone else was interested the patch is here: https://gist.github.com/b08497cf9de0548fd0c4

I've also applied it to the osx branch here: jb55/htop-osx@9c3e63c8f93ce938946f234e55fc4d0bb0aad7f6

Cheers

**Comment by Jskud** [comment]
Thanks very much for doing that, and for continuing to make a great tool
even greater.  /Jskud
