### ISSUE TITLE
Cannot compile after making a file change

### ISSUE THREAD

**Issue by JavaCafe01** [hishamhm/htop#1005]
Hello,
Htop compiles just fine if I do not make any changes to a file. If I edit something, for example just add a comment, I get the following error:

```bash
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:874: htop] Error 1
make[1]: Leaving directory '/home/javacafe01/code/htop'
make: *** [Makefile:656: all] Error 2
```

[Here's](https://pastebin.com/XhJ6kaiW) the full make output.

**Comment by GaugeK** [comment]
Cannot reproduce, can you provide the exact changes you made and share the .diff?

**Comment by GaugeK** [comment]
Try this https://github.com/hishamhm/htop/pull/981

**Comment by JavaCafe01** [comment]
Able to compile with #1017
