### ISSUE TITLE
htop hangs if delay is lower than 2

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#105]
I'm using htop 1.0.3 and if the delay option is set to a value lower than 2 and htop is started the refreshing process will then hang.

**Comment by eric-tucker** [comment]
How come this fix hasn't been published anywhere?  I'm still seeing this and I'm running 1.0.3 on Fedora 21.

**Comment by hishamhm** [comment]
A new release is coming... stay tuned!
