### ISSUE TITLE
Wrong characters in GraphMeterMode_characters

### ISSUE THREAD

**Issue by aueelis** [hishamhm/htop#106]
Hi!

Using this wonderful tool, I noticed, that the color gradient in the CPU- and Memory-graphs doesn't always correspond to the actual "height" of the marker in the graph.

Looking at your screenshots, I noticed, that your are using a different terminal font, which could already be the main reason. For example, in your screenshot, entitled "The meters at the header are fully customizable", I can see, that the yellow tilde (~) is slightly above the characters to the left and right, which are therefor of green color. Unfortunately, my terminal font (Liberation Mono) shows the tilde nearly on same height as a normal dash (-). As a result, I set the string to

    static const char* GraphMeterMode_characters = "^'~-.,_`'~-.,_`'~-.,_";

So I'd like to ask you, if you could maybe create the option to configure this string with an optional file (e.g. ~/.htop)?

Best regards,
Stefan

**Comment by hishamhm** [comment]
This behavior will change in the next release of htop, stay tuned!
