### ISSUE TITLE
Priority adjustment of hidden threads

### ISSUE THREAD

**Issue by aueelis** [hishamhm/htop#107]
Hi, again!

I really like the possibility of htop to change the priority of processes via F7/F8 but there is an annoying issue:

While I can change the niceness/priority of a normal process and its threads, while they are visible, I would expect, that the priority of threads would be adjusted to their corresponding program's priority, while they are invisible (normally, I have both kernel and userland threads set to hidden).

I would propose an additional option, to simply change the priority of threads to their corresponding program.

Best regards,
Stefan

**Comment by hishamhm** [comment]
Thanks for the feedback! I archived the suggestion in the wishlist label for later access, as I keep open issues to bugs.
