### ISSUE TITLE
Grey characters are not visible in recovery mode

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#119]
I'm using htop 1.0.3 and if I'm booting into the recovery mode (with Ubuntu 14.10 dev) grey characters of htop will be shown as black characters on the console and thus making them invisible.

**Comment by hishamhm** [comment]
Looks like an issue in Ubuntu instead. All other text mode applications which use gray will have the same problem.

**Comment by Sworddragon** [comment]
I have retested this now with Ubuntu 15.04 dev and htop 1.0.3 and all is working fine so if there was any issue on Ubuntu with this it seems now to be fixed.
