### ISSUE TITLE
Read/write syscall rate

### ISSUE THREAD

**Issue by CAFxX** [hishamhm/htop#123]
The cumulative number of syscalls since process/thread creation can be useful, but sometimes it would be better to actually know the current rate.
It would be very helpful to have two new columns for the read/write syscall rate (similarly as RBYTES/WBYTES -> IO_READ_RATE/IO_WRITE_RATE)

**Comment by hishamhm** [comment]
Thanks for the feedback! I archived the suggestion in the wishlist label for later access, as I keep open issues to bugs only.
