### ISSUE TITLE
Wrong cpu usage report on first frame.

### ISSUE THREAD

**Issue by Yamakaky** [hishamhm/htop#126]
Hi

I have a little problem : on the first frame, the cpu usage report is wrong. It always shows this cpu usage :

![screenshot](https://lut.im/NUr3T1CQ/f0zEAMFf)

When the screen is refreshed, it shows the right data. Do you know why ?

Thanks

**Comment by Yamakaky** [comment]
Could you make a new release ? This fix isn't available without a git build, as 1.0.3 was released before the fix.

**Comment by hishamhm** [comment]
@Yamakaky there are major changes in the current tree, so the next release will probably be htop 2.0. I still have some work to do on it before the relese... but it is coming!!

**Comment by Yamakaky** [comment]
Cool !
