### ISSUE TITLE
enhancement request: display CPU frequency and C state

### ISSUE THREAD

**Issue by kcgthb** [hishamhm/htop#129]
Hi,

With the generalization of multicore CPUs with independent clock frequencies, C states and turbo boost, it would be great to display those information alongside the CPU id in the CPU meter.
Something like:
```
1 | C6 | 1.20GHz [                ] 
2 | C0 | 2.60GHz [|||||||||       ] 
```

**Comment by hishamhm** [comment]
Thanks for the feedback! I archived the suggestion in the wishlist label for later access, as I keep open issues to bugs.

**Comment by roosemberth** [comment]
Could you reconsider on implementing this feature?

Best Regards

**Comment by hnykda** [comment]
This would be indeed quite handy feature...

**Comment by mmsrubar** [comment]
:+1:

**Comment by archenroot** [comment]
This feature rocks!

**Comment by fonorobert** [comment]
There's a fork with CPU frequency and temperature meters as text: https://github.com/wbenny/htop

**Comment by jatin-code777** [comment]
Is there any update on this feature request? Would be really great to have

**Comment by AlexMuresan** [comment]
Would love to hear about any developments on this! Thank you!
