### ISSUE TITLE
Feature request : batch mode

### ISSUE THREAD

**Issue by pa-de-solminihac** [hishamhm/htop#135]
Hello,

Do you plan to have "batch mode" like there is in `top` ?

```man
       -b : Batch mode operation
            Starts top in 'Batch mode', which could be useful for sending
            output from top to other programs or  to  a  file.   In  this
            mode, top will not accept input and runs until the iterations
            limit you've set with the '-n' command-line option  or  until
            killed.
```

It would allow us to use `htop` superpowers in scripts, which would be great!

**Comment by hishamhm** [comment]
Thanks for the feedback! I archived the suggestion in the wishlist label for later access, as I keep open issues to bugs.

I have no current plans to add this feature now as I focus on improving htop as an interactive application (and there are other superpowerful commands available for scripting, such as ps (which has a million flags) )

**Comment by fiedl** [comment]
Sure, thanks for the info!
