### ISSUE TITLE
htop 1.03 crashing

### ISSUE THREAD

**Issue by bayoulinux** [hishamhm/htop#136]
When invoking htop with distro:

uname -a
Linux palmkey 3.16.3-200.WRMTest1.fc20.x86_64 #1 SMP Mon Oct 6 08:21:10 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Note this is straight from the Fedora site, no custom edits, just built from scratch is all...

I'm getting a crash as follows:

htop 1.0.3 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop[0x409807]
/lib64/libc.so.6[0x39d30358f0]
/lib64/libtinfo.so.5(_nc_str_copy+0x0)[0x39e9c179e0]
/lib64/libncursesw.so.5[0x39d4412fd5]
/lib64/libncursesw.so.5[0x39d4413fdb]
/lib64/libncursesw.so.5[0x39d44141ba]
/lib64/libncursesw.so.5[0x39d4426488]
/lib64/libncursesw.so.5(doupdate+0x77a)[0x39d442a1ea]
/lib64/libncursesw.so.5(wrefresh+0x39)[0x39d4416cd9]
/lib64/libncursesw.so.5(_nc_wgetch+0x14c)[0x39d440fdcc]
/lib64/libncursesw.so.5(wgetch+0x35)[0x39d4410b25]
htop(main+0x68d)[0x40623d]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x39d3021d65]
htop[0x407bdd]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!

Aborted (core dumped)

I need to admit that this is my first bug submission, so I'm not sure how the attach the htop.objdump log to the report.  File type attachments seem to be image files PNG, GIF, or JPG.

**Comment by hishamhm** [comment]
Closing since this is now outdated!
