### ISSUE TITLE
Type of the "Blank" meter can be changed

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#138]
I'm using htop 1.0.3 and in the options it is possible to change the type of the "Blank" meter which seems to make no sense.

**Comment by hishamhm** [comment]
It's harmless

**Comment by Sworddragon** [comment]
In my opinion even such harmless things should be fixed. Or is this behavior intended?

**Comment by hishamhm** [comment]
I respect your opinion, but it's my call. The behavior was seen, but ignored due to being harmless. I don't think it's worth adding code to handle "Blank" in a special way, it adds to overall complexity with no gain.
