### ISSUE TITLE
[improvement] Non [F3]-dependant filter-as-you-type

### ISSUE THREAD

**Issue by Arnaudv6** [hishamhm/htop#141]
Hello Hisham and contributors comunity,
this is more of a suggestion rather than an issue :
I love your project, and am about to switch to htop from the defunct QPS.
But then I will regret the simple, fresh-start filter-as-you-type feature.

My workflow knows two steps : find process(es) to be altered, pick the action to apply on them.
Latest is bound to special keys : [F9] to kill... (which could have a nice [suppr] alternative).

When selecting processes, htop already rocks at sorting and involved keys are handy,
But a non [F3]-dependant filter-as-you-type feature would be a huge improvement IMHO.
We could still exit with [ctrl] + [c]. (or [ctrl] + [q] like in rtorrent)

Thanks for this amazing project
Arnaudv6

**Comment by hishamhm** [comment]
Hi, I'm not adding this because the keyboard is already set by default with bindings to various functions, so we _need_ a key to enter the filter mode.
