### ISSUE TITLE
[Feature request] Ability to hide idle processes.

### ISSUE THREAD

**Issue by absorber** [hishamhm/htop#152]
Hi, I'm pretty new on Git(Hub) and as such I'm not sure how to report new issues (or feature requests for that matter). If you have a comment then please let me know how I could do things better next time :)

With the traditional `top` you have the `-i` flag (and also the same interactive key), which hides idle/zombie processes. I've noticed that it's missing in `htop`. It would be really cool to see this feature in `htop` as well.

**Comment by hishamhm** [comment]
Thanks for the feedback! Github doesn't have separate trackers for issues and feature requests, so each project just creates their own criteria, I think. I keep a label entry with wishlist, to make them accessible later, and I keep open issues to bugs only.

**Comment by sunoterra** [comment]
+1 for -i flag

**Comment by simonmichael** [comment]
I've been wanting this for a long time as well. It's one of the few things I miss from top. 

I tried to contribute a [bounty](https://www.bountysource.com/issues/7158458-feature-request-ability-to-hide-idle-processes/backers?show_profile_modal=1), but couldn't, maybe it needs this issue to be reopened.
