### ISSUE TITLE
make broken for old gcc?

### ISSUE THREAD

**Issue by flip111** [hishamhm/htop#155]
I'm using gcc 3.3.4 because it's in a very old repository for a very old device (embedded system from 2007, 266Mhz, 32MB RAM, linux 2.4, busybox). Configure works ok it seems, but when doing make i get `cc1: error: unrecognized option `-Wextra'`. Is this a bug not checking of the compiler supports `Wextra` or such compiler is not supported? How can i fix this problem myself?

**Comment by flip111** [comment]
I temporarily "fixed" this by removing -Wextra from `Makefile.in` and `Makefile.am`

**Comment by hishamhm** [comment]
Thank you, I added a configure test for that. I no longer regularly test htop on Linux 2.4, so let me know if there are any problems and I'll try to fix them.

**Comment by flip111** [comment]
thanks for support
