### ISSUE TITLE
missing required linux version?

### ISSUE THREAD

**Issue by flip111** [hishamhm/htop#156]
I'm using linux 2.4.22 which does not seem to have a header file with `sys_ioprio_get` see the difference between
http://lxr.free-electrons.com/ident?v=2.4.37;i=sys_ioprio_get
and
http://lxr.free-electrons.com/ident?v=3.2;i=sys_ioprio_get

So it looks like this function should come from `syscalls.h`. It strange that `syscall.h` (singular) is being included by not `syscalls.h` (plural).

The actualy error i'm getting while running `make`
```
gcc -DHAVE_CONFIG_H -I.  -DNDEBUG -I/opt/include -pedantic -Wall -std=c99 -rdynamic -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/opt/etc\" -g -O2 -MT htop-Process.o -MD -MP -MF .deps/htop-Process.Tpo -c -o htop-Process.o `test -f 'Process.c' || echo './'`Process.c
Process.c: In function `Process_updateIOPriority':
Process.c:713: error: `SYS_ioprio_get' undeclared (first use in this function)
Process.c:713: error: (Each undeclared identifier is reported only once
Process.c:713: error: for each function it appears in.)
Process.c: In function `Process_setIOPriority':
Process.c:719: error: `SYS_ioprio_set' undeclared (first use in this function)
make[1]: *** [htop-Process.o] Error 1
make[1]: Leaving directory `/volume1/@tmp/htop/htop-1.0.3'
make: *** [all] Error 2
```

**Comment by flip111** [comment]
https://www.cl.cam.ac.uk/cgi-bin/manpage?2+ioprio_set
`These system calls have been available on Linux since kernel 2.6.13.`

it seems htop 1.0.1 was the latest version without this function, i will try this older version of htop

**Comment by firstvirus92** [comment]
You are using ancient software. Linux 2.4.X isn't even being maintained upstream anymore, its end of life was almost 3 years ago.
I'd highly recommend you to upgrade your software since you are probably affected by some critical security issues. If you can't do that your best bet is to use an older version of htop.

**Comment by flip111** [comment]
htop 1.0.1 worked fine! thank you
