### ISSUE TITLE
Question - What Do Negative nice Numbers Represent?

### ISSUE THREAD

**Issue by moulei** [hishamhm/htop#158]
Hi,

When I look in htop I am seeing nice numbers listed as negative like this;

```
PID     User  Pri   NI  
1288  foo     0     -21
```

This is showing up for this process;
/usr/bin/X -nolisten tcp :0 -auth /home/foo/.serverauth.13393

I don't understand what the -21 means as a negative number?

I also see NI listed as -1 for /usr/sbin/ulogd -d why also the negative for ulogd?

thank you

**Comment by etam** [comment]
https://en.wikipedia.org/wiki/Nice_%28Unix%29

**Comment by moulei** [comment]
Hi,

So a -1 is also considered a high priority?

So then, these are both just processes given high priority...

So anything as a negative is a higher priority?

thanks

**Comment by etam** [comment]
> So a -1 is also considered a high priority?

Yes. Not _very high_ priority, but little bit higher than default.

**Comment by moulei** [comment]
ok thanks
