### ISSUE TITLE
IORW described in the man page as IO

### ISSUE THREAD

**Issue by jackyf** [hishamhm/htop#160]
Hello,

It seems like the IO_RATE column is displayed as IORW but documented in the man page as IO. Longer version: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774930

**Comment by hishamhm** [comment]
Hi! The manpage now matches the implementation in the master branch, and I have new names, inspired by iotop, for the labels (with matching docs in the manpage) in my "wip" branch.
