### ISSUE TITLE
htop 0.8.2.2 aborted on OS X 10.10.1

### ISSUE THREAD

**Issue by vinc30** [hishamhm/htop#161]
I'm using OS X10.10.1
When htop running, if I resize the terminal with my mouse, htop crashes. 
I got the following message which was left on the screen after a crash:

         htop 0.8.2.2 aborted. Please report bug at http://htop.sf.net

**Comment by beltex** [comment]
See the comment [here](https://github.com/hishamhm/htop/issues/30#issuecomment-38105219)

Assuming you installed htop via Homebrew, this is the current fork that is used - https://github.com/max-horvath/htop-osx

**Comment by hishamhm** [comment]
Thank you @beltex for providing @vinc30 with quick feedback!

**Comment by beltex** [comment]
np! :)
