### ISSUE TITLE
user wish: temperature and fan speed meters

### ISSUE THREAD

**Issue by jackyf** [hishamhm/htop#163]
A Debian user would like htop to have  temperature + fan speed meters in htop. Full message there: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776818 .

**Comment by hishamhm** [comment]
Thank you for forwarding it! I'm closing it for now (leaving the open issues list only for pending bugs) and marking it with the wishlist status labels (so I can revisit it later).

**Comment by ScriptFanix** [comment]
Hello
Apparently someone wrote a patch implementing temperature readings : https://gist.github.com/bcbnz/f34f61854b4961d1ad66
I haven't tested it though.

**Comment by semente** [comment]
That would be great!

**Comment by voltagex** [comment]
Ping on this - hasn't made it into htop 2, maybe 2.01?

**Comment by hishamhm** [comment]
The problem with that patch is that it spawns a new process on each screen update. A more native solution would be welcome!

**Comment by MartelliEnrico** [comment]
:+1: for OSX too

**Comment by MichaIng** [comment]
@hishamhm 
We faced this user wish as well and for my impression it indeed would really fit well into htop on Linux. We found so many 3rd party patched/implementations, but all of them have heavy dependencies and/or are not well implemented into htop (as above).

Many devices safe their temperature info readable inside `/sys`, but of course the file path/name varies...
Check our method as an idea, at least it covers _some_ devices 😉: https://github.com/Fourdee/DietPi/blob/testing/dietpi/func/dietpi-globals#L802-L809

**Comment by MichaIng** [comment]
@hishamhm 
Indeed, looking around a bid, I found `lm-sensors` to be a popular module showing (CPU) sensor temperatures. It needs to run a sensor detection command first, which seems to scan/check several different `/sys` and `/proc` folders, depending on existent kernel modules, in case enabling modules to access temps: https://github.com/groeck/lm-sensors/blob/master/prog/detect/sensors-detect

Looks quite messy for implementation. Just scanning some most common default locations and provide CPU temp meter just in case one with reasonable output was found, also is not too secure, as users report values of constant 40 °C or simply from other non-CPU sensor.

No problem, if supporting just a limited amount of devices/hardware, but for htop a deal breaker.
