### ISSUE TITLE
htop can execute lsof on Mac

### ISSUE THREAD

**Issue by oxoocoffee** [hishamhm/htop#168]
I am running 10.10.3 RC and got latest version of top from brew. It is installed in 
/usr/local/Cellar/htop-osx/0.8.2.4/bin/htop

When I start top and them press "l" I get message that lost can't be executed and that I need to check my path. When I quit top I can run lost just fine from same shell. which lsof shows /usr/sbin/lsof. it is in my path.

**Comment by beltex** [comment]
See the comment [here](https://github.com/hishamhm/htop/issues/30#issuecomment-38105219)

This is the current fork that is used by Homebrew - https://github.com/max-horvath/htop-osx
