### ISSUE TITLE
Copy text from output

### ISSUE THREAD

**Issue by skv-headless** [hishamhm/htop#169]
for ex.

![htop_feature](https://cloud.githubusercontent.com/assets/1488195/6244130/22544a14-b760-11e4-8817-72026984d749.png)

I want to select text using mouse /etc/redis/redis.conf and copy it.
May be it is possible and I don't know how.

**Comment by hishamhm** [comment]
Hold shift when selecting. This is true for any ncurses-based applications. Hope this helps!
