### ISSUE TITLE
i got a htop crash on the Ubuntu 12.04.5 LTS server

### ISSUE THREAD

**Issue by orionCMCMSU** [hishamhm/htop#170]
htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace:
htop[0x40959f]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f0d1fc60150]
htop(main+0x81d)[0x40596d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f0d1fc4b76d]
htop[0x407a15]
Aborted (core dumped)

**Comment by hishamhm** [comment]
The latest version is 1.0.3 and it includes fixes. Please update htop. :)
