### ISSUE TITLE
SIGSEGV: LinuxProcess_delete

### ISSUE THREAD

**Issue by nfnty** [hishamhm/htop#172]
GDB backtrace:

    Program terminated with signal SIGSEGV, Segmentation fault.
    #0  0x000003b14a9dce94 in free () from /usr/lib/libc.so.6
    #1  0x000000000041b5c2 in LinuxProcess_delete (cast=0x40c1150) at linux/LinuxProcess.c:40
    #2  0x000000000041da55 in LinuxProcessList_processEntries (this=0x4009fb0, dirname=0x4228ea "/proc", parent=0x0, period=13.25, tv=...) at linux/LinuxProcessList.c:572
    #3  0x000000000041e51a in ProcessList_scan (this=0x4009fb0) at linux/LinuxProcessList.c:715
    #4  0x000000000040d6e5 in main (argc=1, argv=0x3e93f2a7898) at htop.c:714

Valgrind snippet:

    ==24573== Invalid free() / delete / delete[] / realloc()
    ==24573==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==24573==    by 0x41B5C1: LinuxProcess_delete (LinuxProcess.c:40)
    ==24573==    by 0x4185E7: Vector_delete (Vector.c:54)
    ==24573==    by 0x413D85: ProcessList_done (ProcessList.c:217)
    ==24573==    by 0x41BAC2: ProcessList_delete (LinuxProcessList.c:81)
    ==24573==    by 0x40DFCD: main (htop.c:915)
    ==24573==  Address 0x40a917 is in the Text segment of /usr/bin/htop
    ==24573==    at 0x40A917: Hashtable_delete (Hashtable.c:99)

**Comment by hishamhm** [comment]
This crash is indicative that something else went wrong before the crash. Do you have the full Valgrind output, in case something interesting happened earlier? Thanks!

**Comment by nfnty** [comment]
Full log:

https://gist.github.com/1e23d9bab3e73bde31ce

**Comment by hishamhm** [comment]
Thank you! It was a silly bug in the end, sorry about that!
