### ISSUE TITLE
Items barely visible with Solarized Dark theme

### ISSUE THREAD

**Issue by desbma** [hishamhm/htop#173]
Using the popular [Solarized Dark](http://ethanschoonover.com/solarized) color theme (eg. with [gnome terminal](https://github.com/Anthony25/gnome-terminal-colors-solarized)), some numbers are barely visible (1 min load average, and totals in the cpu/mem bar graphs): 
![htop with Solarized color theme](http://i.imgur.com/Z912XJv.png)

Htop has the color setting to "Default".

I'm not sure if this is a htop or Solarized bug, si I'm opening an [issue](https://github.com/Anthony25/gnome-terminal-colors-solarized/issues/49) on both projects.

**Comment by desbma** [comment]
Never mind, this is a theme issue.

**Comment by beltex** [comment]
Related, might be of interest: #29 & #144

**Comment by desbma** [comment]
Thanks, I am using the htop monochromatic theme as a workaround.

Too bad #144 isn't being merged...

**Comment by hotpxl** [comment]
oh my. i didn't know there were numbers until i saw this issue
