### ISSUE TITLE
Pressing ESC in the signal menu needs too long to close it

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#175]
I'm using htop 1.0.3 and in the signal menu (by pressing F9 in the main menu) I'm noticing that pressing ESC does need a little time until the signal menu closes while choosing the entry 0 (Cancel) an pressing enter does immediately close the signal menu. Maybe pressing ESC could be enhanced to close the signal menu immediately too.

**Comment by hishamhm** [comment]
This is an ncurses issue. Set ESCDELAY in your environment.
http://compgroups.net/comp.unix.programmer/ncurses-timeout-for-esc/315473

**Comment by beltex** [comment]
aah so thats what it is!

This can actually be set programmatically through ncurses using `set_escdelay()`. Could check if the user has set the `ESCDELAY` env var and override if not to something much shorter than the default 1000 ms as the second link below suggests.

- [set_escdelay() manual page reference](http://invisible-island.net/ncurses/man/curs_threads.3x.html)
- [Reduce the delay after ESC in ncurses](http://en.chys.info/2009/09/esdelay-ncurses/)

**Comment by Sworddragon** [comment]
I'm wondering why in the second link the delay was set to 25ms and not directly to 0ms. But I like the idea: If the environment variable ESCDELAY is present do nothing otherwise set the delay to 0 ms.
