### ISSUE TITLE
htop crashing

### ISSUE THREAD

**Issue by bhdm** [hishamhm/htop#178]
uname -a
Linux mailbot.evrika.ru 3.2.41-042stab104.1 #1 SMP Fri Mar 13 20:06:37 MSK 2015 x86_64 GNU/Linux

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x32220)[0x7f6a103b6220]
htop(main+0x8ae)[0x40c932]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f6a103a2eed]
htop[0x4057e9]
Аварийный останов (core dumped)

**Comment by hishamhm** [comment]
htop 1.0.1 is an old version. Please upgrade!
