### ISSUE TITLE
Implement optional vi movement keys for scrolling, etc

### ISSUE THREAD

**Issue by liquiddandruff** [hishamhm/htop#18]
Laptops often have small arrow keys, and hitting page up/down often requires hitting the fn key as well. Having the ability to toggle this functionality will make htop easier for mobile users as well as people who are used to vi movement keys.

Forked and will check this out soon

**Comment by bbugyi200** [comment]
Here's a more up-to-date patch (it works with v2.2.0) that implements this if anyone is interested: https://gist.github.com/bbugyi200/c066a5b56819c629f41f8805804e5204
