### ISSUE TITLE
starttime resets if /proc remounted

### ISSUE THREAD

**Issue by shawnl** [hishamhm/htop#180]
https://github.com/shawnl/htop/commit/edc4ea90f20986eb78af7de39497a6de693209bb
https://github.com/shawnl/htop/commit/ffd304321735c20a8a9fb004f48a29d7ffd30a03

**Comment by hishamhm** [comment]
Can't this be calculated once when the process is added instead of every time the process is displayed?

**Comment by shawnl** [comment]
Yes it could. But the information should come from the stat file, cause thats the best source.

**Comment by shawnl** [comment]
I don't think it makes much of a differnce if this gets updated every time, considering that this file is already being read.

**Comment by joder** [comment]
I am bitten by this issue too. Will the patch by @shawnl ever be merged or would the issue better be resolved in another way?

**Comment by hishamhm** [comment]
My question about his patch was about triggering an extra syscall on each list refresh (getting `localtime_r`) in Process.c, but I haven't tested it yet; it's possible that the glibc caches this information. The current codebase builds the starttime string once and just reuses that. I like the idea of reading from the stat file, but I don't want a performance penalty. I will revisit this issue when I get back at the code, thank you for your feedback.

**Comment by shawnl** [comment]
localtime_r() is not a real syscall, it gets handled by the VDSO http://man7.org/linux/man-pages/man7/vdso.7.html

**Comment by sh3bang** [comment]
Bug not fixed? STARTIME is still wrong!

**Comment by shawnl** [comment]
Not if you remount /proc

**Comment by sh3bang** [comment]
i dount mount or remount /proc... its done during boot. But htop show wrong start time... instead of top

**Comment by shawnl** [comment]
This was never merged

**Comment by hishamhm** [comment]
@shawnl Thanks for applying the changes to the PR. I will give it a spin an merge it for the upcoming release!

**Comment by folfy** [comment]
Just stumbled upon this problem while using htop (very odd behavior indeed).
@hishamhm Anything we can help/contribute to the PR? Is there something left which is preventing this from being merged?

**Comment by hishamhm** [comment]
Merged using @shawnl's fix. Thank you!
