### ISSUE TITLE
htop suddenly stopped and could not restart until re-login

### ISSUE THREAD

**Issue by zhouzhaoze** [hishamhm/htop#186]
htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407d3f]
/lib64/libc.so.6[0x32588326a0]
htop(main+0x884)[0x409cd4]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x325881ed5d]
htop[0x404f89]
[2]    25801 abort (core dumped)  htop

**Comment by hishamhm** [comment]
htop 1.0.1 is an old version. Please upgrade!
