### ISSUE TITLE
Detailed CPU time Core DUMP 0x407cfc

### ISSUE THREAD

**Issue by vlastis** [hishamhm/htop#191]
htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace:
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x321e0)[0x7fa0a62411e0]
Aborted

**Comment by gajownik** [comment]
htop 1.0.1 is a really old release. Could you please test the latest one?1.0.3 has a fix for Detailed CPU time crash that might be the same as yours.

Thanks

**Comment by vlastis** [comment]
hello,
i is actuall version from debian wheezy, so I'll compile actual from source 
i source files and let you know.
Thank you for quick response.

-- 
B.R.

Vlastimil Plechacek





---------- Původní zpráva ----------
Od: gajownik <notifications@github.com>
Komu: hishamhm/htop <htop@noreply.github.com>
Datum: 4. 5. 2015 13:18:12
Předmět: Re: [htop] Detailed CPU time Core DUMP 0x407cfc (#191)

"

htop 1.0.1 is a really old release. Could you please test the latest one?
1.0.3 has a fix for Detailed CPU time crash that might be the same as yours.

Thanks

—
Reply to this email directly or view it on GitHub
(https://github.com/hishamhm/htop/issues/191#issuecomment-98679978). 





"=

**Comment by vlastis** [comment]
Hello,
after upgrade to 1.0.3 is everything fine. Sorry for disturbing.

-- 
B.R.
Vlastk Plechacek





---------- Původní zpráva ----------
Od: gajownik <notifications@github.com>
Komu: hishamhm/htop <htop@noreply.github.com>
Datum: 4. 5. 2015 13:18:12
Předmět: Re: [htop] Detailed CPU time Core DUMP 0x407cfc (#191)

"

htop 1.0.1 is a really old release. Could you please test the latest one?
1.0.3 has a fix for Detailed CPU time crash that might be the same as yours.

Thanks

—
Reply to this email directly or view it on GitHub
(https://github.com/hishamhm/htop/issues/191#issuecomment-98679978). 





"=

**Comment by gajownik** [comment]
Good to hear that the issue is resolved. If it's not a problem could you please close the ticket? Unfortunately I do not have permissions to do that.

Thanks

**Comment by vlastis** [comment]
solved by upgrade to 1.0.3
