### ISSUE TITLE
no iorate(0) and io-prio displayed as '??' if it 'idle'

### ISSUE THREAD

**Issue by Astara** [hishamhm/htop#199]
use suse's 13.2 build of htop V1.0.3
kernel=4.0.4 -- 'vanilla'
as root, ran htop -- got an iorate of 0 for all procs (even while smbd procs were doing 194MB/s)
any idea why?

tnx!

**Comment by wolfgang42** [comment]
IORate of 0 sounds like it might be the same issue as #88. ioprio showing idle as '??' is #100.

**Comment by hishamhm** [comment]
@Astara iorate as 0 has been fixed in htop 2.x (it now shows "no perm" when there are no permissions), '??' was just fixed in #100.
