### ISSUE TITLE
htop 1.0.1 aborting. Please report bug at http://htop.sf.net

### ISSUE THREAD

**Issue by pythonms** [hishamhm/htop#200]
Backtrace: 
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x321e0)[0x7f25563e21e0]
htop(main+0x8ae)[0x40c932]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f25563ceead]
htop[0x4057e9]

debian wheezy, 64bit,

**Comment by hishamhm** [comment]
htop 1.0.1 is outdated. Please upgrade!
