### ISSUE TITLE
Missing unicode font for graph view

### ISSUE THREAD

**Issue by LukasLedvina** [hishamhm/htop#212]
Hello, I forked the newest version and cpu-usage graph is not shown properly. Left: new version, right: htop 1.0.3 from debian 8. What font shuld I use in my console instead of "DejaVu Sans Mono"?

It's working only with configuration --disable-unicode.

![luuuuckygraph](https://cloud.githubusercontent.com/assets/1250507/8312308/1829aa00-19dc-11e5-8d4d-8d00858a01cd.png)

Thanks Lukas

**Comment by eworm-de** [comment]
I do use Terminus in my terminals. Version 4.40 has braille characters included.

**Comment by LukasLedvina** [comment]
Thx, it works perfectly.
