### ISSUE TITLE
Feature request: a CTIME column

### ISSUE THREAD

**Issue by bgeron** [hishamhm/htop#224]
There is TIME = UTIME + STIME, and CUTIME and CSTIME, but no CTIME = CUTIME + CSTIME.

It would also be great to have a "cumulative time" column: TIME + CTIME (similar to top's `S` switch).

**Comment by dnnr** [comment]
Does that mean this won't happen?

**Comment by hishamhm** [comment]
no, it just means it's archived along with the other feature requests in that label (I like to keep the list of "open" issues to pending bugs). 

Pull requests are welcome!
