### ISSUE TITLE
"shadow other users' processes" overrides other color options (e.g. highlight basename)

### ISSUE THREAD

**Issue by azrdev** [hishamhm/htop#225]
Enable the option "highlight program basename", see how all basenames are highlighted.
Now also enable the option "shadow other users' processes". See how these processes are hightlighted (in grey in the default color scheme), but not their basename anymore.

**Comment by hishamhm** [comment]
yes, this is by design, they are all shadowed. There are limitations on what we can do with character-mode color/attribute manipulation in the terminal (can't display dark gray on bold), and the idea of shadowing other user's processes was to take the focus away from them anyway.
