### ISSUE TITLE
pid column doesn't grow past 5 chars

### ISSUE THREAD

**Issue by dannyperson** [hishamhm/htop#228]
with pids over 99,999 the formatting goes wonky and the columns don't line up, making things hard to read.
<img width="943" alt="screen shot 2015-07-20 at 5 36 44 pm" src="https://cloud.githubusercontent.com/assets/1476684/8790747/486c627c-2f06-11e5-949b-30f4b592843c.png">

**Comment by hishamhm** [comment]
what version of htop are you running?

**Comment by hishamhm** [comment]
And what's the output of `cat /proc/sys/kernel/pid_max` in your system?
