### ISSUE TITLE
Missing whitespaces on the memory and swap meters

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#229]
I'm using htop 1.0.3 and I'm noticing that at least the memory and swap meters aren't having a whitespace after the colons. But other meters like the task counter and uptime are having a whitespace after their colon so maybe this could be made more consistent.

**Comment by hishamhm** [comment]
CPU meters don't have space either. The ones in the left column in the default view don't have spaces after the colon because they tend to me more starved for space. This is the kind of design problem that has no perfect solution so I just had to make a choice, sorry.
