### ISSUE TITLE
Allow wrapping of long command names

### ISSUE THREAD

**Issue by alexjurkiewicz** [hishamhm/htop#233]
Sometimes I'm using htop to watch a deeply nested process tree, or otherwise very long command names (java procs in particular). It would be nice if htop could show more of the commandline in these cases.

Some more considerations:
* allowing every process to wrap would show too much mostly-useless info
* only allowing the selected process to wrap would result in lines below the selection jumping around and you scrolled up/down through the process list
* allowing processes to show up to 32k chars is probably excessive, so capping at 2 lines is probably sensible

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by hishamhm** [comment]
The design choice I went with for this situation was to allow horizontal scrolling.

Wrapping a process into multiple lines would be to convoluted to implement in the current design of htop, and I'm not sure if it's a good idea. 

In any case, thanks for the feedback!

**Comment by alexjurkiewicz** [comment]
Quick response! Thanks so much
