### ISSUE TITLE
Feature Request:  Linux hugepage accounting

### ISSUE THREAD

**Issue by danpritts** [hishamhm/htop#236]
Hi -

On large Linux systems, it can be useful to configure applications to use "hugepages."  It would be great if htop could display hugepage usage by a process.  

You can see a relevant question & answer here, including the way to get the information out of /proc.  
http://serverfault.com/questions/527085/linux-non-transparent-per-process-hugepage-accounting

Note this is different from "transparent hugepages".  That is a kernel feature to move memory around in the background, to gain the benefits of hugepages without the extra configuration.  Unfortunately it's not perfect, so the old way is useful still.

thanks!

**Comment by c3ph3us** [comment]
1,5 year later :D those wishes never come true

**Comment by hishamhm** [comment]
Patches are welcome! ;)
