### ISSUE TITLE
Crash on killing a process

### ISSUE THREAD

**Issue by asgh** [hishamhm/htop#238]
I killed a process with SIGTERM, it didn't die, so I killed with KIGKILL, then it crashed. I might have pressed something after killing and before the crash, not sure. It asked me to report, so I am. Not sure if there is enough info in the report since the backtrace doesn't have symbols.

If not enough info just close.

    htop 1.0.1 aborting. Please report bug at http://htop.sf.net
    Backtrace: 
    htop[0x804e7d7]
    [0xf7713cf0]
    htop(Process_toggleTag+0x6)[0x8059a5e]
    htop(main+0x1405)[0x8053d42]
    /lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xf7517e46]
    htop[0x804c5c1]
    Aborted (core dumped)

**Comment by hishamhm** [comment]
htop 1.0.1 is outdated - please upgrade!
