### ISSUE TITLE
Crash using repag button.

### ISSUE THREAD

**Issue by alex2ndg** [hishamhm/htop#239]
Using htop 1.0.1 under a x86_64 RHEL (kernel 2.6.32). TTy is Cygwin.

How to reproduce: Enter htop, press F4 (Filter), write anything, then press avpag/repag buttons.

Sometimes it enters S/R, sometimes it crashes. Example:

```
Backtrace:
htop[0x407d3f]
/lib64/libc.so.6(+0x32920)[0x7fc8d890c920]
htop(main+0x884)[0x409cd4]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x7fc8d88f8cdd]
htop[0x404f89]
Abort(coredump)
```

**Comment by hishamhm** [comment]
This was fixed in the latest version, please upgrade!
