### ISSUE TITLE
Implement option to collapse all entries in tree view

### ISSUE THREAD

**Issue by dlaflamme** [hishamhm/htop#24]

**Comment by jangorecki** [comment]
Could someone provide htop version number at which it has been implemented? or a commit hash if easier.

**Comment by hishamhm** [comment]
@jangorecki htop supports + and - for collapsing entries in tree view, but not one for collapsing all. As for why this entry is closed, I'm quoting the comment linked above:

```
Hi, thank you for the input!

Please do not post wishlist items as issues. From now on I will close wishlist items and mark them as such. They will remain archived for reference (and I do look and evaluate them all!). I had to do this because at one point the majority of items in the issues page was feature requests and not actual issues, and that was making the bugs harder to manage.

Please prefer posting wishlist items (feature requests) as messages to the htop mailing list instead. Thank you!
```

**Comment by jangorecki** [comment]
@hishamhm Thanks for clarification. It's a pity the github labels are not able to solve that problem for you. Having feature request opened the project could potentially benefit from third party contribution more easily.

**Comment by dannycolin** [comment]
that's a shame that this feature isn't implemented. At least, it would be more logical if the tree is collapsed by default.

**Comment by Lattyware** [comment]
This seems like a more and more important feature - it is now very common for applications to start a huge number of processes (browsers often manage hundreds alone), so the default view is more and more likely to be useless. Having everything collapsed by default would definitely be more useful for me.

**Comment by SleeplessSloth** [comment]
Why was this implemented and then reverted back? This'd be such a useful feature

**Comment by bedge** [comment]
I'd add that it should be a configurable option for startup.
With 100's of processes on servers, the default expended view that shows the top 2% of them is a bit pointless. 
I find myself starting off collapsing every top level tree, then searching for what I need.

**Comment by dwdixon** [comment]
I will second @bedge's comment here...it should at minimum be configurable to have all processes/threads/child processes start collapsed by default in tree view...but IMO I will also second @dannycolin's comment above that it really seems to be a much more sane default to have the tree collapsed by default and configurable to start the tree expanded.

**Comment by bumbummen99** [comment]
So manually collapsing all groups until 2030.
