### ISSUE TITLE
Display RAM in GB

### ISSUE THREAD

**Issue by deshtop** [hishamhm/htop#243]
Hi, one for the wishlist: It would be nice to have an option to display RAM usage (in the "Mem", "Swp" bar) either in MB or GB.

**Comment by eworm-de** [comment]
My PR #208 is a candidate to solve this... ;)

**Comment by hishamhm** [comment]
PR #208 does solve this in a nicer way. 
Come to think of it, I'm thinking that maybe the MemoryMeter in text mode should keep displaying more detailed memory numbers.

**Comment by eworm-de** [comment]
That was the second patch from PR #208. :D
IMHO htop is a tool that should be perfectly readable for human beings. If anybody (or a script) is interested in exact numbers getting them from `/proc` or `free` is the way to got.
I do not care about text mode, though. So feel free to change that.

**Comment by hishamhm** [comment]
> IMHO htop is a tool that should be perfectly readable for human beings. 

I agree! That's a major design goal. But sometimes human beings want to watch more detailed memory increases :) (plus, `top` displays values in textmode down to kilobytes)

> I do not care about text mode, though. So feel free to change that.

I don't use it either :)
