### ISSUE TITLE
Color glitches on long commandline w/ ncurses ABI6

### ISSUE THREAD

**Issue by NiLuJe** [hishamhm/htop#244]
As recommended, this is a repost of my [comment](https://github.com/hishamhm/htop/issues/241#issuecomment-133090572) comment in #241 ;).

----

I'm seeing a weird graphical issue where sometimes, the coloring of a commandline will go a bit haywire. The weird colors shift around when resizing the window, and eventually settle down to something normal. So far, I've only seen this on very long commandlines.

x86
![htop_ncurses6_color_1](https://cloud.githubusercontent.com/assets/111974/9390729/3e175842-4773-11e5-840a-be27fe305d47.png)

armv7
![htop_ncurses6_color_2](https://cloud.githubusercontent.com/assets/111974/9390730/3e18d1cc-4773-11e5-87b6-62ea24a894c3.png)
... after a resize
![htop_ncurses6_color_3](https://cloud.githubusercontent.com/assets/111974/9390731/3e199878-4773-11e5-9643-e9833a99af2e.png)
... and okay after a second resize.
![htop_ncurses6_color_4](https://cloud.githubusercontent.com/assets/111974/9390732/3e5e8cf8-4773-11e5-8a55-488e1e83535f.png)

**Comment by hishamhm** [comment]
@NiLuJe please verify that the bug is fixed! I can no longer reproduce it here.

**Comment by NiLuJe** [comment]
Will do!

So far, looks okay on x86 & x86_64, I'll get back to you tomorrow when the arm builds are done, since those machines (well, Kindles ;p), happen to have a process that reproduced this 100% ;).

**Comment by NiLuJe** [comment]
And it looks okay on my end on arm too, thanks!

**Comment by hishamhm** [comment]
Great to know, thanks!
