### ISSUE TITLE
Freebsd native usage

### ISSUE THREAD

**Issue by ghost** [hishamhm/htop#25]
How about a FreeBSD Native htop version? Without the need for linprocfs?
Because i discovered the problem that htop doesn't display wired memory usage in FreeBSD and therefore only shows a much lower, and therefore wrong, memory usage compared to top or vmstat (vmstat -m)

**Comment by saatanaperkele** [comment]
I might be willing to do some work on this in the future, but I won't make any promises, just a teaser.

**Comment by hishamhm** [comment]
@saatanaperkele I did some coding in a BSD VM when I was isolating the `linux/` and `unsupported/` parts of the code. I'll commit the stuff I had in a new `freebsd` branch. However, this branch is way behind the major reworkings I'm doing in the `wip` branch. Getting all branches in sync will take some work.

**Comment by saatanaperkele** [comment]
Appreciate all the work, I've been laid off so I'll have some free time to hack at it soon.

**Comment by hishamhm** [comment]
Ouch, sorry to hear that! I wish you luck!
