### ISSUE TITLE
htop failed when have a filter process and process finish

### ISSUE THREAD

**Issue by guilleJB** [hishamhm/htop#256]
When have a filter for some processes and all of them finish htop fails with this backtrace

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x321e0)[0x7f55018931e0]
htop(main+0x8ae)[0x40c932]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f550187fead]
htop[0x4057e9]
Aborted

**Comment by darthhexx** [comment]
I am having this same issue. You can easily reproduce it by simply filtering by a non-existent process, say "abcde", and then clicking anywhere in the terminal screen. I haven't looked, but I guess it's related to ncurses and the fact that there is no process to highlight for the click event.

**Comment by hishamhm** [comment]
Hi there! This was fixed in more recent releases. Please upgrade htop!

**Comment by darthhexx** [comment]
Excellent, thanks.
