### ISSUE TITLE
Segmentation fault when changing the Fan RPM's type to the bar graph in OS X

### ISSUE THREAD

**Issue by raincoats** [hishamhm/htop#257]
I noticed on your sourceforge page that the OS X version is old, and I don't know if this is the place to submit bug reports (or if the older version is still being maintained for OS X), but I thought I'd submit this anyway. 

[On this screen (screenshot)](http://i.imgur.com/zHYjGyr.png), I selected the meter "Fan RPM", and then used the mouse to click the "F4: Type" button at the bottom. Doing so three times (ie. going from the text type, to the graph type, to the big numbers type, and clicking once more) results in the attached segmentation fault.

    htop 0.8.2.7 aborted. Please report bug at http://htop.sf.net
    0   htop                                0x000000010c346a7f CRT_handleSIGSEGV + 30
    1   libsystem_platform.dylib            0x00007fff8edd7f1a _sigtramp + 26
    2   ???                                 0x00007f9979f05360 0x0 + 140297152516960
    3   htop                                0x000000010c3488bd Header_draw + 314
    4   htop                                0x000000010c34c735 MetersPanel_EventHandler + 298
    5   htop                                0x000000010c350832 ScreenManager_run + 524
    6   htop                                0x000000010c349d6e main + 5102
    7   libdyld.dylib                       0x00007fff8c44a5c9 start + 1
    8   ???                                 0x0000000000000003 0x0 + 3

Here's some OS/version info, etc.

    ~% sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.10.4
    BuildVersion:	14E46
    
    ~% htop --version
    htop 0.8.2.7 - (C) 2004-2008 Hisham Muhammad.
    Released under the GNU GPL.
    
    ~% where htop
    htop: aliased to sudo htop -d 10
    /usr/local/bin/htop
    
    ~% $SHELL --version
    zsh 5.0.8 (x86_64-apple-darwin14.3.0)
    
    ~% uname -a
    Darwin vicks-inhaler 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015;     root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin

**Comment by hishamhm** [comment]
This version you are running is not the one on this repository. Please give the one in this repo a try if possible. We are aiming to have native OSX support in the next official htop release, so testing is most welcome!

**Comment by raincoats** [comment]
Cheers! I'll clone it now and have a go.
