### ISSUE TITLE
Incomplete process list

### ISSUE THREAD

**Issue by drwilly** [hishamhm/htop#260]
I've recently noticed a problem with htop. The problem is that htop does not show all processes that are running on my system.
Interestingly the processes that are missing are the ones that are spawned early on during the boot process.
Currently, when sorting the processes by pid, the smallest pid, according to htop, is 164.
`ps -e` confirms that there are about 60 processes running between pid 1 and 164 that htop does not show. It's almost like htop just doesn't let me scroll to the top of the list.

My assumption is that this is related to me replacing sysvinit with [s6](http://skarnet.org/software/s6/).
One difference is that s6 does not have an init-executable that keeps running from system start to end, but starts off as a sequence of programs that `exec` into one another during boot. (described [here](http://skarnet.org/software/s6/s6-svscan-1.html))
Could it be that this `exec`ing of pid 1 causes the error I described?

**Comment by aueelis** [comment]
Did you enable kernel threads? The standard shortcut should be [Shift]-[K].

**Comment by drwilly** [comment]
Enabling kernel threads does indeed reveal the remaining processes.
I still find it weird that s6's pid 1 classifies as a kernel thread under htop and not as a regular process.
`pstree` for instance displays the tree correctly (without showing kernel threads).

**Comment by drwilly** [comment]
After further investigation, this issue looks a lot like openwrt/packages#426
