### ISSUE TITLE
nan% for values when htop initially starts on OS X

### ISSUE THREAD

**Issue by raincoats** [hishamhm/htop#265]
Hi, I made an issue the other day. As you kindly asked, I tested the new htop on OS X (10.10.4). Apart from some problems actually compiling it (not sure if it deserves an issue? it's likely something I did), it's been just fine.

There's only been one very tiny issue — when starting htop, the bars display `nan%` for a second until it updates. [Like this](http://i.imgur.com/j6DH4gY.png). But after a second, it all updates and it works perfectly, without a single issue.

```shell
~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.4
BuildVersion:	14E46

~ % uname -a
Darwin vicks-inhaler 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64 i386 MacBookAir6,2 Darwin

~ % htop --version
htop 1.0.3 - (C) 2004-2015 Hisham Muhammad
Released under the GNU GPL.
```

**Comment by edrozenberg** [comment]
Same issue here. Using latest htop compiled on Mac.

**Comment by raincoats** [comment]
I think that this is part of how it works, it doesn't know what the CPU usage is when it starts, it takes a sample, and then it takes another and prints the difference, or something. It's how top works, but top prints 0.0.
