### ISSUE TITLE
Crash while filtering

### ISSUE THREAD

**Issue by Fclem** [hishamhm/htop#270]
Have a lot of processes displayed with color, treeview details etc.
mouse click on Filter > input > 'pyhton' > Press enter >got this trace 

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x40959f]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f9417a09150]
htop(main+0x81d)[0x40596d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f94179f476d]
htop[0x407a15]
Aborted (core dumped)

**Comment by hishamhm** [comment]
This has already been fixed! Please update htop :)
