### ISSUE TITLE
Ability to change the position of the Command column

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#278]
I'm using htop 1.0.3 and noticing that the position of the Command column can't be changed. I think this is because of the potential too long command names but maybe this can be enhanced by setting dynamic columns (like USER and Command) to a fixed size only if they are not the last column while not setting them to a fixed size if they are the last column.

**Comment by AndydeCleyre** [comment]
I would love the Command column on the left side. In that case, the column's width could expand when panning left.
