### ISSUE TITLE
RFE: batch mode like top's -b option

### ISSUE THREAD

**Issue by pixelb** [hishamhm/htop#282]
It would be useful to generate output for another program.
See for example https://news.ycombinator.com/item?id=10323333

**Comment by pixelb** [comment]
Is this implemented or discounted? Would you accept a pull request to implement?

**Comment by hishamhm** [comment]
I'm leaving all feature requests closed, but marked with the "feature request" label.
This is not implemented, but I would be happy to accept a PR, if it doesn't increase the size of the tool too much.
