### ISSUE TITLE
platform specific signals, more specifically FreeBSD

### ISSUE THREAD

**Issue by etosan** [hishamhm/htop#284]
After some head scratching when sending signals, I realised htop, is sending wrong signals on FreeBSD. In my case the problematic signal was SIGUSR1, which htop has encoded as 10, but is actually 30 on FreeBSD, according to signal man page, and also as sent from kill utility from base os. 

I tried to put signal item array into FreeBSD platform directory and mucked around Makefile.am, but my *-fu with these things is low.

Here is at least compiled list which seems to work as intended, when I overwrite SignalsPanel.c directly

```C
static SignalItem signals[] = {
   { .name = " 0 Cancel",    .number =  0 },
   { .name = " 1 SIGHUP",    .number =  1 },
   { .name = " 2 SIGINT",    .number =  2 },
   { .name = " 3 SIGQUIT",   .number =  3 },
   { .name = " 4 SIGILL",    .number =  4 },
   { .name = " 5 SIGTRAP",   .number =  5 },
   { .name = " 6 SIGABRT",   .number =  6 },
   { .name = " 7 SIGEMT",    .number =  7 },
   { .name = " 8 SIGFPE",    .number =  8 },
   { .name = " 9 SIGKILL",   .number =  9 },
   { .name = "10 SIGBUS",    .number = 10 },
   { .name = "11 SIGSEGV",   .number = 11 },
   { .name = "12 SIGSYS",    .number = 12 },
   { .name = "13 SIGPIPE",   .number = 13 },
   { .name = "14 SIGALRM",   .number = 14 },
   { .name = "15 SIGTERM",   .number = 15 },
   { .name = "16 SIGURG",    .number = 16 },
   { .name = "17 SIGSTOP",   .number = 17 },
   { .name = "18 SIGTSTP",   .number = 18 },
   { .name = "19 SIGCONT",   .number = 19 },
   { .name = "20 SIGCHLD",   .number = 20 },
   { .name = "21 SIGTTIN",   .number = 21 },
   { .name = "22 SIGTTOU",   .number = 22 },
   { .name = "23 SIGIO",     .number = 23 },
   { .name = "24 SIGXCPU",   .number = 24 },
   { .name = "25 SIGXFSZ",   .number = 25 },
   { .name = "26 SIGVTALRM", .number = 26 },
   { .name = "27 SIGPROF",   .number = 27 },
   { .name = "28 SIGWINCH",  .number = 28 },
   { .name = "29 SIGINFO",   .number = 29 },
   { .name = "30 SIGUSR1",   .number = 30 },
   { .name = "31 SIGUSR2",   .number = 31 },
   { .name = "32 SIGTHR",    .number = 32 },
   { .name = "33 SIGLIBRT",  .number = 33 },
};
```

Is there a chance to have this implemented in mainline?

sources:
 - https://github.com/freebsd/freebsd/blob/master/sys/sys/signal.h
 - https://www.freebsd.org/cgi/man.cgi?query=signal&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html

**Comment by hishamhm** [comment]
Thank you! Factored out the table to platform-specific parts and added your table to the sources (see commit 3fe2f3e). Please test it!

**Comment by etosan** [comment]
Well I am bit lost in this github, thing so I am not sure if I missed something. 

But after I merged upstream into my master, I had to move table into "generator" comment to make it compile on FreeBSD, and so I created pull request.

But now when I do `git fetch upstream/master` and `git merge upstream/master` i am told everything is up to date, so I don't know...

Everything seems to compile now, and signal sending works.

**Comment by hishamhm** [comment]
Oh, I already copied your FreeBSD signal table into htop when I made that commit! You don't need to make a PR, just fetch a clean copy of `master` and test it, to verify that signal sending is ok. Thank you!

**Comment by etosan** [comment]
In that case signals are working.

**Comment by hishamhm** [comment]
Thanks for reporting!
