### ISSUE TITLE
Crash when trying to go to the end of an empty processlist

### ISSUE THREAD

**Issue by vtdmhd** [hishamhm/htop#290]
MWE:
1) launch htop
2) <F4>, enter some text until no processes are visible, <ENTER>
3) <END>
4) 
>htop 1.0.3 aborting. Please report bug at http://hisham.hm/htop    
 >                                                                  
 >Please include in your report the following backtrace:            
>htop[0x4096f7]                                                     
>/lib/x86_64-linux-gnu/libc.so.6(+0x35180)[0x7f843f685180]          
>htop(Panel_draw+0x1f2)[0x40e2f2]                                   
>htop(main+0x6a1)[0x406111]                                         
>/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f843f671b45]                                                               
>htop[0x407aeb]                                                     

I wish I could attach htop.objdump  as htop recommends, but Github doesn't let me do so.

**Comment by hishamhm** [comment]
This is fixed in the latest code in Git. Sorry about the bug and thank you for the report!
