### ISSUE TITLE
Description of DATA is wrong

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#297]
In this ticket ( https://bugzilla.kernel.org/show_bug.cgi?id=101341 ) it got figured out that the description of DATA in the manpage seems to be wrong. The last post from me in this tickets explains the reason:

>Thanks for the information. I think I figured out the problem: The manpage of htop descibes the DATA column as the data segment size + stack size while the manpage of top descibes it as anything except the code size. I'm reporting it then to htop and marking this ticket as invalid.

**Comment by hishamhm** [comment]
htop reads DATA (m_drs) straight from /proc/<pid>/statm. in the manpage for proc(5) (as of man-pages 3.55) it says:

```
       /proc/[pid]/statm
              Provides information about memory usage, measured in pages.  The columns are:

                  size       (1) total program size
                             (same as VmSize in /proc/[pid]/status)
                  resident   (2) resident set size
                             (same as VmRSS in /proc/[pid]/status)
                  share      (3) shared pages (i.e., backed by a file)
                  text       (4) text (code)
                  lib        (5) library (unused in Linux 2.6)
                  data       (6) data + stack
                  dt         (7) dirty pages (unused in Linux 2.6)
```

That's where the author of the man page seems to have got his information from.

To clarify, are you saying htop is displaying the wrong number or giving the wrong explanation? (If the latter, the proc manpage should be fixed as well, and I'd like to know what the correct fix is.)

Thank you for looking into this!

**Comment by Sworddragon** [comment]
>To clarify, are you saying htop is displaying the wrong number or giving the wrong explanation?

The description is wrong. If you make a look at the kernel ticket you will see that I have made based of the assumption that DATA is the data segment size + stack size a mistake because with limiting the data segment size to 8 MiB and the stack size to 8 MiB I have got DATA values around 2 GiB. But checking this in the ticket caused that limiting the data segment size works correctly so it can't be what is shown in DATA.

>If the latter, the proc manpage should be fixed as well, and I'd like to know what the correct fix is.

I'm posting this in the ticket but there is already an answer what DATA is:

>The top's DATA column includes both the heap and the additional memory region.

But maybe we should wait until the manpage of proc gets fixed.

**Comment by Sworddragon** [comment]
At the kernel ticket it is claimed that all is correct. That caused me to make a deeper look into it. On executing my original testcase (can be found here: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1462853 ) by having the data segment size and the stack size limited to 8 MiB with ulimit the DATA column of htop shows 2069 MiB. top shows the same value but just in KiB. The 6th column of /proc/_pid_/statm shows 529681 (and there is also no other column showing a significant higher value). This means that htop's DATA column is not showing the data + stack usage.

**Comment by hishamhm** [comment]
The manpage for the version of top I have installed (procps-ng 3.3.9) says the following:

```
     6. DATA  --  Data + Stack Size (KiB)
           The amount of physical memory devoted to other than executable
           code, also known as the 'data resident set' size or DRS.
```

and shows the same values as htop. Is this description more precise? Could we use that instead? Or has top's manpage changed recently? Thanks!

**Comment by Sworddragon** [comment]
The kernel ticket advanced again and now the problem is solved: htop describes the DATA column as data segment + stack and proc(5) as data + stack but at the kernel ticket it was me telled that data isn't the same as data segment.

This means that htop needs theoretically only to remove the word segment in the description of DATA to be accurate. But the top description reads like DATA is anything what not CODE is so maybe htop could rewrite the DATA description to be similar to CODE which is currently:

>The size of the text segment of the process (i.e the size of the processes executable instructions).


So I would suggest to describe DATA as:

>The data resident set size (data + stack) of the process (i.e the size of anything except the processes executable instructions).

And also to replace "size of the text segment" in the CODE description with "text resident set size".

**Comment by hishamhm** [comment]
Awesome! I'm traveling this week, so could you send a PR my way with those fixes to speed things up?

**Comment by Sworddragon** [comment]
Sure: #304
But since this topic was a bit difficult you maybe want to double check these changes.
