### ISSUE TITLE
Replace the uptime (!) easter egg with ;-) 

### ISSUE THREAD

**Issue by bverheg** [hishamhm/htop#3]
With an uptime above 100 days htop displays a `(!)` after the number of days.
This is misleading and people have been wasting time, thinking that it meant something was wrong with the machine. I suggest to replace the `(!)` in UptimeMeter.c with the friendlier and not misleading `;-)`. 

I patched my binary version:

```
  perl -pi -e 's/days\(\!\)/days;-)/' /usr/bin/htop
```

and am pleased with the result: 
`Uptime: 315 days;-), 02:03:35`

**Comment by pfarrell** [comment]
If you're looking for more upvotes, I too wasted time searching to find out if this indicated a warning or not.  I would vote for the ;-) as well.  it's the same number of characters and doesn't have the associate sense that something is wrong. A :+1: would communicate the intended comment, but, obviously, isn't available in text.
