### ISSUE TITLE
[Mac] Crashes in OSX 10.9 when in full screen

### ISSUE THREAD

**Issue by jamesmcfadden** [hishamhm/htop#30]
When I try to use htop while in terminal/ iterm full screen mode, the application crashes.

This happens both if I launch while in fullscreen and also if I transition to fullscreen after launching:

`htop 0.8.2.2 aborted. Please report bug at http://htop.sf.net`

**Comment by RSully** [comment]
@hishamhm don't want to bug you too much, but any idea when you'll have a chance to work on this some more?

**Comment by beltex** [comment]
One thing to note about this, the **top** implementation for OS X from Apple is open source. The statistics component is nicely structured into a single source file, [libtop.c](http://www.opensource.apple.com/source/top/top-100.1.2/libtop.c). So that should provide nearly all the stats needed by **htop** for an OS X backend.

In the meantime, @RSully, you might be interested in [this](https://github.com/beltex/dshb) :)

**Comment by hishamhm** [comment]
@RSully @beltex I hope to have good news about the abstraction layer later this week :)

**Comment by hishamhm** [comment]
@beltex unfortunately, libtop.c is released under the APSL 1.1, which is incompatible with the GPL, which htop uses.

**Comment by beltex** [comment]
@hishamhm Nice! :)

Darn, didn't realize that. It might still be handy as just a reference of where to get some stats from (Mach layer vs BSD layer vs `sysctl`, etc.). Though I know the whole derivative works thing is quite murky.

**Comment by kaefer** [comment]
@hishamhm Any (good) news about the abstraction layer? 
I'm currently trying to add a mac folder with mac specific stats (for now just dummy files with no stats information to get it up and running although it can't display any relevant data) and....I'm stuck with several segfaults from the "main" code which I can't resolve. 

btw: what is your suggestion: adding a mac branch, commiting directly to wip, shall I fork the repo and do my work there?

**Comment by hishamhm** [comment]
@kaefer yes! The wip branch is now merged to master. The "unsupported" directory there was supposed to be a starting point for new ports, but I think it is a bit behind the times right now; you might need to hack a bit to make it run again.

You can try to start by forcing the "unsupported" arch in configure.ac (rerun autogen.sh) and making it run. Once it's working it should produce an empty list of processes, and then you can start from there. For the (still unfinished) FreeBSD code I started with some meters and then the basic process list.

**Comment by kaefer** [comment]
@hishamhm +1!
I don't need to "force" the unsupperted part...on mac it will choose it anyway ;) 
I already created a mac folder + added detection in configure.ac. 

problems are in FunctionBar.c:111 although I don't know exactly why there. Maybe I'll create another ticket, when I can figure it out. on Linux (Ubuntu 14.10) it just works, but my mac doesn't want to :(
