### ISSUE TITLE
Feature Request: No Process List Argument

### ISSUE THREAD

**Issue by dannluciano** [hishamhm/htop#300]
What you think about stop with argument that hidden process list like this http://imgur.com/o3lbTda?
With this we can monitoring many server in same screen.

**Comment by dannluciano** [comment]
![screen shot 2015-11-01 at 23 45 37](https://cloud.githubusercontent.com/assets/44121/10894877/ba75e2ae-818f-11e5-8d8e-6f8c856288ff.png)

**Comment by unhammer** [comment]
doesn't `htop -p 0` do this?

**Comment by dannluciano** [comment]
Thanks @unhammer in OSX this parameter not exist.

**Comment by hishamhm** [comment]
@unhammer Clevel! :)
