### ISSUE TITLE
htop 1.0.3 aborting

### ISSUE THREAD

**Issue by fox0** [hishamhm/htop#306]
htop 1.0.3 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop[0x8050826]
linux-gate.so.1(__kernel_sigreturn+0x0)[0xb76e5d1c]
htop(Hashtable_get+0x27)[0x8052a77]
htop[0x8058c1f]
htop(ProcessList_scan+0x7fa)[0x805ad6a]
htop(main+0x8ec)[0x804ceac]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xf3)[0xb7495a63]
htop[0x804ea62]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!

Аварийный останов

**Comment by j0hannes** [comment]
Same problem, same message.

Here comes a dump:

[htop.objdump.txt](https://github.com/hishamhm/htop/files/38978/htop.objdump.txt)

**Comment by hishamhm** [comment]
Closing since this report is now outdated!
