### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by rarmstrong22** [hishamhm/htop#307]
Running remotely over an SSH terminal:

<i>htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407d3f]
/lib64/libc.so.6[0x36e42326a0]
htop(main+0x884)[0x409cd4]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x36e421ed5d]
htop[0x404f89]
Aborted (core dumped)</i>

cat /etc/issue on that machine:
<i>CentOS release 6.7 (Final)
Kernel \r on an \m </i>

**Comment by rarmstrong22** [comment]
Here's the output from  <code>objdump -d /usr/bin/htop > ~/htop.objdump.txt</code>:


[htop.objdump.txt](https://github.com/hishamhm/htop/files/32418/htop.objdump.txt)

**Comment by hishamhm** [comment]
Thank you for reporting, but htop 1.0.1 is outdated! Please upgrade.

**Comment by rarmstrong22** [comment]
Sorry 'bout that; I should have checked first. Thanks.
