### ISSUE TITLE
htop 1.0.1 aborting

### ISSUE THREAD

**Issue by fractalf** [hishamhm/htop#310]
htop crashed on me twice, so I guess I should report it.

I think it happens because I have an active filter. First thing I do after opening htop is press F4 (filter) and then punching in "his" to filter out my history_foobar.sh

````
[cron@elkcloner ~]$ htop


htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace:
htop[0x407d3f]
/lib64/libc.so.6[0x333b8326a0]
htop(main+0x884)[0x409cd4]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x333b81ed5d]
htop[0x404f89]
Aborted

[cron@elkcloner ~]$ uname -r
2.6.32-504.3.3.el6.x86_64

[cron@elkcloner ~]$ cat /etc/issue
Scientific Linux release 6.5 (Carbon)
Kernel \r on an \m
````

**Comment by hishamhm** [comment]
htop 1.0.1 is outdated, please upgrade to 1.0.3! 

Still, thanks for taking the effort to report a bug! :)
