### ISSUE TITLE
Suggestion - make Disk Read/Write/Activity columns much narrower

### ISSUE THREAD

**Issue by edrozenberg** [hishamhm/htop#311]
Currently, the Disk Write / Disk Read / Disk Activity columns ( IO___ items ) take up a lot of space and push the program name offscreen on 80 char terminals. IO items are useful to see but because they take up so much space cannot be practically left enabled on default terminal widths. Screenshot attached below.

![disk read write cols very wide](https://cloud.githubusercontent.com/assets/2648417/11343329/8b0c348c-91d9-11e5-886d-7fa9bbcbdc4c.png)

Suggestions -

Make column names much shorter, for example:

"DISK WRITE" --> "DW"
"DISK READ" --> "DR"
"DISK R/W" --> DRW

Make data values much shorter, for example with option for no decimals:

95.11 K/s --> 95 K/s or 95K/s with units having a different color, maybe grey
66.01 M/s --> 66 M/s or 66M/s with units having a different color, maybe grey

**Comment by pthfdr-42** [comment]
It used to be narrow in some old versions that IO speed is displayed in the same style as memory usage.

**Comment by gloschtla** [comment]
How to use this Disk Read column? I can't see it.
