### ISSUE TITLE
Feature request: Mac disk IO information

### ISSUE THREAD

**Issue by edrozenberg** [hishamhm/htop#312]
Currently, htop shows disk io (read/write/activity/bytes etc) on Linux but not currently on Mac platforms. It would be great to see IO information on the Mac platform as well.

For reference, here are disk information fields displayed in the Activity Monitor system utility.

![mac standard disk info](https://cloud.githubusercontent.com/assets/2648417/11343753/7149b996-91db-11e5-89df-d0a894ddbfd9.png)

**Comment by andrewchen-braze** [comment]
Why is this issue closed? did we implement it for Mac?

**Comment by kingspp** [comment]
Its only available in Linux. What about Mac?

**Comment by edrozenberg** [comment]
I/O info columns are not available on the Mac. I assume the developer doesn't plan to add this feature and closed the issue for that reason.

**Comment by kingspp** [comment]
At present, I am monitoring disk io using [psutil](https://psutil.readthedocs.io/en/latest/index.html#psutil.disk_io_counters).

Record read and write bytes with a second delay and the difference is the current usage/second
