### ISSUE TITLE
What is TTY_NR column realy?

### ISSUE THREAD

**Issue by denkondor** [hishamhm/htop#316]
'htop' displays some odd number for TTY column:

PID    TTY  USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
1141  1031  root         20    0   431M  219M 45480 S  2.4  2.8 6h56:30 /usr/bin/X :0 vt7 -br -nolisten tcp
1054  1025 root      20   0 92896  4532  3872 S  0.0  0.1 0:00.02 /bin/login --

and so on...
'top' and 'ps' show it correctly: pts/0, pts/1...

My system:
user@machine01:~$ uname -a
Linux machine01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

user@machine01:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie

user@machine01:~$ htop --version
htop 1.0.3 - (C) 2004-2012 Hisham Muhammad
Released under the GNU GPL.

**Comment by GiedriusS** [comment]
It parses the tty_nr field of /proc/[pid]/stat (atleast on linux). As the manual page says about it:

> The controlling terminal of the process.  (The minor device number is contained in the combination of bits 31 to 20 and 7 to 0; the major device number is in bits 15 to 8.)

I guess top and ps just go a extra mile and parse /dev/pts/* and check which pts really corresponds to the tty_nr field.

**Comment by hishamhm** [comment]
@GiedriusS Thank you for the inspiring comment! I gave it some digging here and produced a top-like output for Linux (and a fallback that at least prints major:minor device data on other platforms)
