### ISSUE TITLE
htop 1.0.2 aborting.

### ISSUE THREAD

**Issue by hitul007** [hishamhm/htop#317]
Please include in your report the following backtrace: 
htop[0x4098e7]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f24022c9d40]
htop(Panel_draw+0x2a7)[0x40df77]
htop(main+0x724)[0x405b84]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f24022b4ec5]
htop[0x407daf]

Dump can be found at https://drive.google.com/file/d/0BzPwHs8b0FolcjQxcU01aG12MlU/view?usp=sharing

**Comment by hishamhm** [comment]
htop 1.0.2 is outdated, please upgrade!
