### ISSUE TITLE
I can't scoll htop viewer with my mouse

### ISSUE THREAD

**Issue by backav** [hishamhm/htop#322]
I can't scoll the htop viewer with my mouse since i can't remember when.

The htop installed in a VPS with Centos6.5.
It happened when i use SSH connect to the VPS with the Teriminal application in OS X El Capitan.

**Comment by cjgibson** [comment]
Figured I'd give this a try myself -- on scrolling upwards with the mouse's scroll wheel, htop seems to stop updating entirely until interacted with again. Scrolling downwards seems to have no effect at all.

Running htop 1.0.2, with `ncurses5-config` and `ncursesw5-config` in my PATH. `uname` as follows:
`Linux WorkstationV 4.2.0-18-generic #22~14.04.1-Ubuntu SMP Fri Nov 6 22:20:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

Going to install 1.0.3 and see if the issue persists.

**Comment by edrozenberg** [comment]
Same issue on latest github build. Scrolling with mouse on Mac eventually causes app to quit, but no error is generated that I could see.

**Comment by hishamhm** [comment]
Try building with ncurses 6. Mouse support was greatly improved in this version.

**Comment by edrozenberg** [comment]
Confirmed, building with ncurses6 installed via homebrew, scrolling works fine on Mac OS X.

**Comment by hishamhm** [comment]
Thank you for the feedback!
