### ISSUE TITLE
htop 1.0.1 aborting

### ISSUE THREAD

**Issue by SpartakusMd** [hishamhm/htop#324]
htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x40959f]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7fecc32e6150]
htop(main+0x81d)[0x40596d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7fecc32d176d]
htop[0x407a15]
Aborted (core dumped)

**Comment by hishamhm** [comment]
htop 1.0.1 is outdated, please upgrade!
