### ISSUE TITLE
Resizing the Terminal window htop runs on with OS X causes a crash.

### ISSUE THREAD

**Issue by ddpwnage** [hishamhm/htop#326]
[A ZIP folder containing a screen recording.](https://github.com/hishamhm/htop/files/69552/htopbug.mov.zip)

Pretty much, if you resize the Terminal window htop is running on, running OS X El Capitan 10.11, it causes a crash. The log looks like this:

```
htop 0.8.2.7 aborted. Please report bug at http://htop.sf.net
0   htop                                0x000000010cce7a43 CRT_handleSIGSEGV + 30
1   libsystem_platform.dylib            0x00007fff898a952a _sigtramp + 26
2   libsystem_c.dylib                   0x00007fff938c6cd4 strcpy + 84
3   htop                                0x000000010cce782b AllCPUsMeter_draw + 71
4   htop                                0x000000010cce9854 Header_draw + 226
5   htop                                0x000000010ccea0c4 main + 1872
6   libdyld.dylib                       0x00007fff8b9a85ad start + 1
```

I know the crash is in the way it draws the meters for CPU usage, because disabling that and trying again works with no crash.

**Comment by hishamhm** [comment]
htop 0.8.2.7 is the unofficial fork. If you can compile the sources from Github, please give the one in this repository a try, and reopen if the bug persists!
