### ISSUE TITLE
Command field not updated beyond first read

### ISSUE THREAD

**Issue by yunake** [hishamhm/htop#329]
For example, I constantly observe it with gmrun: it does not fork, it simply execs the process I request, and htop continues to display its name as "gmrun" until I restart htop.

I'm not sure if there's a good strategy to address it - re-reading the process name on every tick is probably incredibly wasteful. Maybe do it once in awhile? Just wanted to let you know this issue exists.

**Comment by hishamhm** [comment]
"Update process names" was implemented as an option in htop 2.0!

**Comment by yunake** [comment]
thanks @hishamhm! works like a charm
