### ISSUE TITLE
multiple processes

### ISSUE THREAD

**Issue by fabianschwarzfritz** [hishamhm/htop#336]
Hi,

First things first: To be honest I am **not sure if this is an htop issue**. 
I am currently developing a service with [bosh](bosh.io/). During development I sometimes to check if specific processes are running, and what the system state is. I use _top_ for that. But simply because I like _htop_ more, I started using htop. 

However, I the processes displayed with _htop_ differ from the ones listed with _top_. 

In the vm instance attached on the screenshot, there is only one _mongodb_ running. with _top_ I only see one instance, with _htop_ I see multiple processes. Same with the *syslogd* service

It is so called "warden setup" - the state of the art how to develop services with bosh locally. For virtualisation vagrant and virtual box is used. [bosh-lite](https://github.com/cloudfoundry/bosh-lite).

Do you have any idea if this is an htop issue or another issue? Let me know if you need any additional information to examine this behavior

Cheers,
Fabian

![screen shot 2016-01-04 at 14 46 44](https://cloud.githubusercontent.com/assets/1759672/12090924/40491b28-b2f3-11e5-84b9-13f676ad4eb9.png)
![screen shot 2016-01-04 at 14 47 55](https://cloud.githubusercontent.com/assets/1759672/12090926/439b0e58-b2f3-11e5-8068-e2de6dc84925.png)

**Comment by kaefer** [comment]
I think this is explained by this link (top behaves similar as ps regarding this): 
http://unix.stackexchange.com/a/10403

you can see both htop and top reporting 20 tasks whereas top simply ignores multiple threads from one task

**Comment by fabianschwarzfritz** [comment]
Thanks for the fast response and the hint @kaefer :+1: . I'll close this one.
