### ISSUE TITLE
SIGSEGV when terminal < 42 characters wide on OSX

### ISSUE THREAD

**Issue by millerjs** [hishamhm/htop#353]
Version: 0.8.2.7

Stack dump (with addresses removed):
```
htop 0.8.2.7 aborted. Please report bug at http://htop.sf.net
0   htop                                0xxxxxxxxxxxxxxxxx CRT_handleSIGSEGV + 30
1   libsystem_platform.dylib            0xxxxxxxxxxxxxxxxx _sigtramp + 26
2   ???                                 0xxxxxxxxxxxxxxxxx 0x0 + 118572974680
3   htop                                0xxxxxxxxxxxxxxxxx Header_draw + 225
4   htop                                0xxxxxxxxxxxxxxxxx main + 1924
5   libdyld.dylib                       0xxxxxxxxxxxxxxxxx start + 1
6   ???                                 0xxxxxxxxxxxxxxxxx 0x0 + 1
```

Issue only appears on OSX afaict (thought I only attempted to reproduce on ubuntu 14.04).  Happens when resizing terminal as well as when increasing font size

**Comment by millerjs** [comment]
Considering the current version is `htop 1.0.3`, it seems this issue really isn't relevant, barring the fact that this is the default `brew` installation.

**Comment by kaefer** [comment]
brew formula will be updated as soon as @hishamhm will release a new official version.

**Comment by millerjs** [comment]
:+1: thanks
