### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by oneivan** [hishamhm/htop#354]
I used  mouse wheel scroll up and got htop crash

[htop.objdump.zip](https://github.com/hishamhm/htop/files/109369/htop.objdump.zip)

**Comment by oneivan** [comment]
+ I'm sure that filter works bad:  I have ps from user "sia" and can see all them in full list. but when I try F4(use filter) with "sia" list has no my process right : 
![htop_1](https://cloud.githubusercontent.com/assets/10061325/12669521/56a77aee-c672-11e5-84f4-1f8176a02854.png)
![htop_2](https://cloud.githubusercontent.com/assets/10061325/12669522/56a92fec-c672-11e5-8095-792772963bc6.png)

**Comment by kaefer** [comment]
which version of htop and which system are you running?

**Comment by Explorer09** [comment]
When you report a crash, did you copy the backtrace? You should have seen such message:
`Please include in your report the following backtrace:`

A mere objdump file (i.e. the disassembly) in not enough for us to determine what causes the crash.

**Comment by kaefer** [comment]
i think the filter function searches only in the command string. e.g. "/usr/bin/firefox" won't be displayed if you search for the user which runs firefox because the username doesn't show in the command.

**Comment by oneivan** [comment]
sorry for lack info , I hoped info in dump.
this is htop 1.0.3 version
filter shows every row with substr "sia" , so its works correct ,
thank you !

**Comment by hishamhm** [comment]
The filter works as expected and the crash refers to an outdated version. Closing this one!
