### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by rumpelsepp** [hishamhm/htop#358]
htop's latest release is almost 2 years old. What about bumping a new release, so that the improvements can be adopted by distributions and the bsds easily? :)

**Comment by kaefer** [comment]
this is already in the pipeline (source: https://github.com/hishamhm/htop/pull/356#issuecomment-177933081)

**Comment by rumpelsepp** [comment]
Nice; I searched the issue tracker, but I didn't find that one. :+1:
