### ISSUE TITLE
htop on Darwin incorrectly identifies process states

### ISSUE THREAD

**Issue by nevali** [hishamhm/htop#361]
This may be two separate issues, feel free to edit/split…

I've just built the current `master` of htop on Darwin 14.5.0 (Mac OS X Yosemite 10.10.5); it built and installed painlessly, but all processes (running as a normal unprivileged user) show as state `R`, and the 'tree' view shows almost all processes as being direct children of `kernel_task`, with the exception of the `login` processes launched by Terminal.app (and the descendent processes within those sessions), which show as having no parent task.

**Comment by nevali** [comment]
Interestingly, I note the running task _count_ is actually reported correctly (e.g., `Tasks: 337, 1285 thr; 3 running`)

**Comment by hishamhm** [comment]
Apparently this is because the code is using a BSD interface that doesn't work on Darwin:

A similar problem happened here:

https://communities.vmware.com/message/1920460#1920460

```
Sigar was using the BSD kinfo_proc.kp_proc.p_stat field, invalid for darwin.  Changed to get the state from the mach thread_info api.
```

Writing this here in case any OSX dev would like to try their hand at fixing this.

**Comment by hishamhm** [comment]
All right, so I bit the bullet, managed to get ahold of an OSX shell session temporarily, and tried my hand at fixing this issue.

Please let me know if current master is fixed. Thank you!

**Comment by pipping** [comment]
Yes, things are much better now! There's a proper tree structure *and* the arguments that were passed to the process are shown.

**Comment by hishamhm** [comment]
@pipping Thanks for the feedback!
