### ISSUE TITLE
missing commits for tag 2.0.0

### ISSUE THREAD

**Issue by eworm-de** [hishamhm/htop#362]
You pushed tag `2.0.0`, but there is no branch containing the commit(s) it points to.
Did you miss to merge and/or push?

**Comment by Explorer09** [comment]
I also noticed this too. These are missing from the current master branch:
807640e49b0d8b67b5bf424db0c221812483f55d , f1f805f29f6358aafc392c07d3569d143786961e , 563d5d3ab93e9e2d005123b29037345619ee2e5a

**Comment by hishamhm** [comment]
Ouch, sorry! Is it fixed now?

**Comment by eworm-de** [comment]
Looks good. Thanks a lot!
