### ISSUE TITLE
make error with separate build dir.

### ISSUE THREAD

**Issue by iEFdev** [hishamhm/htop#367]
I just installed `htop-2.0.0` from <http://hisham.hm/htop/releases/>.

It installed fine in OS X (10.7.5) with GCC 5.3. Though, first I tried using a separate build folder, then you get errors during `make`. So, I wanted to report that.

```make
../htop-2.0.0/Affinity.c: In function 'Affinity_get':
../htop-2.0.0/Affinity.c:90:4: error: unknown type name 'cpu_set_t'
    cpu_set_t cpuset;
    ^
../htop-2.0.0/Affinity.c:91:15: warning: implicit declaration of function 'sched_getaffinity' [-Wimplicit-function-declaration]
    bool ok = (sched_getaffinity(proc->pid, sizeof(cpu_set_t), &cpuset) == 0);
               ^
../htop-2.0.0/Affinity.c:91:51: error: 'cpu_set_t' undeclared (first use in this function)
    bool ok = (sched_getaffinity(proc->pid, sizeof(cpu_set_t), &cpuset) == 0);
                                                   ^
../htop-2.0.0/Affinity.c:91:51: note: each undeclared identifier is reported only once for each function it appears in
../htop-2.0.0/Affinity.c:95:11: warning: implicit declaration of function 'CPU_ISSET' [-Wimplicit-function-declaration]
       if (CPU_ISSET(i, &cpuset))
           ^
../htop-2.0.0/Affinity.c: In function 'Affinity_set':
../htop-2.0.0/Affinity.c:102:4: error: unknown type name 'cpu_set_t'
    cpu_set_t cpuset;
    ^
../htop-2.0.0/Affinity.c:103:4: warning: implicit declaration of function 'CPU_ZERO' [-Wimplicit-function-declaration]
    CPU_ZERO(&cpuset);
    ^
../htop-2.0.0/Affinity.c:105:7: warning: implicit declaration of function 'CPU_SET' [-Wimplicit-function-declaration]
       CPU_SET(this->cpus[i], &cpuset);
       ^
../htop-2.0.0/Affinity.c:107:15: warning: implicit declaration of function 'sched_setaffinity' [-Wimplicit-function-declaration]
    bool ok = (sched_setaffinity(proc->pid, sizeof(unsigned long), &cpuset) == 0);
               ^
Makefile:1377: recipe for target 'htop-Affinity.o' failed
make[1]: *** [htop-Affinity.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/path/to/htop/2.0/htop-2.0.0_build'
Makefile:522: recipe for target 'all' failed
make: *** [all] Error 2
```
_Both when using a build dir inside or outside the source directory._

- - -

Another thing... It would be nice if just the _basename_ of the commands would display, like in the old htop I had, and in `top`.

![htop_top](https://cloud.githubusercontent.com/assets/3958664/12981179/dace3a84-d0df-11e5-9f50-7f61212acab5.png)

_Those long names get cut off as well._

 

Else than that… Thanks! for a great update. :+1:

**Comment by Explorer09** [comment]
Just a reminder that you can scroll the screen with left and right arrow keys.
And, check your "Show program path" option in "Setup" -> "Display Options".

**Comment by hishamhm** [comment]
About the path names, try this: [F2] Setup → Display Options → [ ] Show program path

About building off-tree, I've never tried it. I'd welcome patches to fix it if it's easy, but it's not a real priority right now.

**Comment by iEFdev** [comment]
@hishamhm, @Explorer09 

Thanks… :+1: 

That'd be great. I always prefer using a separate build dir.
