### ISSUE TITLE
2.0 crash when move cursor in empty environment window.

### ISSUE THREAD

**Issue by infectormp** [hishamhm/htop#370]
Get a crash when try view environment of nginx worker process.

step to reproduce:
run htop, on nginx worker process pres 'e' then press down key.

htop(CRT_handleSIGSEGV+0x2f)[0x41980f]
/lib64/libc.so.6(+0x335f0)[0x7f84143405f0]
htop(Panel_draw+0x27c)[0x40d53c]
htop(InfoScreen_run+0x4d)[0x415d5d]
htop[0x4140e2]
htop[0x409bcf]
htop(ScreenManager_run+0x1a1)[0x410291]
htop(main+0x4b7)[0x407647]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7f841432d620]
htop(_start+0x29)[0x4077a9]
[htop.objdump.zip](https://github.com/hishamhm/htop/files/126881/htop.objdump.zip)

**Comment by infectormp** [comment]
same for php-fpm pool.

When i open environment view for this process htop not show any environment variable and when i try  move cursor down htop crash.

**Comment by hishamhm** [comment]
@infectormp Thank you for the report! I just committed a fix.
