### ISSUE TITLE
htop 2.0 in before 16.04 feature freeze?

### ISSUE THREAD

**Issue by kodyensley** [hishamhm/htop#372]
Will htop 2.0 make it into 16.04 before the feature freeze?

**Comment by Najoj** [comment]
I suppose you mean Ubuntu 16.04. Its feature freeze date is February 18 and htop 2.0 is already released.

**Comment by kodyensley** [comment]
I checked https://launchpad.net/ubuntu/xenial/+source/htop and didn't see 2.0 listed.

**Comment by hishamhm** [comment]
Hi! 

This bug tracker is for htop bugs — distribution issues should be posted in their specific trackers. Thank you!
