### ISSUE TITLE
FreeBSD MEM% 0

### ISSUE THREAD

**Issue by synthmeat** [hishamhm/htop#373]
All percentages in PERCENT_MEM column are always 0%.

FreeBSD 10.2-RELEASE-p9, htop 2.0.0

**Comment by Sp1l** [comment]
This has been fixed in the port, see
https://svnweb.freebsd.org/ports/head/sysutils/htop/files/patch-freebsd__FreeBSDProcessList.c?view=markup&pathrev=408842
Will generate a pull request
