### ISSUE TITLE
Command line options aren't displayed on Mac OS X

### ISSUE THREAD

**Issue by klas-genestack** [hishamhm/htop#379]
When I start  `./htop --user $(whoami)`, I can only see `./htop` in *htop*.

Mac OS X 10.11.3, *htop* from current ''master'' (`2.0.0-11-g1bedac1`)

**Comment by mhinz** [comment]
FWIW, it works for me on the same OS version, same commit.

**Comment by melomac** [comment]
Can reproduce, program arguments are missing. Please compare with `ps axu` output.

Tested on OS X 10.11.3 and commit 0b70439316b4e4608c0916317ded7e6e56982de6.

**Comment by mhinz** [comment]
Oops, I misread the issue. I can reproduce this as well. Sorry for the confusion.

**Comment by hunsakerbn** [comment]
The following patch fixes both the basename highlight problem and the process arguments not showing problem.

--- htop-2.0.0/darwin/DarwinProcess.c   2016-02-02 07:58:45.000000000 -0700
+++ htop-2.0.x/darwin/DarwinProcess.c   2016-02-18 14:09:59.000000000 -0700
@@ -286,9 +286,9 @@
       /* The command is from the old Mac htop */
       char *slash;

-      proc->comm = DarwinProcess_getCmdLine(ps, false);
-      slash = strrchr(proc->comm, '/');
-      proc->basenameOffset = (NULL != slash) ? (slash - proc->comm) : 0;
+      proc->comm = DarwinProcess_getCmdLine(ps, true);
+      proc->basenameOffset = strlen(DarwinProcess_getCmdLine(ps, false));
+
    }

    /* Mutable information */

**Comment by hishamhm** [comment]
Thanks @hunsakerbn for confirming this logic fixes the issue! I have a Mac shell currently available and I got a patch together that obtains the same results while calling DarwinProcess_getCmdLine only once.
