### ISSUE TITLE
Process information table does not resize with terminal window

### ISSUE THREAD

**Issue by mslinn** [hishamhm/htop#383]

**Comment by hishamhm** [comment]
Hi! More info is needed:

Version of htop? 
OS, and OS version?
Terminal emulator, and its version?
ncurses version?

Thank you!

**Comment by mslinn** [comment]
Current version provided by apt-get
XUbuntu 15.10
xfce4-terminal current
No idea about ncurses version

**Comment by hishamhm** [comment]
> Current version provided by apt-get

Please type `htop --version` for the exact version. :)

**Comment by mslinn** [comment]
htop 1.0.3

**Comment by hishamhm** [comment]
I can't reproduce it here. It should resize correctly. Make sure you don't have the environment variables COLUMNS and LINES hardcoded in your terminal for any reason. If the problem persists, try to upgrade htop to the latest version. Thank you!

**Comment by ManuelSchneid3r** [comment]
I have the same issue. But only if I run it from qtcreator in debug mode. I dont think htop is the reason. But I want to find the bug. Who sets the size while  htop is running? SIGWINCH? The debug shells are at SHLVL=3 may this be the cauae? Are signals forwarded to subshells?

**Comment by hishamhm** [comment]
ncurses listens to SIGWINCH and then sends a KEY_RESIZE event to htop, which consumes it with getch().
