### ISSUE TITLE
Resident memory usage appears to be incorrect on OS X

### ISSUE THREAD

**Issue by shssoichiro** [hishamhm/htop#385]
I have taken a screenshot of my current htop to demonstrate.

<img width="1412" alt="screen shot 2016-02-12 at 8 57 24 am" src="https://cloud.githubusercontent.com/assets/5951392/13008815/be9e385a-d166-11e5-9c6d-83ec41378ddf.png">

(Though not displayed, the total memory usage is currently shown as 6.5 GB out of 16 GB.)

There are a couple of discrepancies to note.

1. If you add up the resident memory values for these processes, it comes to over 23 GB. This is not including many <100M processes that are off the screen. This is completely different from what the overall memory meter shows, and is more than the total memory on this system.
2. If we take Finder for example, this process shows a resident memory usage of 2536 M, or 3.9% of total memory. 3.9% of the total memory would be 624 MB, however.
3. The largest Chrome process in htop appears to be using 1896 M. However, Chrome's task manager shows that process's usage as 474 MB. (I've also never seen a single Chrome process use 1896 M of resident memory.)

In general, the resident memory usage appears to be much higher than the actual usage. This issue does not seem to occur on Linux with htop 2.0.

**Comment by hishamhm** [comment]
Looks like all values are multiplied by 4 (ie, values should be divided by the page size). This commit should fix this (please give the code now in Git a try if possible!).

**Comment by shssoichiro** [comment]
Tested on OS X, memory values appear to be correct now. Values are still correct on Linux as well. Thanks for the quick fix!
