### ISSUE TITLE
htop 2 on OSX

### ISSUE THREAD

**Issue by PhillippOhlandt** [hishamhm/htop#386]
I read that htop is now available on OSX.

But how can I install it? The [download page](http://hisham.hm/htop/index.php?page=downloads#binaries) doesn't have any binaries for OSX and homebrew gives me `0.8.2.8`.

**Comment by mrvkino** [comment]
There is now a htop install in homebrew called "htop" that is linked to the current version (the one you are talking about is called htop-osx in homebrew).

**Comment by PhillippOhlandt** [comment]
I tried `brew install htop` after I read about the htop 2 release. Installed from source now.

**Comment by PhillippOhlandt** [comment]
For all others:
I had to update homebrew to get the new `htop` package.

```
Phillipps-MacBook-Pro ~/Downloads/htop-2.0.0$ brew search htop
htop                                                                                                                    htop-osx
Caskroom/cask/splashtop-personal                                                                                        Caskroom/cask/splashtop-streamer
```

**Comment by jtyle6** [comment]
Just do `./configure; make; sudo make install` from the unpacked folder.

**Comment by PhillippOhlandt** [comment]
Yeah as said earlier, I built it from source.

**Comment by xeoron** [comment]
You can, also, use https://www.macports.org/ to grab it from the repository
and it will compile and install it.
 MacPorts install instructions: https://www.macports.org/install.php

Once Macports is installed, to get htop, all you have to do in the terminal
is type: sudo port install htop
It will grab any dependencies, compile and install them, too.

-Jason
