### ISSUE TITLE
Sorting by aggregate of CPU, memory and IO

### ISSUE THREAD

**Issue by vi** [hishamhm/htop#389]
Is it a good idea?

I personally use a modified version of htop-0.9 with an additional column "SK" (sort key) consisting of weighted sum of CPU percentage, memory usage, IO, being in uninterruptible sleep and being a main thread of a process.

Shall I try preparing a pull request based on those my local changes?

**Comment by jvaelen** [comment]
Yes please.

**Comment by vi** [comment]
@jvaelen, Ready.
