### ISSUE TITLE
Highlight program "basename" on OS X

### ISSUE THREAD

**Issue by melomac** [hishamhm/htop#392]
On OS X, Highlight program "basename" option highlights wrong path component, i.e.:
/Applications/Contacts.app/Contents/**MacOS**/Contacts

instead of:
/Applications/Contacts.app/Contents/MacOS/**Contacts**

Tested on OS X El Capitan 10.11.3 and commit 0b70439316b4e4608c0916317ded7e6e56982de6.

**Comment by hishamhm** [comment]
Should be fixed now! Please check latest git, please reopen in problem persists.

**Comment by mhinz** [comment]
Much better now. :+1: Thanks for all the recent OSX fixes.
