### ISSUE TITLE
Tree view on OS X

### ISSUE THREAD

**Issue by melomac** [hishamhm/htop#393]
The tree view looks surprisingly flat on OS X, as most programs are children of `kernel_task`.

Tested on OS X El Capitan 10.11.3 and commit `0b70439316b4e4608c0916317ded7e6e56982de6`.

**Comment by hishamhm** [comment]
What happens when you open a terminal, and then launch bash, and inside it launch bash again? Does it show a hierarchical tree?

**Comment by mhinz** [comment]
> What happens when you open a terminal, and then launch bash, and inside it launch bash again? Does it show a hierarchical tree?

I did that with zsh. On the right side you can see them all listed in line, although it should show a "stair". On the left side I manually follow the parents via `ps` up to the `login` process.
