### ISSUE TITLE
htop: setCommand(): htop killed by SIGABRT on Fedora 23

### ISSUE THREAD

**Issue by mortenstevens** [hishamhm/htop#405]
Hello,

I'm co-maintaining the htop package for Fedora. We have a bug report with a strange htop crash. I'm not able top reproduce this error.

Here is the Fedora bug report with additional details: https://bugzilla.redhat.com/show_bug.cgi?id=1308359

Backtrace: https://bugzilla.redhat.com/attachment.cgi?id=1127060

**Comment by mortenstevens** [comment]
It crashes using a configuration file written by old versions of htop.
Here is an example htop file that crashes 2.0.0: https://bugzilla.redhat.com/attachment.cgi?id=1127293

# Beware! This file is rewritten by htop when settings are changed in the interface.
# The parser is also very primitive, and not human-friendly.
fields=0 48 17 18 38 39 40 2 46 47 49 1 
sort_key=46
sort_direction=1
hide_threads=0
hide_kernel_threads=1
hide_userland_threads=0
shadow_other_users=0
show_thread_names=1
highlight_base_name=1
highlight_megabytes=1
highlight_threads=1
tree_view=1
header_margin=1
detailed_cpu_time=0
cpu_count_from_zero=0
update_process_names=1
account_guest_in_cpu_meter=0
color_scheme=0
delay=5
left_meters=AllCPUs Memory Swap 
left_meter_modes=1 1 1 
right_meters=Tasks LoadAverage Uptime 
right_meter_modes=2 2 2

**Comment by hishamhm** [comment]
Thanks for reporting! This is already fixed in current git. For a workaround, set `update_process_names=0`

**Comment by mortenstevens** [comment]
Thank you. Could you point me to the mentioned commit? Then we could backport it to Fedora. Thank you.

**Comment by hishamhm** [comment]
(You might have gotten the original comment on email, I had just edited my comment adding a link to the commit and more info: https://github.com/hishamhm/htop/commit/0b70439316b4e4608c0916317ded7e6e56982de6 )

**Comment by mortenstevens** [comment]
@hishamhm 
All right. Thank you. It 's now backported to Fedora with commit http://pkgs.fedoraproject.org/cgit/rpms/htop.git/commit/?id=28ef2bf7ec01aab25ea528db0efc5f416b40f7d1
