### ISSUE TITLE
-Wmisleading-indentation

### ISSUE THREAD

**Issue by JIghtuse** [hishamhm/htop#409]
Hey. Just built gcc6 and decided to check its [new warnings](https://gnu.wildebeest.org/blog/mjw/2016/02/15/looking-forward-to-gcc6-many-new-warnings/). It spotted only one issue with misleading indentation:

    linux/LinuxProcessList.c: In function ‘LinuxProcessList_readIoFile’:
    linux/LinuxProcessList.c:299:13: warning: statement is indented as if it were guarded by... [-Wmisleading-indentation]
                 process->io_syscw = strtoull(line+7, NULL, 10);
                 ^~~~~~~
    linux/LinuxProcessList.c:297:15: note: ...this ‘if’ clause, but it is not
              else if (strncmp(line+1, "yscw: ", 6) == 0)
                   ^~

I don't know what all these `yscw` and `yscr` mean, but this warning looks valid.

**Comment by Explorer09** [comment]
It's `syscw` and `syscr` (for `/proc/{pid}/io`) if you understand the context. However, it's a pity that they implement a tree-like pattern matching code without making it more readable.

**Comment by Explorer09** [comment]
Wait a minute. You caught a bug.
The io_syscw variable is read two times. One of them is outside strcmp("syscw") , and so the `syscr` value will be read to io_syscw variable where it's not intended to.

    /* Line 294-300 */
       case 's':
          if (line[5] == 'r' && strncmp(line+1, "yscr: ", 6) == 0)
             process->io_syscr = strtoull(line+7, NULL, 10);
          else if (strncmp(line+1, "yscw: ", 6) == 0)
             sscanf(line, "syscw: %32llu", &process->io_syscw);
             process->io_syscw = strtoull(line+7, NULL, 10);
          break;

**Comment by hishamhm** [comment]
Thank you @JIghtuse for the report and @Explorer09 for the analysis!

It looks like something produced out of an automatic merge that went unnoticed.
Fixing it!
