### ISSUE TITLE
Crash upon deletion of last item in column [2.0.0] [OS X]

### ISSUE THREAD

**Issue by admiral-Guck** [hishamhm/htop#412]
htop 2.0.0 built on OS X 10.10.5 with `brew install htop --with-ncurses`
ncurses 6 is installed correctly, i.e. scrolling works :smile:

In setup, when deleting any last item from any column, htop crashes immediately as follows:

````
0   htop                                0x000000010d272757 CRT_handleSIGSEGV + 69
1   libsystem_platform.dylib            0x00007fff8fb2ef1a _sigtramp + 26
2   ???                                 0x4600277289d35065 0x0 + 5044074955547037797
3   htop                                0x000000010d26c251 ScreenManager_run + 696
4   htop                                0x000000010d27026b actionSetup + 134
5   htop                                0x000000010d265d33 MainPanel_eventHandler + 483
6   htop                                0x000000010d26c251 ScreenManager_run + 696
7   htop                                0x000000010d2674bb main + 1131
8   libdyld.dylib                       0x00007fff880865c9 start + 1
````

otool output [in this gist](https://gist.github.com/admiral-Guck/f7ae626e239e7f5ea0bf).

**Comment by Explorer09** [comment]
Could you please try the latest development version (this git master branch)? I believe this has been fixed already. (Issue #381)

    git clone https://github.com/hishamhm/htop htop
    cd htop
    ./autogen.sh && ./configure && make

**Comment by hishamhm** [comment]
Yes, this is the same as #381. Thanks for reporting!

**Comment by admiral-Guck** [comment]
Yep, fixed in latest devel version, thanks!
