### ISSUE TITLE
Feature request: text info for cache/buffer

### ISSUE THREAD

**Issue by fourzerofour** [hishamhm/htop#415]
Can we have text info meter for similar info given under the `shared`, `buff/cache` and `available` columns in `free -m` command?

**Comment by Explorer09** [comment]
I'm not using the recent Linux kernel or procps, so I cannot see the `available` field in `free` command (or the equivalent `MemAvailable` in `/proc/meminfo`). Just for the info, `MemAvailable` is available only in Linux kernel 3.14+. For earlier version you have to emulate the field or hide it completely.

I personally don't believe `buff/cache` (the sum of `buffers` and `cache`) is useful in htop.

For `shared` (`Shmem` in `/proc/meminfo`) field, I don't know and can't make opinions on it.

**Comment by Explorer09** [comment]
Bring pull request #96 together with this one. The two requests look similar.

**Comment by fourzerofour** [comment]
Sorry I beg to differ. `buff/cache` info can be pretty useful ie when you have ramdisk (ie tmpfs) mounted. Is your memory usage ballooning because running apps taking memory or because your ramdisk space is filling up?

    % free -m
                total        used        free      shared  buff/cache   available
    Mem:           2008         578         759         166         671        1231
    Swap:          4095         142        3953

    % dd if=/dev/zero of=/mnt/ramdisk/test.bin bs=1M count=500
    500+0 records in
    500+0 records out
    524288000 bytes (524 MB, 500 MiB) copied, 1.40682 s, 373 MB/s

    % free -m
                total        used        free      shared  buff/cache   available
    Mem:           2008         577         260         666        1170         733
    Swap:          4095         142        3953

    % rm /mnt/ramdisk/test.bin
    % free -m
                total        used        free      shared  buff/cache   available
    Mem:           2008         570         772         160         665        1245
    Swap:          4095         142        3953

**Comment by Explorer09** [comment]
@fourzerofour 
htop already has separate `buff` and `cache` for memory meters.
What I said is that the _combined_ total of buff and cache is not useful.
Your `free` is too new so you may not notice, but my `free` output has buff and cache separated:

    $ free --version
    free from procps-ng 3.3.9
    $ free -m
                 total       used       free     shared    buffers     cached
    Mem:          7897       5282       2614        461        163       1736
    -/+ buffers/cache:       3382       4514
    Swap:         2047          0       2047
