### ISSUE TITLE
tree view collapsing/expanding on OSX

### ISSUE THREAD

**Issue by mikazuki** [hishamhm/htop#416]
When collapsing tree nodes in OSX I'm unable to expand them again.
I've built htop with and without ncurses (using the homebrew formulae).

I've tried to: double click a collapsed entry, press F6 on a collapsed entry, press + on a collapsed entry.
Neither works to expand the subtree again.
The subtree can only be expanded after relaunching htop.

Might be related to #393 since also the nesting of tree elements isn't correct.

**Comment by hishamhm** [comment]
Thank you for the report! I just fixed the bug.
