### ISSUE TITLE
ncurses & functions bar ESC key issues

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#417]
(Note: I'm not ready to provide patches for you now. Otherwise I'll make this a pull request.)

For ncurses apps, ESC key doesn't take effect immediately, but rather have 1 or 2 seconds delay. IIRC, this is part of ncurses's design in order to differentiate ESC key from other function keys. This is what it says in ncurses manual: "Use of the ESC key by a programmer for a single character function is discouraged, as it will cause a delay of up to one second while the keypad code looks for a following function-key sequence." ([source](https://www.gnu.org/software/guile-ncurses/manual/html_node/Getting-characters-from-the-keyboard.html))

And see also (http://en.chys.info/2009/09/esdelay-ncurses/) for info about Esc key delay.

While this looks like only key issues, it's not. It also affects function bar commands (in htop) that simulates an ESC key press, with mouse clicks. Here are scenarios (and steps to produce):

(1) On htop main screen, mouse-click `[F3]Search` on the functions bar.
(2) Click `[Esc]Cancel` then, and observe a 1- or 2-second delay.

(1) With a process selected to kill, mouse-click `[F9]Kill`.
(2) Click `[Esc]Cancel` and also observe a delay.

Pressing ESC twice in ncurses will work like a single ESC in other GUI apps, but without delay. However, I didn't find out how to send out double ESC together for FunctionBar class (hence no patches yet). If that's impossible, then we will need other solutions.

I set up this issue so we may discuss whether we need to avoid the ESC problem, or resolve that, and how to resolve.

**Comment by hishamhm** [comment]
Since we depend on ncurses, I think ESCDELAY is the way to go. I'm already using it on Dit, I simply forgot to put it on htop.

My trivial attempt to put it there didn't work, though, so I'll have to give it a closer look; it's probably interacting with the other halfdelay() features, etc.

But sure, let's fix this!

**Comment by Explorer09** [comment]
WAIT! I don't believe this is over! Although setting ESCDELAY does bring down the ESC key delay, the Function Bar "Events" things still use it internally, so clicking on those will still give _milliseconds_ of delay, even though user will not notice.

My I try to be a perfectionist here, and have those mouse events avoid sending the ESC code whenever possible? It would be like what I've tried in pull request #414, except that we retain the "Esc" word on the UI and change only the event to send F10 internally.

(And as a side note, I don't like seeing the magic number 27 everywhere in source files. My we define a KEY_ESC macro and use that instead? This would help when using `grep -r`.)
