### ISSUE TITLE
Feature: Adapt layout to term dimensions

### ISSUE THREAD

**Issue by admiral-Guck** [hishamhm/htop#419]
I'd be lovely if htop were to adapt to the term it's running in. By adding some kind of conditionals to config files, htop could switch between layouts based on them. I'm thinking primarily about dimensions, since my use case is putting htop in a wide but low pane to keep a general eye on things. Guess it could be made to know about lots of stuff once some kind of grammar is established.

**Comment by hishamhm** [comment]
It already adapts according to size, spreading its two meter columns. As for a "general configuration grammar", no, that's not in the plans, sorry.
