### ISSUE TITLE
Debian 8.3 - libncursew error during configure.

### ISSUE THREAD

**Issue by FlorentATo** [hishamhm/htop#422]
Hi,

I'd like to compile htop 2.0 on Debian 8.3 but I encounter the following error in the configure process:

```
(...)
checking for addnwstr in -lncursesw... no
checking for addnwstr in -lncurses... no
checking for addnwstr in -lncursesw6... no
checking for addnwstr in -lncursesw... (cached) no
checking for addnwstr in -lncurses... (cached) no
configure: error: You may want to use --disable-unicode or install libncursesw.
ato@kimsufi-ato:~/htop$ sudo apt-cache search libncursesw
libncursesw5 - shared libraries for terminal handling (wide character support)
libncursesw5-dbg - debugging/profiling libraries for ncursesw
ato@kimsufi-ato:~$ sudo locate libncursesw
[sudo] password for ato: 
/lib/x86_64-linux-gnu/libncursesw.so.5
/lib/x86_64-linux-gnu/libncursesw.so.5.9
(...)
```

I tried to analyze configure (the file) but I couldn't find a way to set the path to the lib.
Thank you for your time :)

**Comment by kaefer** [comment]
I had the same problem as you (`libncursesw5` installed, but `./configure` won't find it).

Installing the `libncursesw5-dev` package solved this. 
(Note: I'm on Kubuntu 15.10)

**Comment by hishamhm** [comment]
Thanks @kaefer for elucidating @FlorentATo's issue :)

**Comment by FlorentATo** [comment]
Sorry for the late reply and thanks @kaefer for the trick. I confirm this solved the issue.
However, I was expecting some explanations regarding why htop 2.0 requires libncursesw5-dev. Since I run Debian Jessie, I would have preferred not to install developer libraries on it. Thoughts @hishamhm ?
Thanks.

**Comment by hishamhm** [comment]
@FlorentATo Compiling requires developer libraries, running doesn't.

**Comment by edgiru** [comment]
configure: error: You may want to use --disable-unicode or install libncursesw.

**Comment by michaelmoldawski** [comment]
Thanks for this solution FlorentATo,  it worked for me :)

**Comment by emilfihlman** [comment]
This issue is still present on Debian stretch 9.4., .configure does not detect version 5 of libncurses
