### ISSUE TITLE
htop 2.0.0 aborting when pressing `q` key to quit

### ISSUE THREAD

**Issue by eocasio** [hishamhm/htop#424]
htop 2.0.0 aborting when pressing `q` key to quit. objump file attached.

Backtrace: 
htop(CRT_handleSIGSEGV+0x3a)[0x806065a]
[0x322400]
/lib/i386-linux-gnu/libc.so.6(+0x75aa8)[0x710aa8]
htop(Hashtable_delete+0x33)[0x8050b53]
htop(ProcessList_done+0x13)[0x8055a63]
htop(ProcessList_delete+0x10)[0x805fa10]
htop(main+0x5df)[0x804d81f]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x6b44d3]
htop[0x804d8f9]

`file $(which htop)
/usr/local/bin/htop: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0xe42d581734744260fea16e2e9bb7300f7b542bef, not stripped`

[htop.objdump.zip](https://github.com/hishamhm/htop/files/145671/htop.objdump.zip)

**Comment by hishamhm** [comment]
htop 2.0.1 was just released containing various fixes that should fix crash bugs, please upgrade! If it crashes again, feel free to post a new bug.
