### ISSUE TITLE
Large virtual address spaces cause 

### ISSUE THREAD

**Issue by puellanivis** [hishamhm/htop#425]
I'm using Go on OSX and it generally decides to give its process about half a terabyte of virtual memory. When displaying a `%3.1f` digit 'G', it would be nice if it kept alignment.

<pre>13620 cassandr  31   0 546.8G  1828     0 S  0.0  0.0  0:00.00 ./stub -alsologt
50043 cassandr  31   0 546.8G 18404     0 S  0.0  0.1  0:01.99 dremel -alsologt
  256 cassandr  55   0 5346M  261M     0 S  0.0  1.6  0:08.29 /System/Library/C
87275 cassandr  31   0 4625M  305M     0 S  0.0  1.9  0:00.27 /Applications/Goo
76689 cassandr  42   0 4600M 2082M     0 S  1.0 12.7  2:42.70 /Applications/Vir
</pre>

For the record, no, my machine is actually pretty usable... not peppy, but not bad considering it has some number of tibibytes of virtual memory.

**Comment by hishamhm** [comment]
@puellanivis Is this with 2.0.0 or the latest `master`?

**Comment by puellanivis** [comment]
Ugh.... yeah, it was a way older version, 0.8.2.8 ...
