### ISSUE TITLE
htop 2.0.0 aborting 

### ISSUE THREAD

**Issue by hbfl** [hishamhm/htop#431]
htop(CRT_handleSIGSEGV+0x42)[0x80615d2]
linux-gate.so.1(__kernel_sigreturn+0x0)[0xb775b410]
/lib/libc.so.6(+0x74678)[0xb75c1678]
htop(Hashtable_remove+0x65)[0x80518b5]
htop(ProcessList_remove+0x1f)0x80566ef]                                                                                          htop(ProcessList_scan+0xa7)0x8056b97]                                                                                            
htop(ScreenManager_run+0xd9)0x80575b9]                                                                                            
htop(main+0x53c)0x804e2cc]                                                                                                            
/lib/libc.so.6(__libc_start_main+0xf9)0xb75660d9]                                                                                    
htop[0x804e445] 

compiled for eisfair
[htop.objdump.txt](https://github.com/hishamhm/htop/files/155299/htop.objdump.txt)

Kernel 3.2.75
GLibC 2.15
GCC   4.7.4
ld        2.23.2

**Comment by hishamhm** [comment]
Thank you for reporting! htop 2.0.1 was released containing various fixes, please upgrade! If it crashes again, feel free to post a new bug.
