### ISSUE TITLE
Htop batch mode like top -b

### ISSUE THREAD

**Issue by cgx027** [hishamhm/htop#432]
Is there a batch mode in Htop like `top -b` do? 

I would love to capture the htop log into a file an then parse it.

BTW, htop is a great tool and I love it a lot.

**Comment by mattbent** [comment]
@hishamhm I am currently working towards this feature because I do find it very handy.  I would like to branch off of the master project to continue to work towards this feature.  I also greatly enjoy htop and run it on all of my machines.  Thank you for such a great tool.
