### ISSUE TITLE
Side effect: Alt+O, Alt+P as PageDown and PageUp

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#438]
Commit c23d4f12d , which defines Alt key combinations as (KEY_F(60)+(c-'A')) actually overflows with my ncurses version (my <curses.h> says that KEY_F(63) is the maximum). This brings a funny side effect that the key codes of Alt+O and Alt+P collide with PageDown and PageUp, respectively.

This is not necessary a bug, but it's better to have this side effect documented or avoid it.

**Comment by hishamhm** [comment]
Good catch, thanks

**Comment by Explorer09** [comment]
f295a52 fixes nothing. You just made them Alt+K and Alt+L instead, which is worse as they collide with Alt+{H,J,K,L} scrolling.
The right way would be: `#define KEY_ALT(x) KEY_F(64-26) + (x - 'A')`
