### ISSUE TITLE
ZFS buffer/cache is counted under used memory

### ISSUE THREAD

**Issue by borutmrak** [hishamhm/htop#44]
I'm running zfsonlinux and htop is counting the ZFS ARC (memory) cache under normal used memory.

This is because ZFS doesn't use normal Linux memory cache but it's own version.

It would be useful if htop could detect if ZFS is running (maybe checking for /dev/zfs) and in that case show the memory used by ZFS cache in a different colour or maybe joined with the normal buffers/cache.

ARC used memory can be checked in /proc/spl/kstat/zfs/arcstats (size):

```
# grep ^size /proc/spl/kstat/zfs/arcstats 
size                            4    3533162592
```

**Comment by flaviut** [comment]
It looks like ARC space is considered correctly on FreeBSD, but not Linux.

Is this bug something you're willing to re-open?

**Comment by xornet-sl** [comment]
@hishamhm Please, could you consider adding this feature for linux?
It would be great if I could see ARC statistics by different color in memory bar and as a different counter!
It would be very useful feature!

**Comment by Harvie** [comment]
This is still a problem. Can you please take a look at it?
