### ISSUE TITLE
htop 0.8.22  aborted 

### ISSUE THREAD

**Issue by wangping25** [hishamhm/htop#451]
brew installed on Mac 10.11.1

htop 0.8.2.2 aborted. Please report bug at http://htop.sf.net
0   htop                                0x00000001094d4a47 CRT_handleSIGSEGV + 30
1   libsystem_platform.dylib            0x00007fff9989952a _sigtramp + 26
2   htop                                0x00000001094e5348 scales + 2728
3   htop                                0x00000001094d482f AllCPUsMeter_draw + 71
4   htop                                0x00000001094d6858 Header_draw + 226
5   htop                                0x00000001094d70c8 main + 1872
6   libdyld.dylib                       0x00007fff8a7995ad start + 1
7   ???                                 0x0000000000000001 0x0 + 1

**Comment by kaefer** [comment]
This is a very old, unsupported fork of htop. Please install the most recent version (also available via homebrew).
