### ISSUE TITLE
Feature Request: Better Process Selection

### ISSUE THREAD

**Issue by phatmanace** [hishamhm/htop#453]
Hi.

I'm a long time htop user. One feature I've always wanted is better process filtering - I know I can do things like "all processes for user" but I'd like to have some other options like
- only show me processes that are a child of process x or y
- only show me processes that match a regex

If you think its reasonable - I'd be happy to have  a go at coding it and submit as a pull request

Let me know what you think

**Comment by Explorer09** [comment]
Showing only processes that match a regex is already proposed. Check out pull request #428.
About showing processes that are child of something... I don't know.

**Comment by phatmanace** [comment]
Ok - that's fine I'll leave the regex to #428 

hopefully people might find the "all processes that are a child of..." useful. Example would be if you run a "ports install foo" or something - you might select the parent bash process and htop would just show you everything that's a child of that process

**Comment by hishamhm** [comment]
I'm not a fan of this idea, to be honest. I think tree view already does a good job at visually organizing child processes.
