### ISSUE TITLE
graph glitches

### ISSUE THREAD

**Issue by zaza42** [hishamhm/htop#455]
I'm using htop 2.0.1 on Debian Stretch i386, and noticed the load graph shows nothing. It was also a problem with 2.0.0.  Is it caused by the low (<1) values? Can i multiply the values where the top line represents load 1.0?
The cpu graph works with rxvt-unicode, but with rxvt-unicode-lite it has an ugly top line.
You can see on attached screenshot. Is it rxvt bug or htop?
![gkrellshoot_03-20-16_070148](https://cloud.githubusercontent.com/assets/16356124/13903125/85f3a0d4-ee6d-11e5-9043-593814b9bd64.png)

**Comment by hishamhm** [comment]
Hi!

> Is it caused by the low (<1) values? 

Yes, not all graphs "make sense" in all modes. The problem with Load as a graph is that there is no "maximum load" value, so there's no way to calibrate the Y axis.

> Is it rxvt bug or htop?

The top line thing is either a bug in your terminal or in your system's fonts.
