### ISSUE TITLE
CPU usage is wrong on FreeBSD

### ISSUE THREAD

**Issue by main--** [hishamhm/htop#456]
All of htop's bars are set to 100% nice

```
  1  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   4  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   7  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   10 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  2  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   5  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   8  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   11 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  3  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   6  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   9  [||||||||||||||||||||||||||||||||||||||||||||100.0%]   12 [||||||||||||||||||||||||||||||||||||||||||||100.0%]
  Avg[||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||100.0%]   Tasks: 781; 15 running
  Mem[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                        11.7G/63.4G]   Load average: 3.23 2.89 2.70
```

while top accurately reports:

```
CPU:  2.4% user, 17.3% nice,  2.7% system,  0.2% interrupt, 77.4% idle
```

The load is caused mainly by a nice process that uses about 200% CPU. This individual process CPU usage however is incorrectly reported in htop as ~1%.

(htop 2.0.1 from FreeBSD ports)

**Comment by Limman** [comment]
I can confirm problem with display CPU usage. 
FreeBSD 10.2 + htop 2.0.1 (from ports)
top: CPU:  0.1% user,  0.0% nice,  1.2% system,  0.0% interrupt, 98.6% idle
Wrong CPU usage in bars and a table column. Sorted by CPU (desc):
![htop_2 0 1_freebsd](https://cloud.githubusercontent.com/assets/9432322/13948460/2f32ee4c-f031-11e5-9669-37ea0da186c5.png)

**Comment by formatj** [comment]
FreeBSD 10.2-RELEASE-p7
![untitled-2](https://cloud.githubusercontent.com/assets/5443422/14256207/b7908622-faa0-11e5-9e14-c1162ea5e215.jpg)

**Comment by hishamhm** [comment]
Hi! Thank you all for your reports!

Could you check if problem also happens with htop 2.0.0?

If it _doesn't_ happen in 2.0.0, is anyone able to help out running `git bisect` to help to track this down?

**Comment by main--** [comment]
Okay, so after some bisecting I think I finally know what happened. Unsurprisingly, this is heavily related to #399. There are two distinct issues here: Without #399, the CPU percentage of *individual processes* is too low. After it, *this is fixed* but now the per-core CPU bars are wrong.

In fact, my testing indicates that everything was perfect as of d753996b967166b351dd1bffbc65c8c3a3b703a6. Contrary to what the commit message says, this commit not only fixes memory percentage (well - it *may* do so but I didn't test that) but also removes code that divides the CPU percentage by the number of CPU cores.

Apparently, f554f08fa92f8440faa853b5fa4d588829959c8a then *attempted* to do the same (except that it multiplies instead of just not dividing) for the CPU bars - even though they were already correct. As a result, they're too high.

I'm not too familiar with htop internals or the relevant FreeBSD APIs, so it would be best if someone who is could review the affected code, but it seems to me that reverting f554f08fa92f8440faa853b5fa4d588829959c8a could fix everything.

**Comment by gaod** [comment]
After my testing, it seems reverting f554f08fa92f8440faa853b5fa4d588829959c8a could not fix this issue.

**Comment by donileo** [comment]
I believe I am seeing the same.. On idle my cpu bars on freebsd are always spiking.. I see them go from 0 to 100% and back.. mostly consisting of the kernel. I look at the same info via top.. and look at my individual cores and I see 99% + idling in all my cores which is correct. Is there any fix for this, assuming it is some form of bug?

**Comment by ahmedhamdy90** [comment]
Hello guys, 
You have closed the issue that hasn't been solved!
I still have the same problem till now in 2018...
