### ISSUE TITLE
Htop crashes when trying removing all elements from right column

### ISSUE THREAD

**Issue by Drulex** [hishamhm/htop#459]
In an attempt to have an empty right column, removing the last element from the column crashes htop with the following backtrace:

htop(CRT_handleSIGSEGV+0x2f)[0x419a0f]
/usr/lib/libc.so.6(+0x33330)[0x7f6930f2d330]
htop(MetersPanel_setMoving+0x1a)[0x40c7fa]
htop[0x40cb23]
htop(ScreenManager_run+0x1a1)[0x410291]
htop[0x414e2b]
htop[0x409b5f]
htop(ScreenManager_run+0x1a1)[0x410291]
htop(main+0x4b7)[0x4075e7]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7f6930f1a710]
htop(_start+0x29)[0x407749]

[htop.objdump.txt](https://github.com/hishamhm/htop/files/197699/htop.objdump.txt)

htop --version
htop 2.0.0 - (C) 2004-2016 Hisham Muhammad
Released under the GNU GPL.

uname -a
Linux DRUPAD-T440 4.4.3-1-ARCH #1 SMP PREEMPT Fri Feb 26 15:09:29 CET 2016 x86_64 GNU/Linux

**Comment by Drulex** [comment]
Just noticed that having the right column empty can be achieved by adding a "blank" element.

**Comment by hishamhm** [comment]
in any case, this crash is fixed in htop 2.0.1 :)
