### ISSUE TITLE
Question: Termux & Htop

### ISSUE THREAD

**Issue by Geyup** [hishamhm/htop#460]
Hello,

Have you seen Termux, and any relation to htop?

https://termux.com/

Hmm sure look the same...

**Comment by Explorer09** [comment]
Termux is a terminal emulator like xterm, rxvt or gnome-terminal. And what you see is that htop can be run on top of Termux. That's it.

But it is interesting to see htop operating on such a screen size (I mean, on narrow width terminals that is common on mobile). The htop meters were not designed for such use, so you should have see that the text of the "Tasks" meter has be cut off.

**Comment by Geyup** [comment]
thanks
