### ISSUE TITLE
Add GPU monitoring or plug in interface for top display

### ISSUE THREAD

**Issue by mbostwick** [hishamhm/htop#461]
Video cards and drivers have special drivers (and therefore top information), however, having some method for other groups to add support for GPU top displays would be very useful.

Here are some of the different top displays that exist for GPU's:
https://github.com/clbr/radeontop
for closed source:aticonfig --odgc --odgt
https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/
https://developer.nvidia.com/nvidia-system-management-interface
https://github.com/al42and/cuda-smi

**Comment by Explorer09** [comment]
It will be a big effort to support GPU monitoring in htop, and I don't think there will be a plugin system for htop soon. So, could you describe precisely what kind of monitoring you are expecting in htop? There are many things to monitor for GPUs, you know.

**Comment by mbostwick** [comment]
I apologies for not responding. 
This request was targeted at htop being the linux equivalent of [process hacker](http://processhacker.sourceforge.net/). 

![image](https://cloud.githubusercontent.com/assets/547590/21646523/1db98e38-d25c-11e6-8796-b6479572cb79.png)

**Comment by JustinWick** [comment]
I would absolutely love this feature as well. nvidia-smi doesn't offer the sort of "dashboard" style status display that htop does, and if I'm monitoring CPU load usually I also wish to monitor GPU load as well.

**Comment by Ly0n** [comment]
Check this htop like nvtop for nvidia GPUs:
https://github.com/Syllo/nvtop

Maybe a fusion is possible of nvtop and htop.

**Comment by shivdhar** [comment]
+1, it would be very useful for deep learning use cases as well to see how much CPU _and_ GPU the process is taking. Right now, I start htop and `watch nvidia-smi` separately in different terminals and have to switch between them.

As an aside, thanks for this wonderful tool!
