### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by Jollyrgr3** [hishamhm/htop#465]
Reporting bug just to help.

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x40959f]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f529ed81150]
htop(main+0x81d)[0x40596d]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f529ed6c76d]
htop[0x407a15]
Aborted (core dumped)

**Comment by kaefer** [comment]
This is an old version. Please consider updating to the latest version of htop (either packaged by your system or fetching/building master via git).

**Comment by hishamhm** [comment]
Thank you for the initiative @Jollyrgr3! It's best to follow @kaefer's advice and upgrade.
