### ISSUE TITLE
Filter(F4) Bug

### ISSUE THREAD

**Issue by sursir** [hishamhm/htop#467]
if filter result is blank, and click the scrren will caused the program crash.
backtrace below:
> [root@jstub2i7uf69ay log]# htop

> htop
1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407d3f]
/lib64/libc.so.6[0x35df6326a0]
htop(main+0x884)[0x409cd4]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x35df61ed5d]
htop[0x404f89]
Aborted

**Comment by narutoxboy** [comment]
Please update to lasted version 2.0.1 and try again

**Comment by hishamhm** [comment]
Confirmed as fixed.
