### ISSUE TITLE
Problem about RAM between htop vs top

### ISSUE THREAD

**Issue by narutoxboy** [hishamhm/htop#469]
Hello every body
i'm install htop 2.01 on system centos 6.7 but ram usage diffrent between htop vs top and command free -m,  top same same free -m, but htop is diffrent
I had previously installed version 1.0.3 and it's also different ram usage vs top
i don't know about it, please explain it for me.
Thank you
Picture demo 
http://i.imgur.com/WFI8SM4.png
http://i.imgur.com/cRxgibS.png

**Comment by hishamhm** [comment]
Hi!

Calculating from the numbers in your `top` screenshot:

```
>>> (10259084 - 222352 - 8701664) / 1024.0 / 1024.0
1.2732200622558594
```

See also the second question in the FAQ: 

http://hisham.hm/htop/index.php?page=faq

Hope this explains!

**Comment by narutoxboy** [comment]
Thank you :D, i know it, top show used memory by sum buffer and cached.
