### ISSUE TITLE
htop crashes on OSX 10.11.4

### ISSUE THREAD

**Issue by cappetta** [hishamhm/htop#470]
Changing the metering display from text to bars crashes the htop application when selecting 'bar' for CPUs or Memory.

**Comment by Explorer09** [comment]
What is your htop version?
Could you reproduce the error on the latest version?

**Comment by cappetta** [comment]
Hey,

htop --version
htop 0.8.2.8 - (C) 2004-2008 Hisham Muhammad.
Released under the GNU GPL.


Yes I was able to reproduce at that time but checking it now and I'm seeing
htop function as expected.  Going to try and reproduce it again but all 3
bar meters are working as expected right now.  Maybe it was fixed when I
rebooted?  Not sure -- will check over the next few days.

**Comment by Explorer09** [comment]
This is @cappetta's mail reply, in case that GitHub doesn't show it properly:

> Hey,
> 
> htop --version
> htop 0.8.2.8 - (C) 2004-2008 Hisham Muhammad.
> Released under the GNU GPL.
> 
> Yes I was able to reproduce at that time but checking it now and I'm seeing
> htop function as expected. Going to try and reproduce it again but all 3
> bar meters are working as expected right now. Maybe it was fixed when I
> rebooted? Not sure -- will check over the next few days.

Ok. So it's an unsupported fork. Please use the latest version.

**Comment by hishamhm** [comment]
Yes, please install htop 2.0.1! It's available in the usual channels, such as Homebrew! Thanks!
