### ISSUE TITLE
Showing an error message if problematic values for arguments are passed

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#477]
I'm using htop 2.0.1 and for example if I'm passing a value lower than 1 to -p htop does not find any processes (as processes with a PID lower than 0 does not exist). Another example is if I'm passing a value lower than 1 to -d which seems to result to imply the value 1 then. Maybe htop should show an error message and abort if the user passed invalid values for arguments. Alternatively htop could show just a warning and continue.

**Comment by Explorer09** [comment]
Duplicate of #418. I don't know how to repoen the old issue.

**Comment by hishamhm** [comment]
Well, if you ask to see only PID 10 and there's no process with PID 10, it accepts and shows nothing. If you ask to see PID -2 and there's no process with PID -2, it accepts and shows nothing too. It looks consistent to me. It's not htop's task to teach the user about the valid range of PIDs.

Plus, who knows if in the future some crazy OS that htop comes to support accepts negative PIDs? :)

**Comment by Sworddragon** [comment]
And what is with -d?

**Comment by Explorer09** [comment]
@hishamhm 
No, negative PIDs will be never supported in POSIX world. It will conflict with specification of the [kill(2) system call](http://pubs.opengroup.org/onlinepubs/009695399/functions/kill.html). Specifically, negative PID in kill(2) will kill a process _group_ of that ID (removing the negative sign).

**Comment by Explorer09** [comment]
@Sworddragon
It's rather a documentation error that didn't mention the minimum or maximum allowed value of -d option. I think the current behavior (pass silently with the -d value clamped or rounded) is fine.
