### ISSUE TITLE
Pressing "Page Down" hides all entries except the last

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#480]
I'm using htop 2.0.1 and after upgrading from version 1.0.3 I'm noticing that pressing "Page Down" in any menu that supports it (like the process list) the selection moves succesfully to the last entry but instead of showing the remaining entries above it until there is no space they are directly moved "offscreen" and thus hidden.

**Comment by hishamhm** [comment]
Fixed, thanks for the push! This always annoyed me slightly but not enough to do anything about it.
