### ISSUE TITLE
Making memory formatting more consistent

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#481]
I'm using htop 2.0.1 and noticed that the meters (like the memory and swap meter) got a new formatting for the units. I'm not sure but it looks as it now uses always a maximum of 3 digits (with eventually a comma somewhere between them like 1.03G) before changing to the next unit while beginning with the unit K. The memory values in the process list instead seem to use up to 4 digits (like 2863M) while beginning with Bytes (no unit) (and if I'm not wrong some columns are beginning with kilobytes while not showing the unit). Both behaviors are different from what the meters have shown in htop 1.0.3 as for example 5 digit values were possible (like 14382M).

Maybe this could be made more consistent across all entries that show such memory values:
- The current meters are formatting fast to the next unit which enhances the readability at the cost of a bit visual precision (only showing one-tenth of the current unit - for example you see every 10 MiB). That it begins with the unit K looks in my opinion a bit ugly (like 0K) but maybe this can be changed to begin with Bytes too.
- The current memory columns in the process list have in my opinion a bit worse readability for example on showing many values like 2864M compared to many values as they could be like 2.80G. But they have a higher precision in showing values (one-hundreth compared if the unit would have been bumped up - for example you see every MiB).

I have no strong opinion which variant should be used but I think they should be the same across all memory entries instead of having 2 (or even 3) different ones.

**Comment by Explorer09** [comment]
1. Memory unit in bytes is not applicable. Most OSes track memory usage in pages, and a page is usually a multiple of kilobytes.
2. The memory column in the process list is an artifact of the old `top` program. That is, the "K" letter is always omitted, and it will display 4 digits when it's possible in the 5 character limit. Think of it as not a bug, but a feature. :)

**Comment by mecjuszfufecjusz** [comment]
On the other hand it could be nice to have an option to revert to old memory meter units (Ms instead of Gs) included in htop setup screen. I liked megabytes more, it’s just one–two characters, but made me somehow feel more informed.

**Comment by Explorer09** [comment]
@mecjuszfufecjusz 
You have to tell us your use case of why you must use megabyte unit on memory meters. Here's a catch: some systems (a large server or a VM on a cloud) could have terabytes of memory, and when you represent that in megabytes it could be a unreadable large number. If you want a setup option that fixed the unit to megabytes, then what about the option to represent in GiBs? Or KiBs?
Would you explain?

**Comment by Sworddragon** [comment]
He could also word his suggestion that increasing the unit should only happen on reaching the fifth digit left of the comma for higher precision. Better would be possibly an option for custom formatting for related groups to fit any needs.

**Comment by mecjuszfufecjusz** [comment]
Totally what I would love to see implemented.

**Comment by Explorer09** [comment]
@Sworddragon @mecjuszfufecjusz
I know what it takes to implement this. Actually it all belongs to `Meter_humanUnit()` function in Meter.c source code. But I think a custom format to specify a precision would be an overkill for a small process viewer like this.
Maybe you could look in the source code and tweak it by yourself?

**Comment by hishamhm** [comment]
The design of columns is derived from `top` indeed, but the choice to make the meters more readable and the columns more precise was deliberate. They deal with different granularities. The meters are an overview of the system (coarser grain), where are processes often need to be analyzed in more detail (finer grain). They are different because I consider their use-cases to be different things.

It's all a matter of opinion, of course, and feedback is always welcome, but as the developer I take the responsibility for the design.
