### ISSUE TITLE
Sudden Death (first time)

### ISSUE THREAD

**Issue by beeva-manueldepaz** [hishamhm/htop#484]
htop 0.8.2.8 aborted. Please report bug at http://htop.sf.net
0   htop                                0x0000000105dd5a9f CRT_handleSIGSEGV + 30
1   libsystem_platform.dylib            0x00007fff8ea6952a _sigtramp + 26
2   libncurses.5.4.dylib                0x00007fff91d24add mvcur + 1747
3   htop                                0x0000000105dd787f Header_draw + 225
4   htop                                0x0000000105dd812c main + 1940
5   libdyld.dylib                       0x00007fff96da55ad start + 1

MacOs Pro Retina -> iTerm -> Developing with Node.js

**Comment by kaefer** [comment]
This is a very old and unofficial fork from htop. Please consider updating to the most recent version (2.0.1) either by compiling from sources or using homebrew.

**Comment by beeva-manueldepaz** [comment]
👍  Thanks & fixed.

1. removed with: [(http://unix.stackexchange.com/a/98262](http://unix.stackexchange.com/a/98262)
2. Clean links: $ htop-osx
3. Installed with: brew install htop
