### ISSUE TITLE
htop does not update process command line

### ISSUE THREAD

**Issue by mcr** [hishamhm/htop#489]
I noticed this with Debian jessie htop 1.0, so installed from source code to see what 2.0.1 does.
htop will only update the process name when it first sees the process (either when process starts, or when htop starts).  It does not catch updates to $0/setproctitle that the process might do.  
Updating the process title to indicate progress for long-lived processes that process many files is a really useful thing. ($0 in perl,ruby, setproctitle(3) in C. Sadly not part of glibc)
I realize that this might need a lot more scanning of /proc to pick these changes up. 
If there is an option to do this already I missed it.

**Comment by Explorer09** [comment]
The first thing, setproctitle(3) is probably not a standard call. My Google search result says it's in [Freebsd](https://www.freebsd.org/cgi/man.cgi?query=setproctitle&sektion=3), [PHP](http://php.net/manual/en/function.setproctitle.php) and probably a [Python module](https://pypi.python.org/pypi/setproctitle). For Linux, it [looks like it's not available](https://lwn.net/Articles/462095/) yet.

Can you provide a test case (test code is better) that changes the process title in Linux/FreeBSD/whatever-OS-you-have, so that we can test and see what idea it's like? Otherwise I don't know what's the advantage or use case to support that in htop.

**Comment by hishamhm** [comment]
> If there is an option to do this already I missed it.

Setup → Display Options → [x] Update process names on every refresh

:)

**Comment by mcr** [comment]
thanks for the reply, see inline.

Kang-Che Sung (宋岡哲) <notifications@github.com> wrote:
    > The first thing, setproctitle(3) is probably not a standard call. My Google
    > search result says it's in Freebsd, PHP and probably a Python module. For
    > Linux, it looks like it's not available yet.

It's not POSIX, true.  Why glibc omits it has always been a mystery to me.
sendmail has shipped with an implementation since 1988 or so...
Implementations usually just frob argv[0] a bunch.

    > Can you provide a test case (test code is better) that changes the process
    > title in Linux/FreeBSD/whatever-OS-you-have, so that we can test and see what
    > idea it's like? Otherwise I don't know what's the advantage or use case

#!/usr/bin/perl

my $num = 1;
while(1) {
         my $line = sprintf("process %d line", $num);
         $0 = $line;
         $num++;
         sleep(5);
}

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by mcr** [comment]
Hisham Muhammad <notifications@github.com> wrote:
    > Setup → Display Options → [x] Update process names on every refresh

Can I set that from command line?


--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by etosan** [comment]
When 

Setup → Display Options → [x] Update process names on every refresh

is enabled, it works 100%, at least on FreeBSD and Linux, as I am heavy setproctitle() user on both.

If you want to transfer settings among multiple machines (of same OS) I suggest configuring htop on one box, and distribute it's source:~/.config/htop/htoprc config either into target:~/.config/htop/htoprc or target:/etc/htoprc locations. Cross OS might be problematic, if you have non-platform columns, I think columns IDs might clash. So keep default/static config for each OS kind separate (it doesn't make sense with custom columns anyway).
