### ISSUE TITLE
Functions bar not restored when deleting a meter in moving

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#498]
In the meters panel in the Setup screen, when deleting a meter in the moving state, the functions bar is not restored to a non-moving bar.

Tested on htop 2.0.0 and also current master branch (specifically, on commit 645057d81aa619f4f9704cd221e63b357ac7f749).

Steps to reproduce the bug:
1. In htop, go to Setup (F2).
2. Press Right to select a meter on a column.
3. Press Enter to make the meter in the moving state (with the '↕' mark).
4. Press Delete.
5. See the functions bar still remain in the moving state, with "Up", "Down", "Left", "Right" labels. It should  be restored to the non-moving state, with "[Enter]Move" instead. In addition, mouse actions on the bar goes weird, too (specifically clicking Up changes the meter type/style, clicking Down sets another meter to moving state, and so on).

**Comment by hishamhm** [comment]
Thank you for the detailed report! Fixed.
