### ISSUE TITLE
Session ID column name should be "SID" or "SESS", not "SESN"

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#502]
Session ID column name should be "SID" or "SESS", not "SESN".
Because:
1. People use the SID abbreviation more often (see [setsid(2)](http://pubs.opengroup.org/onlinepubs/9699919799/functions/setsid.html) or [getsid(2)](http://pubs.opengroup.org/onlinepubs/9699919799/functions/getsid.html)).
2. Linux [top](http://man7.org/linux/man-pages/man1/top.1.html) uses SID as the abbreviation, and FreeBSD [ps](https://www.freebsd.org/cgi/man.cgi?ps%281%29) uses it, too. OS X [ps](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/ps.1.html) and OpenBSD [ps](http://man.openbsd.org/ps.1) seems to use the keyword SESS instead. Linux [ps](http://man7.org/linux/man-pages/man1/ps.1.html) accepts both keywords. (As an additional reference, Solaris [ps](https://docs.oracle.com/cd/E26502_01/html/E29030/ps-1.html) uses SID as keyword.)

Anyway, no one but htop would use SESN for this!

**Comment by hishamhm** [comment]
I'm pretty sure I didn't come up with it. For the first version of htop I copied the column names from the then-current version of top. I quickly tried to find references to it, but it seems to have mostly evaporated. [This one](http://stackoverflow.com/questions/3728151/what-is-the-best-way-to-close-this-group-of-processes) from 2010 seems to show it, and the "CMD" shows it's not htop (I didn't dig up old top sources to check).

Anyway, I'm fine with changing it to SID if it's more current usage.

**Comment by Explorer09** [comment]
Or perhaps you did make an error when copying the column names at the time. :)

This is how I can proof that: Here ([procps-3.0.5.tar.gz](http://procps.sourceforge.net/procps-3.0.5.tar.gz)) is the earliest procps package I can get, with the source files dated 2002-10-24. Within it, the `ps/ps.1` man page and `ps/output.c` source file state that they used "SESS" and "SID" for that (citing that BSD also uses them). And in it's `top.c` it uses `Command` (in Title Case) for the field. Your first htop release ([0.1](http://hisham.hm/htop/releases/0.1/)) was dated 2004-05-03, and it was not until [htop-0.3.1](http://hisham.hm/htop/releases/0.3.1/) (2004-05-29) did you introduce the session column. As I can't think of any place other than procps that you can have copied the column names from, the only conclusion I can make is that you might have made a mistake then.

Ok, now [it seems that only htop still keeps the "SESN" abbreviation](https://www.google.com.tw/search?q="SESN"+man+page) and is noted so in the man page. It is time to change it, isn't?

**Comment by hishamhm** [comment]
Sure, a PR is welcome!

**Comment by shevegen** [comment]
The beauty is that "SID" and "SESS" and "SESN" are all equally non-descriptive to people unless they know the full words anyway. :)

However had, "Session ID" is probably the best intuitive name, so SID would be more intuitive (and shorter!) than either SESS or SESN, in my opinion.

**Comment by hishamhm** [comment]
Closed via #593.
