### ISSUE TITLE
Pressing Ctrl+4 in htop 2.0.1 causes it to "Quit (core dumped)" and mess up the terminal (Linux; Mageia x86-64 v6)

### ISSUE THREAD

**Issue by shlomif** [hishamhm/htop#503]
Hi all,

pressing Ctrl+4 in htop inside konsole on Xfce on Mageia x86-64 v6 causes it to exit with "Quit (core dumped)" and mess up the terminal requiring a reset (Linux; Mageia x86-64 v6). I tried that in a new Unix user account and with an htop built from source using just './configure --prefix'. Pressing ctrl+3 or ctrl+5 has no apparent effect there.

**Comment by shlomif** [comment]
Update: I've now tested it in a virtual console and it happens there as well.

**Comment by hishamhm** [comment]
Confirmed! htop was not handling SIGQUIT. [More info here](http://stackoverflow.com/questions/19248556/why-does-pressing-ctrl-backslash-result-in-core-dump):

> CTRL-\ is the Linux key that generates the QUIT signal. Generally, that signal causes a program to terminate and dump core. This is a feature of UNIX and Linux, wholly unrelated to Python. (For example, try sleep 30 followed by CTRL-\.)
