### ISSUE TITLE
moving left/right quicker?

### ISSUE THREAD

**Issue by ryenus** [hishamhm/htop#508]
Is there any option to accelerate the horizontal scrolling? Or can we add?

It seems `htop` only moves by tab, or a tab size. this is ok for the first a few fields/columns, but very inefficient for the command line fields, especially for lengthy ones.

For example, java programs with lots of classpath entries and vm options, one must scroll to the far right end to be able to see the main class and it's arguments.

My 2 cents:
1. make the <kbd>left / right</kbd> arrow keys scroll by half screen/window width,
2. add another pair of key bindings that can move by 1 screen a time, like <kbd>ctrl + j / ctrl + k</kbd>, or something more appropriate.

Thanks

**Comment by ryenus** [comment]
e.g. https://gist.github.com/anonymous/8875cd4ca54b5ec71d80593aeade9e66/

which is **7k+** characters long.

**Comment by Explorer09** [comment]
If what you need is to solve your use case, then a faster scrolling is probably not what you need. Instead, I would personally suggest a dedicated key or window to show the full command line, wrapped into multiple lines automatically. Even for that, I doubt such a long command line will be common, so I don't think there is an urgency for such a feature.

As a workaround, if you are using Linux, you may parse the `/proc/${pid}/cmdline` file by yourself. Something like `tr '\0' '\n' < /proc/${pid}/cmdline`

**Comment by ryenus** [comment]
@Explorer09 thanks for the input!I like this part:
> a dedicated key or window to show the full command line, wrapped into multiple lines automatically.

But probably leaving `htop` itself might not be a good one, also `/proc/` in my understanding is Linux specific.

**Comment by hishamhm** [comment]
@ryenus the most logical option would be to use <kbd>Home</kbd> and <kbd>End</kbd> for that, but I'm already using these to go to the top and bottom of the list (which should have been <kbd>Ctrl</kbd>+<kbd>Home</kbd> and <kbd>Ctrl</kbd>+<kbd>End</kbd> instead, but many terminals don't support these key sequences). I'll give this some thought, thank you for the feedback!

**Comment by hishamhm** [comment]
I decided on <kbd>Ctrl</kbd>+<kbd>A</kbd> and <kbd>Ctrl</kbd>+<kbd>E</kbd>, with <kbd>^</kbd> and <kbd>$</kbd> as alternates. Thank you for the push, I've missed this feature myself in the past!

**Comment by ryenus** [comment]
@hishamhm thank you! thank you! really happy that you have taken my suggestion and landed a fix so quickly :D

Hopefully I'm not over demanding, is it also possible to have the feature @Explorer09 has mentioned?
> a dedicated key or window to show the full command line, wrapped into multiple lines automatically.

I think the upper <kbd>L</kbd> key (for **L**ong **L**ines), would be a great fit, which would behave very close to the lower <kbd>l</kbd> key, with a dedicated window, but showing the whole line wrapped instead.

**Comment by hishamhm** [comment]
No plans to add this, sorry.
