### ISSUE TITLE
Processes are not followed correctly

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#51]
I'm using the current git of htop and on pressing F5 to enable the tree view the focus stays always on the same line (which is mostly not the same process) instead of following the correct process.

**Comment by Arnaudv6** [comment]
F keybinding works for me (really have to press shift, Sworddragon)

But this behavior should be default.

**Comment by hishamhm** [comment]
Fixed in wip branch.

**Comment by Sworddragon** [comment]
On retesting this with htop 2.0.1 it seems that this behavior is not the default. But I think this problem should be solved in another way so I'm creating a new ticket for it.

**Comment by stuaxo** [comment]
Just hit this, it seems like it should be the default behaviour.

**Comment by stuaxo** [comment]
The other thing that's suboptimal here, is that even when you do press F to follow the followed process jumps up and down the screen, it would be better if it maintained its position and scrolling adjusted.

**Comment by Arnaudv6** [comment]
@Sworddragon care to link to your bug ?
