### ISSUE TITLE
Basename problem with some Google Chrome processes

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#513]
Some Google chrome processes may not show or highlight the correct "basename" in the Command field. Let me show an example with some screenshots:
![htop screen, without 'Show program path'](https://cloud.githubusercontent.com/assets/2487263/16168039/82656a10-3530-11e6-993e-580b352e49fa.png)
![htop screen, with 'Show program path'](https://cloud.githubusercontent.com/assets/2487263/16168045/8c2c6a3a-3530-11e6-8f06-ba34a5c8ce3a.png)

But in `top`, the names are shown correctly ("chrome"):
![top screen](https://cloud.githubusercontent.com/assets/2487263/16168059/bf58b86e-3530-11e6-8096-0f664e9d4380.png)

According to my research, this is not completely htop's fault. But Chrome sometime changes its `cmdline` entry so that its first part (the string before the first `\0` delimiter) concatenates file names and some of its options.

For reference, here's the `cmdline` entry for process 5443 as shown in the example:

![proc/5443/cmdline output](https://cloud.githubusercontent.com/assets/2487263/16168124/a60bd138-3531-11e6-9805-71e2ea441702.png)

    $ tr '\0' '\n' </proc/5443/cmdline | cat -n
         1	/opt/google/chrome/chrome --type=renderer --enable-features=IncidentReportingModuleLoadAnalysis<SafeBrowsingIncidentReportingServiceFeatures,IncidentReportingSuspiciousModuleReporting<SafeBrowsingIncidentReportingServiceFeatures,LinuxObsoleteSystemIsEndOfTheLine<LinuxObsoleteSystemIsEndOfTheLine,*UsePasswordSeparatedSigninFlow<PasswordSeparatedSigninFlow,WebFontsIntervention<WebFontsIntervention,*WebRTC-EnableWebRtcEcdsa<WebRTC-EnableWebRtcEcdsa,brotli-encoding<BrotliEncoding --disable-features=DocumentWriteEvaluator<DisallowFetchForDocWrittenScriptsInMainFrame,RenderingPipelineThrottling<RenderingPipelineThrottling --force-fieldtrials=AppBannerTriggering/Aggressive/AutofillProfileOrderByFrecency/Enabled/*BrotliEncoding/Enabled/CaptivePortalInterstitial/Enabled/*ChildAccountDetection/Disabled/*ClientSideDetectionModel/Model0/*DisallowFetchForDocWrittenScriptsInMainFrame/Default/*EnableMediaRouter/Disabled/*ExtensionActionRedesign/Enabled/*ExtensionDeveloperModeWarning/Default/*GFE/Default/*GoogleBrandedContextMenu/default/InstanceID/Enabled/LinuxObsoleteSystemIsEndOfTheLine/EndOfLine/MaterialDesignDownloads/Enabled/*OmniboxBundledExperimentV1/Unused_2/*OutOfProcessPac/Default/*PageRevisitInstrumentation/Default/PasswordBranding/Disabled/*PasswordGeneration/Disabled/*PasswordManagerSettingsMigration/Disable/PasswordSeparatedSigninFlow/Default/*QUIC/EnabledNoId/*RenderingPipelineThrottling/Disabled/ReportCertificateErrors/ShowAndPossiblySend/*ResourcePriorities/Launch50Permanent_11011_1_1_10/SHA1IdentityUIWarning/Enabled/SHA1ToolbarUIJanuary2016/Warning/SHA1ToolbarUIJanuary2017/Error/SSLCommonNameMismatchHandling/Control/*SafeBrowsingIncidentReportingService/Enabled/SafeBrowsingIncidentReportingServiceFeatures/WithSuspiciousModuleReporting/SafeBrowsingUnverifiedDownloads/DisableByParameterMostSbTypes2/*SafeBrowsingUpdateFrequency/Default/*SimpleCacheTrial/ExperimentYes2/*SyncHttpContentCompression/Enabled/*UMA-Population-Restrict/normal/*UMA-Uniformity-Trial-1-Percent/group_26/*UMA-Uniformity-Trial-10-Percent/group_07/*UMA-Uniformity-Trial-100-Percent/group_01/*UMA-Uniformity-Trial-20-Percent/group_03/*UMA-Uniformity-Trial-5-Percent/group_10/*UMA-Uniformity-Trial-50-Percent/default/*UseDelayAgnosticAEC/DefaultEnabled/*WebFontsIntervention/Enabled/*WebRTC

Because top display this one correctly, I think it's the job for htop to workaround these "weird cmdlines" and show the basenames correctly.

Google chrome version: 51.0.2704.103 (64-bit)
Ubuntu 14.04.4 LTS
Kernel version: 3.13.0-88-generic
`top -v` output: `procps-ng version 3.3.9`
htop version: custom built (commit abbe6c1417845d42fff688f76ed1bfa465703e3a) which is based upon htop 2.0.1

**Comment by hishamhm** [comment]
Nice catch, thanks for the research, it will be useful in case someone reports this in the future.

But I disagree and do not consider htop's job to workaround arbitrary binaries' tweaks. 

top is probably just showing the short name from /proc/PID/stat so it just doesn't bump into it.

You may want to post a bug report to Google Chrome instead, asking them to split their cmdline tokens correctly.
