### ISSUE TITLE
Single crash of 1.0.1 on RHEL6

### ISSUE THREAD

**Issue by severinraez** [hishamhm/htop#518]
On Red Hat Enterprise Linux Server release 6.7 (Santiago) I

* started htop
* filtered the processes by name (F4) and
* left htop alone for some minutes

Coming back to the terminal, I saw

> htop 1.0.1 aborting. Please report bug at http://htop.sf.net
> Backtrace: 
> htop[0x407d3f]
> /lib64/libc.so.6(+0x326a0)[0x7f6fbafe66a0]
> htop(main+0x884)[0x409cd4]
> /lib64/libc.so.6(__libc_start_main+0xfd)[0x7f6fbafd2d5d]
> htop[0x404f89]
> Aborted

Sadly (luckily) I cannot reproduce the problem.

I don't know whether the backtrace provides enough context to get to the bottom of this - I bet you do ;)

**Comment by hishamhm** [comment]
htop 1.0.1 is out of date! Please upgrade, there are many bugfixes.
