### ISSUE TITLE
error on search

### ISSUE THREAD

**Issue by softctrl** [hishamhm/htop#523]
Backtrace:
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x324f0)[0x7f3500eab4f0]
htop(main+0x8ae)[0x40c932]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f3500e97ead]
htop[0x4057e9]
Abortado

**Comment by hishamhm** [comment]
Hi! htop version?

**Comment by softctrl** [comment]
Hi, sorry, the htop version is 1.0.1
Linux SRVINTRACHAT 3.2.0-4-amd64 #1 SMP Debian 3.2.57-3 x86_64 GNU/Linux

**Comment by softctrl** [comment]
i was just trying to make a searching when this crash appear.

**Comment by kaefer** [comment]
Please consider updating to the most recent version (2.0.1) or building from source. 
Report again if the issue is still in place.

**Comment by softctrl** [comment]
thank, i will do this soon as i can
