### ISSUE TITLE
Implement "include" config directive

### ISSUE THREAD

**Issue by msva** [hishamhm/htop#530]
Hi there!
It'd be nice to have possibility to include custom configs.

It will be very useful to place include in dotfiles, that user transferring between, say, servers, to have as some "default" settings, and all changes made in local config would have priority over them.

**Comment by Explorer09** [comment]
What do you mean by "custom config" and "dotfiles"? You know the word "config" can mean different things. A VCS (version control system) config, a text editor config, a build time config (the config header for Autotools, that is, `config.h`), a runtime config (the file that will be installed in your home directory as `~/.config/htop/htoprc`). Which one?

**Comment by hishamhm** [comment]
Hi, thanks for the feedback!

> transferring between, say, servers, to have as some "default" settings, and all changes made in local config would have priority over them.

This use-case is already handled, by having a global /etc/htoprc and the local user-specific ~/.config/htoprc.

I have no plans to add "include" or to make other enhancements to the htoprc file format.
