### ISSUE TITLE
Real UTF-8 bargraphs for capable terminals

### ISSUE THREAD

**Issue by mbirth** [hishamhm/htop#536]
Now that the Braille graphs got included, I'd wish for the normal bargraphs to also be improved in that direction, e.g. instead of:

    [||||||||||||||||||       66%]

Show something like:

    ▕███████▌      66%▏

It would be awesome if you could use all available substeps, i.e. `▉▊▋▌▍▎▏` (U+2588 to  U+258f). Instead of the brackets, you could use U+2595 (`▕` = Right 1/8th block) and U+258f (`▏` = Left 1/8th block).

**Comment by Explorer09** [comment]
My humble and personal opinion says that it might not be a good idea. The main problem lies in coloring. With the limit of the terminal display, the coloring may only be applied on characters. (Sub-character coloring is technically possible but requires tricks and has many caveats, such as that at most 2 colors can be applied on a character, and that bold/lightened colors may not be used, and more.) I'm not bothered with 1/8th character precision for these reasons.

**Comment by mbirth** [comment]
As long as you change colors on full blocks only, there shouldn't be any problems.

**Comment by Explorer09** [comment]
My point is that it's really not worth it. And you DO need to consider the visual when the bar is 100% filled, or 98%. The eighth blocks you mentioned won't apply to this case.

**Comment by mbirth** [comment]
Well, then maybe forget the substeps but use the full block character.

**Comment by Explorer09** [comment]
I'm not bothered now. Since this is only a display style problem, it may be done as a customization, and yet I highly doubt Hisham will make this into the master branch.

**Comment by hishamhm** [comment]
@mbirth Thanks for the suggestion, but in the end things like this boil down to aesthetic preference. @Explorer09 already discussed the technical limitations, which are _really_ a showstopper — if I could produce the graph with 8x the precision while having all colors correct in the memory and CPU bars, I would do it. Since that is not possible, I don't plan to add UTF-8 block characters to the bar meters, sorry.
