### ISSUE TITLE
Feature Request: Peak Swap Usage Indicator

### ISSUE THREAD

**Issue by blag** [hishamhm/htop#539]
## Motivation

Hi, I'm using htop on an RPi, and I'm trying to compile some stuff that ends up taking a lot of memory, and eventually starts taking up a lot of swap space.

The compiler is erroring out, and I can't tell if it's because it runs out of memory (`ENOMEM`) or if I'm triggering a compiler bug. Since the RPi is a little underpowered, this process takes a long time, so I don't really want to babysit it for 1+ hours while it does its thing, but I want to know if I've allocated enough swap space for it or not.

I'm currently using htop to monitor the CPU/mem/swap usage on the RPi in a different tty, and I think it would be great to be able to add in "peak" usage indicators, kind of like VU meters:

![emss7](https://cloud.githubusercontent.com/assets/597113/17620142/7bb3c58a-6047-11e6-8ba3-cb65212a21fa.png)

^ Check out the "Peak" indicator

(shamelessly stolen from [http://www.webalice.it/g_pochini/ead/ea-emixer.html](http://www.webalice.it/g_pochini/ead/ea-emixer.html))

That way I can tell the maximum swap space used, and if I've allocated enough to it.

With normal VU meters the peak decays, but I don't think that should happen here. I think it should be a keybinding and/or menu option that resets the peak indicator in the usage meters.

Anyway, thanks for all of your work and for considering my idea. I'm not sure if I've explained it well enough, so please ask questions if you have them. :smile:

**Comment by Explorer09** [comment]
The problem with your peak indicator feature request is that in htop, our meters usually represent "stacked" values of different items. Take the memory meter for example, we stack at least {used, buffer, cache} together in one bar, and in this case a "peak" indicator makes little sense. (The "stacked" trait of the bar is also the reason we cannot plot MemAvailable in it, by the way.) The peak indicator, if we implement it, will be applicable to only a few meters (swap meter, battery meter). So I'm not sure that's really worth it.

Note: Meters such as Load Average, Task Counter, that do not have a maximum value, don't need to indicate the peak, the maximum of the bar, when plotted, will _be_ the peak value anyway.
