### ISSUE TITLE
Only require libtool 2.4.0

### ISSUE THREAD

**Issue by champtar** [hishamhm/htop#540]
Hi @hishamhm,

OpenWRT / LEDE only has libtool 2.4.0, and you recently introduced a check for 2.4.2 (https://github.com/hishamhm/htop/commit/6c1be632919baeef12143ad762b0fc0f7398f8b0)
How version 2.4.2 version was chosen? Is 2.4.0 enough?

Thanks

**Comment by champtar** [comment]
update to htop 2.0.2 in OpenWRT: https://github.com/openwrt/packages/pull/3066

**Comment by Explorer09** [comment]
I'm a bit confused. If you are building htop from a release tarball, then it shouldn't depend on the libtool installed on your host (this is how autotools work). So precisely what is the problem you are facing? Are you building from a checked-out tree from git?

**Comment by champtar** [comment]
Hi @Explorer09 
I'm cross-compiling htop from release tarball.
In OpenWRT/LEDE you have a special instruction "PKG_FIXUP:=autoreconf" to
rerun libtool to help cross-compilation to work
https://wiki.openwrt.org/doc/devel/packages#pkg_fixup

**Comment by Explorer09** [comment]
@champtar Specifically, which part is broken? Broken in a way that autoconf and libtool need to be rerun?

**Comment by hishamhm** [comment]
@champtar I honestly have no idea if 2.4.0 is enough; the number 2.4.2 was arbitrary because that's what I was running. If it works with no errors for you, I suppose it is. I'll change it. Thanks for reporting!
