### ISSUE TITLE
user limiting: choose user by typing

### ISSUE THREAD

**Issue by klaernie** [hishamhm/htop#541]
On many systems I have to limit the process list to specific users. Sadly the user list tends to be very long.

Could htop allow typing the start of the username? This would often limit the list to just two or three options, or might reduce the list to just one entry.

**Comment by ahlinc** [comment]
Yes, on main windows press 'u' and start typing the username and it automatically moves the focus on appropriate name and after that press Enter to apply the filter. It just moves the focus and doesn't reduces usernames list. Also see "htop --help" output, there is --user parameter that may be useful too.

**Comment by klaernie** [comment]
Okay, I never noticed that newer versions already do that. I am have to use SLES at work, where a older versions are shipped.

**Comment by hishamhm** [comment]
Thank you @ahlinc for posting the clarification :)
