### ISSUE TITLE
htop dumps error on quitting 

### ISSUE THREAD

**Issue by jitendranair** [hishamhm/htop#544]
Pressing "q" for quitting, dumps the following error  

htop 2.0.2 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop(CRT_handleSIGSEGV+0x2f)[0x4194ff]
/lib64/libc.so.6(+0x35670)[0x7f489a1bb670]
htop(String_freeArray+0xd)[0x41188d]
htop(Settings_delete+0x1e)[0x410e2e]
htop(main+0x54f)[0x40721f]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f489a1a7b15]
htop[0x4072f9]

LinuxOS:  Scientific Linux release 7.2 (Nitrogen)
htop version: htop 2.0.2 - (C) 2004-2016 htop 2.0.2 - (C) 2004-2016 Hisham MuhammadMuhammad

[htop.objdump.txt](https://github.com/hishamhm/htop/files/426565/htop.objdump.txt)

**Comment by hishamhm** [comment]
Hi, thank you for reporting! Was this an one-off thing or is it happening every time?

**Comment by jitendranair** [comment]
I did repeat the exercise about 4-5 times and yes it did throw the same error.

**Comment by hishamhm** [comment]
Do you have gcc and git available in your box? Could you download the code from git and make a debug build?

```bash
git clone https://github.com/hishamhm/htop
cd htop
./autogen.sh
./configure
make debug
valgrind ./htop 2> valgrind.out.txt
```

**Comment by jitendranair** [comment]
Hisham attaching  valgrind.out.txt  obtained from running the debug build .
[valgrind.out.txt](https://github.com/hishamhm/htop/files/434297/valgrind.out.txt)

**Comment by hishamhm** [comment]
@jitendranair Thank you. I did not find the precise cause, but I found something that might have caused memory corruption, and added an extra safeguard that should stop this crash. If you repeat the test pulling the latest commits from Git, I hope it should no longer crash.

**Comment by jitendranair** [comment]
Yes pulled in the fix and tested. No errors seen. Thanks @hishamhm .

**Comment by hishamhm** [comment]
Thanks for testing! :)
