### ISSUE TITLE
Monitor network traffic

### ISSUE THREAD

**Issue by der-stefan** [hishamhm/htop#545]
It would be a nice feature to show the current and accumulated network traffic in htop.

**Comment by Explorer09** [comment]
Monitoring network is probably out of the htop's scope. [There are other tools that can do the better job.](http://www.binarytides.com/linux-commands-monitor-network/) But, if what you really want is only a meter showing the Rx and Tx of network _as a total_ (i. e. all sockets/ports summed up and all network interfaces summed up excluding loopbacks), that's another matter. You better state explicitly what you want.

**Comment by Lokke** [comment]
a simple up- and downrate of traffic on network interfaces would be great

**Comment by cobrafast** [comment]
I just ported my old traffic meter I made years ago to htop 2. It probably still needs work, but it basically works.

#547

**Comment by der-stefan** [comment]
@Explorer09 I was thinking about a tool similar to "Mate system monitor":
[Screenshot 1](https://alexpl.fedorapeople.org/AppData/mate-system-monitor/screens/mate-system-monitor_01.png), [Screenshot 2](https://alexpl.fedorapeople.org/AppData/mate-system-monitor/screens/mate-system-monitor_02.png), [Screenshot 3](https://alexpl.fedorapeople.org/AppData/mate-system-monitor/screens/mate-system-monitor_03.png)
All in all, a tool for easy system administration. On the first tab "System" (no screenshot for this) you can easily find out about your system, kernel, installed RAM, processor and available disk space. There is no program for terminal-only systems with functions like that. Of course you can read out various /proc files, but you need to know about them.
Nonetheless, htop is a great tool right now.

**Comment by cobrafast** [comment]
>On the first tab "System" (no screenshot for this) you can easily find out about your system, kernel, installed RAM, processor and available disk space. There is no program for terminal-only systems with functions like that.

`inxi -F`
