### ISSUE TITLE
Number of processors only checked on launch

### ISSUE THREAD

**Issue by lgommans** [hishamhm/htop#548]
Many systems have the ability to dynamically take offline or put online CPU cores for power saving or other purposes. Mobile phones do this especially vigorously, for example my Galaxy Note 2 scales down from 4 CPUs to 1 immediately when the screen is turned off.

Any htop processes running while this occurs will not notice the change and still shows 4 CPU charts even though only 1 CPU core is online (or shows only 1 when 3 new ones came online). The number of CPUs is only determined on launch and never again.

I don't know how heavy it is to do a system call to get the info, but htop isn't the lightest program anyway (someone concerned with that would use good ol' top) and `time cat /proc/cpuinfo` is next to instantaneous. I think it might be a nice addition to update CPUs along with a normal update.

If it's too heavy (or just wasteful) to do every update, perhaps check every N updates (say, 15) and if a change is ever noticed, reduce N to every update or maybe every 2 updates.

**Comment by GiedriusS** [comment]
Seems like a duplicate of https://github.com/hishamhm/htop/issues/529.

**Comment by lgommans** [comment]
You're right. I searched for "processors" and "CPUs" but didn't find that thread (should have searched for "cores"). Thanks!
