### ISSUE TITLE
Doesn't show user-defined thread names

### ISSUE THREAD

**Issue by isj-privacore** [hishamhm/htop#554]
If a program sets a thread name with pthread_setname_np() then htop still shows program name for all threads. The thread name is stored in /proc/self/task/[tid]/comm and defaults to being the same as /proc/self/comm

htop 1.0.3
kernel 3.16.7

**Comment by hishamhm** [comment]
Hi! Please update your htop, the latest version shows custom thread names.

**Comment by hishamhm** [comment]
Also, make sure you go to the Setup screen (pressing F2), select the `Display Options` page, and then check the `[x] Display custom thread names` option.

**Comment by aronica** [comment]
User defined thread name in java is never shown, what's the matter?
