### ISSUE TITLE
htop 0.8.2.2 aborted while changing fan type

### ISSUE THREAD

**Issue by Flower7C3** [hishamhm/htop#557]
htop 0.8.2.2 aborted. Please report bug at http://htop.sf.net
0   htop                                0x0000000102d00a6b CRT_handleSIGSEGV + 30
1   libsystem_platform.dylib            0x00007fff92b4a52a _sigtramp + 26
2   ???                                 0x00007f9330411aa0 0x0 + 140270146493088
3   htop                                0x0000000102d028a9 Header_draw + 314
4   htop                                0x0000000102d06721 MetersPanel_EventHandler + 298
5   htop                                0x0000000102d0a822 ScreenManager_run + 524
6   htop                                0x0000000102d03d5a main + 5102
7   libdyld.dylib                       0x00007fff923355ad start + 1
8   ???                                 0x0000000000000001 0x0 + 1

**Comment by Explorer09** [comment]
htop 0.8.2.2 is an unsupported mac fork. Please upgrade to 2.0.
