### ISSUE TITLE
htop 1.0.3 - Debian Jessie - OS X - Not refreshing

### ISSUE THREAD

**Issue by dphilpot** [hishamhm/htop#559]
I've got quite an annoying issue with htop version 1.0.3 in combination with Debian Jessie and a remote OS X SSH Session.

If i make a remote ssh login from my OS X (El Capitan) to a Debian Jessie (Version 8) Server or Desktop Workstation and then open htop its not redrawing anything. If i move the courser around a bit, i get one refresh of the tool. If i press F5 i get a refresh every time i press it.

When i remote login from a Linux or a Windows PC there is no problem at all.
I've made a Test-Server for further investigation and as far as i can tell: The issue is only with htop version 1.0.3 all other Versions works fine.

Could you please take a look at this issue, since Debian has quite strict version policy so i'm not able to upgrade to a version 2.0 of htop.

**Comment by fasterit** [comment]
Add jessie-backports to /etc/apt/sources.list (or the sources.list.d/ directory) and you can install htop 2.0.2 from the backports archive.

**Comment by dietmar** [comment]
I have the same problem, but regardless of where my remote login comes from. My server is also Debian Jessie, running htop 1.0.3. I have logged in from another Debian machine, an Ubuntu machine and a Mac OSX machine, htop is always frozen. Pressing something like up/down or F5 causes a single refresh.
It's maybe also noteworthy that when htop is first started, the CPU bars are always at the same values (from some earlier time I guess), regardless of current CPU load. Only when I press arrow keys or something the bars reflect the current situation.

Any hints what might cause this behavior?

Also, it's not true that jessie-backports provides 2.0.2, according to https://packages.debian.org/jessie/htop stretch has 2.0.2, but jessie-backports does not offer a newer htop than regular jessie does (i.e., 1.0.3).

Thanks!

**Comment by fasterit** [comment]
Ginggs and DLange will do a backport to Jessie-backports. Should be there within a week.

**Comment by dietmar** [comment]
Great, thanks!
In the meantime I can confirm that htop 2.0.2 compiled from source works fine.

**Comment by hishamhm** [comment]
> In the meantime I can confirm that htop 2.0.2 compiled from source works fine.

Good to know it's not a current upstream issue! Also, great news about the backports. Closing the issue here.
