### ISSUE TITLE
Htop suddenly crashed with filter option activated

### ISSUE THREAD

**Issue by faintcoder** [hishamhm/htop#561]
I was using htop with a filter opion to see processes running and exiting, and suddenly crashed.
The message was:

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace: 
htop[0x407cfc]
/lib/x86_64-linux-gnu/libc.so.6(+0x321a0)[0x7f8be3cad1a0]
htop(main+0x8ae)[0x40c932]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f8be3c99ead]
htop[0x4057e9]
Aborted

**Comment by Explorer09** [comment]
It's hard to track the cause of your crash in such an old version. Please upgrade and see if that happens again.

**Comment by hishamhm** [comment]
@faintcoder There's an old known bug when filters produced empty lists, that has since been fixed. Please upgrade htop! :)
