### ISSUE TITLE
refresh frequency and ability to pause and resume?

### ISSUE THREAD

**Issue by ryenus** [hishamhm/htop#568]
title says it all, thanks.

**Comment by Explorer09** [comment]
Refresh frequency: see the `-d` option. (`-d --delay=DELAY            Set the delay between updates, in tenths of seconds`)
For the pause, no. Not available at the moment.

**Comment by hishamhm** [comment]
Archiving under the "feature request" label; thanks for the feedback!

**Comment by Evi1M4chine** [comment]
`top` has had the ability to set the refresh rate while the program was running since forever. It’s stunning that still does not exist in htop …

**Comment by Evi1M4chine** [comment]
I just looked into coding this up myself. And … holy shit, that language and UI library is *horribly, cumbersomly verbose*. How can anyone work with that? 90% is just boilerplate that could be abstracted away (assuming the language supports it).

No wonder this feature still isn’t built in. Even for an expert, it would take a day, just to code the basic functionality.

Sorry, I’m not gonna do it. The with stuff I prefer to use, I could probably code up the entirety of `htop` in the same amount of time.

**Comment by ericandrewlewis** [comment]
> I just looked into coding this up myself. And … holy shit, that language and UI library is horribly, cumbersomly verbose. How can anyone work with that? 90% is just boilerplate that could be abstracted away (assuming the language supports it).

This is intensely rude and unproductive.

I'd like to second that it would be useful to set the refresh rate after the program has started running, or perhaps read defaults like this from an rc file.

**Comment by foxxlpaul** [comment]
Ability to pause/resume htop would be a nice feature while troubleshooting a busy server.

**Comment by evandrocoan** [comment]
You can change the refresh rate by editing the file `~.config/htop/htoprc` and changing the line `delay=10` to whatever you like. Note, the value of 10 is 1 second. If the line `delay=10` is not present, just add it to the end of the file.

**Comment by alexander255** [comment]
@evandrocoan: Thanks! I changed it to 30 and now it's refresh rate matches `top` and it's not the most CPU-consuming task on the system anymore. :+1:

**Comment by delanym** [comment]
@hishamhm if this feature ever gets implemented, what status will you change it to?
