### ISSUE TITLE
Random crash on filter

### ISSUE THREAD

**Issue by NeilSmith100** [hishamhm/htop#572]
Nothing unusual - started htop, pressed F4 filter
Typed 'art' (no matching processes)
I think I pressed 'ESC' but maybe fat fingers.
Unable to repeat with steps a second time ...

Crash trace is :

```
https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/
 htop

htop 1.0.1 aborting. Please report bug at http://htop.sf.net
Backtrace:
htop[0x40948f]
/lib64/libc.so.6(+0x35670)[0x7f3ea3060670]
htop(main+0x812)[0x4059b2]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3ea304cb15]
htop[0x407919]
Aborted
```

**Comment by Explorer09** [comment]
Please upgrade to latest version.

**Comment by NeilSmith100** [comment]
Thanks, I'm using the Amazon AWS repos so there's no current update from 1.0.1

It's not a biggie, first and only time I've seen it -
I can happily wait for future repo upgrades.
