### ISSUE TITLE
Divide cores into more columns

### ISSUE THREAD

**Issue by ftfish** [hishamhm/htop#583]
Hi all,

Is there a way to divide the cpu usage meters into e.g. 8 columns instead of 4?
I'm asking because I recently got access to a machine with 72 physical cores and 144 with hyper-threading. I can therefore only see very few lines for processes. 
I know I can turn off the cpu meters altogether or half of them, but I don't want to.

Thanks in advance!

**Comment by hishamhm** [comment]
> Is there a way to divide the cpu usage meters into e.g. 8 columns instead of 4?

No, this feature is not available, sorry!

I may rework the CPU visualization in the future. Thanks for the feedback!

**Comment by yech1990** [comment]
hi @hishamhm 
How does the rework visualization going on?
