### ISSUE TITLE
Ordering bug in tree view

### ISSUE THREAD

**Issue by atlaua** [hishamhm/htop#587]
On my system, processes by other users aren't visible in htop due to SELinux restrictions. This includes the init process. Normally, this doesn't bother htop, but it seems to cause the following bug (which does not occur:

When a process has a lower PID than its parent, it is not included in the tree below its parent; instead, it is listed above the parent without any indentation. Here's a screenshot: 

![htop_tree_order_bug](https://cloud.githubusercontent.com/assets/864193/22174375/7ad2cab0-dfdd-11e6-8bfe-62d8ed7d6172.png)

This does not happen when run htop as root (thereby overriding the restrictions mentioned above); hence I assume this bug is causes by htop not being able to see the whole process tree.

**Comment by hishamhm** [comment]
Thanks for reporting!

I think I know what's going on (if I recall correctly, I think the tree-sorting _does_ assume that children have a higher PID than their parents — the code sorts by PID and constructs the tree from there).

Just out of curiosity, how did child processes end up with lower PIDs than their parents in your system? Was it a long uptime, then the PID number overflowed and rolled over? (Just asking in case there's an easy way to reproduce this.)

**Comment by atlaua** [comment]
On Tue, 24 Jan 2017 14:21:08 -0800
Hisham Muhammad <notifications@github.com> wrote:

> Thanks for reporting!
> 
> I think I know what's going on (if I recall correctly, I think the
> tree-sorting _does_ assume that children have a higher PID than their
> parents — the code sorts by PID and constructs the tree from there).
> 

This doesn't seem to match my observation that the tree is ordered
correctly when the init process (= antecessor of all other processes)
is visible to htop, though. (Apologies for just asking dumb questions
instead of having a look at the source; but I'm using my mobile right
now and it's really a pain to browse source code on this thing.)

> Just out of curiosity, how did child processes end up with lower PIDs
> than their parents in your system? Was it a long uptime, then the PID
> number overflowed and rolled over? (Just asking in case there's an
> easy way to reproduce this.)

Yes, I indeed observed this after my system hat overflowed the pid_max
limit (which was funnily enough not caused by long uptime, but by a
dumb shell script iterating over a huge directory tree and spawning
several processes for every single of the ~40000 files).

I have had several successes at reproducing the issue using the
following procedure:

(1) Run "while /bin/true; do /bin/true; done" in one bash instance to
    churn out lots and lots of processes (with pid_max being at its
    default of 32768, this script causes an overflow approx. every 20
    seconds on my system).

(2) Run "while true; do sleep 1; done" in a second shell. If you watch
    this in "htop -d1", you can see how the PIDs increase steadily.

(3) When the PIDs approach pid_max, start a process which spawns a lot
    of children (firefox works well, as does "for i in $(seq 1 100);
    do sleep 0.1; sleep 3600 & done").

Of course, frequent PID overflows combined with an invisible init
process truly are a negligible corner case if there's ever been one. :)
