### ISSUE TITLE
Bug with broken visualization of processes on macos

### ISSUE THREAD

**Issue by oriontvv** [hishamhm/htop#591]
I use htop 2.0.0 from homebrew on MacOS 10.10.5, reinstall doesn't solve the problem.
![screen shot 2017-01-27 at 15 22 54](https://cloud.githubusercontent.com/assets/13721490/22370839/a1ae80e0-e4a4-11e6-94b0-aa14d952a91b.png)
I can navigate cursor-line, but all processes are invisible

**Comment by Explorer09** [comment]
Can I say this bug is a duplicate to #410? There are other similar "process list empty" issues in the issues list, such as #573.

**Comment by oriontvv** [comment]
@Explorer09 Yes, Sorry for duplicate.
