### ISSUE TITLE
crash while config cpu's

### ISSUE THREAD

**Issue by Micha-Btz** [hishamhm/htop#598]
sysiphus:~$ htop
htop 2.0.2 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop(CRT_handleSIGSEGV+0x33)[0x55b0c916c0b3]
/lib/x86_64-linux-gnu/libc.so.6(+0x33040)[0x7f8d8bf36040]
htop(String_freeArray+0xd)[0x55b0c9163efd]
htop(Header_writeBackToSettings+0x4e)[0x55b0c915cbae]
htop(+0x19224)[0x55b0c9167224]
htop(+0xdd4f)[0x55b0c915bd4f]
htop(ScreenManager_run+0x1dd)[0x55b0c91624ed]
htop(main+0x4f4)[0x55b0c9159674]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f8d8bf232b1]
htop(_start+0x29)[0x55b0c91597e9]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!

Abgebrochen
[htop.objdump.txt](https://github.com/hishamhm/htop/files/772128/htop.objdump.txt)

program crashes while i configure the shown cpus and memoeryusage.

regards Micha

**Comment by jzyken** [comment]
I have the same trouble.
[htop.objdump.txt](https://github.com/hishamhm/htop/files/888087/htop.objdump.txt)

**Comment by hishamhm** [comment]
Fixed in 2.1.0! Thanks for reporting!
