### ISSUE TITLE
F10 doesn't work in my system

### ISSUE THREAD

**Issue by memnoth** [hishamhm/htop#600]
Htop : 2.0.2
OS : Elementary OS 0.4 Loki (based on Ubuntu 16.04.2)
Kernel : 4.4.0-62
Installed library before compiling is libncursesw5-dev

F1 ~ F9 keys work very well i expected, but F10 doesn't work. nothing happened.
Also all keys don't work after i pressed F10. i think it's keyboard freezing.
workaround for this issue is that i click the display of htop by mouse.
q works very well.

**Comment by hishamhm** [comment]
Hi! Thanks for reporting, but this is most certainly not an htop issue. We use the standard definition of F10 coming from ncurses.

Try a different terminal and see if the problem persists. You might want to report a bug for the Elementary OS terminal application.

**Comment by LWF666** [comment]
@hishamhm 
My system is ArchLinux X64,and my desktop is gnome,I found htop work on tildr and guake very well.
When htop work in gnome-terminal,F10 key and F8 key doesn't work.Is this gnome-terminal's problem?And can you give me some suggestions about this problem?Thanks!My English is bad.Sorry!
