### ISSUE TITLE
Del key for deleting a meter doesn't work on macOS X

### ISSUE THREAD

**Issue by sbibauw** [hishamhm/htop#607]
On macOS 10.12.3 (Sierra), on a MacBook Air (French/Belgian AZERTY keyboard if that makes any difference) using htop 2.0.2 on iTerm2, I can't delete any meter, because the `Del` key (when a meter is selected in F2-Setup) does not seem to have any effect. (Remember Macs have only the `Backspace ←` key.)

I have tried all the possible combinations (`Fn` + `Backspace` [usually emulates Delete on mac], `Ctrl` + `Backspace`, `Cmd` + `Backspace`...) with no luck.

This issue was already [mentioned in June 2016 on StackOverflow](https://superuser.com/questions/1088184/cant-delete-meters-on-htop-with-the-delete-key), without any successful solution.

**Comment by kapitainsky** [comment]
Indeed delete does not work but Fn + delete works for me with iTerm2.

**Comment by sbibauw** [comment]
`Fn`+`Delete/Backspace` doesn't work for me, probably because it is a French AZERTY keyboard...?

**Comment by kapitainsky** [comment]
Does Fn-delete behave like delete in e.g. text editor?

**Comment by sbibauw** [comment]
@kapitainsky Yes!

**Comment by kapitainsky** [comment]
so it looks like no problem with AZERTY french keyboard behaviour. I would suspect that you have some issue in iTerm2 with keys mapping. Try to go to Profile -> Edit Profiles -> Keys and try to load defaults. Or check carefully if there is no mapping for Fn+delete (Del->)

**Comment by sbibauw** [comment]
@kapitainsky Indeed! You are absolutely right. The default key mappings for the "Hotkey Window" were changing the behaviour of `Del→`. Thank you very much!

**Comment by Ruslang** [comment]
@sbibauw Use Fn+F9.
