### ISSUE TITLE
htop display is empty in Cygwin

### ISSUE THREAD

**Issue by mraper3** [hishamhm/htop#611]
I'm trying to use htop in Cygwin, and it seems it's not displaying any data, just empty bars and zeroed numbers.  Install worked fine.  Screenshot attached.  I'm guessing it's not grabbing the relevant data from the host system, and I'm also guessing that htop not originally being ported to Cygwin is the underlying issue.  I can do a little coding if needed.  Please let me know if you need more information.  Thanks!
![blank htop](https://cloud.githubusercontent.com/assets/5323781/25067770/2bf9e57c-2213-11e7-987a-d810af823df7.JPG)

**Comment by GUiHKX** [comment]
>htop has a lot of platform-specific code, so porting it is [not a matter of simply recompiling it](https://www.youtube.com/watch?v=g5GamptmWeA). The current version of htop does not support Cygwin. The latest [release](http://hisham.hm/htop/releases) version, [2.0.1](http://hisham.hm/htop/releases/2.0.1/), supports Linux, Mac OS X, FreeBSD and OpenBSD.

Source: https://stackoverflow.com/a/34137317

**Comment by mraper3** [comment]
Ah, I see.  Thanks for the information, then.  Closing this issue.
