### ISSUE TITLE
install & update 1 to 2

### ISSUE THREAD

**Issue by AhrimanSefid** [hishamhm/htop#629]
Hi All.
me install htop 1 in centos 6.9 but need help for update v 2.
plz help me.
thank you.

**Comment by Explorer09** [comment]
No one here has the direct access to your machine. If you can't explain the exact problem you are facing (error messages or getting lost on which step), then none can help you.

**Comment by hishamhm** [comment]
@AhrimanSefid please contact the CentOS community for instructions on installing updated packages. Thank you!
