### ISSUE TITLE
htop functions normally but crashes when I try to change display options

### ISSUE THREAD

**Issue by BlitzKraft** [hishamhm/htop#633]
I can use htop normally, except for entering setup. Even the sorting and tree view works fine. It crashes on quit. This is the backtrace on quit (when I hit `q`):
```
htop(CRT_handleSIGSEGV+0x2f)[0x41938f]
/lib64/libc.so.6(+0x343b0)[0x7f65166493b0]
htop(String_freeArray+0xd)[0x411c1d]
htop(Header_writeBackToSettings+0x4f)[0x40a8ef]
htop[0x414cb4] 
htop[0x409abf] 
htop(ScreenManager_run+0x1d2)[0x410332]
htop(main+0x487)[0x407577] 
/lib64/libc.so.6(__libc_start_main+0x114)[0x7f6516635954] 
htop(_start+0x29)[0x4076e9]
```
Something similar also happens when change anything in the display (by entering setup, F2). This is the backtrace:

```
htop(CRT_handleSIGSEGV+0x2f)[0x41938f] 
/lib64/libc.so.6(+0x343b0)[0x7f6e088233b0] 
htop(String_freeArray+0xd)[0x411c1d] 
htop(Settings_delete+0x30)[0x411210] 
htop(main+0x52a)[0x40761a] 
/lib64/libc.so.6(__libc_start_main+0x114)[0x7f6e0880f954] 
htop(_start+0x29)[0x4076e9]
```

From that, it appears the both have a common cause. Here is the zip of the objdump:
[htop.objdump.zip](https://github.com/hishamhm/htop/files/1050044/htop.objdump.zip)

EDIT: Removed trailing spaces in the backtrace.

**Comment by hishamhm** [comment]
Fixed in 2.1.0! Thanks for reporting!
