### ISSUE TITLE
Regression on "fixedgray": Gray on black bg not initialized properly.

### ISSUE THREAD

**Issue by Explorer09** [hishamhm/htop#635]
Regression on "fixedgray": Gray on black bg not initialized properly.

Regression caused by "fixedgray" branch (2d8dd0b29ef350731e2f1afa26af7b02f7649347 the attempt to fix #630)
![screenshot](https://user-images.githubusercontent.com/2487263/27009883-987edf7e-4ecb-11e7-8a02-5067c55fa118.png)

This is the screenshot tested on gnome-terminal on Ubuntu 14.04.

The cause: the curses COLORS variable is not checked when initializing colors,
and it lets `init_pair(ColorIndex(Magenta,Magenta), 8, -1);` to fail silently.

If COLORS==8, then `init_pair(ColorIndex(Magenta,Magenta), 8, -1);` would fail!
Should check if COLOR>8 before doing the "fixedgray" color initialization.

**Comment by Explorer09** [comment]
By the way, I personally don't like using the ColorIndex(Magenta,Magenta) to be used for the gray workaround. With `TERM=linux-16color`, we have additional color pair values, so it could be possible to use new indices such as index 64 for this.

```
if (COLORS > 8 && COLOR_PAIRS > 64) {
   //This is 16-color terminal. Use real gray (color 8) instead of bold black...
   init_pair(64, 8, -1);
}
```

No?

**Comment by hishamhm** [comment]
@Explorer09 Sorry for letting this slip unnoticed. I pushed a fix now.
