### ISSUE TITLE
building with netbsd-curses

### ISSUE THREAD

**Issue by CvH** [hishamhm/htop#643]
Trying to build htop with netbsd-curses but I get some build errors that I can't fix. https://pastebin.com/Q8iXDGgB
I am not too sure if this is a htop problem or a problem of my toolchain (or if I miss something).
```
/builddir/htop-89d1539/RichString.h:44:56: error: 'cchar_t {aka struct <anonymous>}' has no member named 'chars'
 #define RichString_getCharVal(this, i) ((this).chptr[i].chars[0] & 255)
```
Google points to a missing ncurses.h include but I had already tried a lot but nothing had fixed it.
The usual things like `-lncurses -lterminfo`, pointing to n/curses.h, manual include etc didn't helped.

Are there know problems with netbsd-curses or anything that I could try ?

**Comment by hishamhm** [comment]
Is netbsd-curses based on a different codebase than ncurses? htop does assume some ncurses-specific extensions.

**Comment by CvH** [comment]
`is close to being a 100% feature-complete drop-in replacement for ncurses`
it is more or less the successor of ncurses [(why a new curses was needed)](https://github.com/sabotage-linux/netbsd-curses#table-1-comparison-between-ncurses-and-netbsd-curses) with drastically improvements™.
As no other curses lib is available at my toolchain I can't "just" switch to ncurses. 
We had no problems so far distribution wide with netbsd-curses besides unfortunately htop. 
Netbsd-curses is rather "new" so I am unsure if it is supported at htop at all.

**Comment by hishamhm** [comment]
@CvH This is the problem:

> the structures used differ. some programs access ncurses structure members directly, they must be patched to use a portable approach.

Patches to make it portable are welcome!

**Comment by CvH** [comment]
@hishamhm are there some commits where similar things was done? I am not that skilled in this stuff but with some example it should be doable for me

**Comment by hishamhm** [comment]
@CvH unfortunately not. But I believe all changes would be in `RichString.c`.

**Comment by CvH** [comment]
@hishamhm we didn't found the culprit but at least got it working with this [ugly workaround](https://github.com/LibreELEC/LibreELEC.tv/blob/fa8e02e75f0fd11f1a4fbba406941a88f8ff1e0e/packages/addons/addon-depends/system-tools-depends/htop/patches/htop-01_netbsd-curses_support.patch) - maybe it helps someone

**Comment by krytarowski** [comment]
netbsd-curses is the original BSD curses(3) still maintained - with ncurses compat when useful. ncurses is a reimplementation.
