### ISSUE TITLE
Misaligned PID column on DragonFly BSD

### ISSUE THREAD

**Issue by liweitianux** [hishamhm/htop#646]
Hi,

I just installed **htop** on **DragonFly BSD**.  It seems work well, except for the misalignment of the **PID** column.  Please see this screenshot:
![htop-dragonfly-pid-misaligned](https://user-images.githubusercontent.com/686169/27912256-bf5a8360-628e-11e7-9d77-660de2f96af5.png)

By default, DragonFly BSD allows PID up to **999999** to help SMP implementation and performance.

Cheers,
Aly

**Comment by hishamhm** [comment]
Merged, thank you @liweitianux for the report and @Explorer09 for the fix!
