### ISSUE TITLE
Readable Process Names (Auto-scroll?)

### ISSUE THREAD

**Issue by sughodke** [hishamhm/htop#650]
The pain point is as alexjurkiewicz highlights in https://github.com/hishamhm/htop/issues/233, the Process name field is not very helpful as is.  At a glance, I would prefer to see process name (and args), and not system paths.

**There are a couple of proposals here,**
- could we put ellipsis on the directory names after the first couple characters (e.g. from /Applications/Xcode/blah it could be /App../Xco../blah)
- alternatively, we could auto-scroll process names or simply be instead of showing the first-n characters show the last-n.  

I hope others would like these changes, I know I would.

```
$ htop --version
htop 2.0.2 - (C) 2004-2017 Hisham Muhammad
Released under the GNU GPL.
```

![screen shot 2017-07-11 at 9 02 11 am](https://user-images.githubusercontent.com/31588/28077824-ade6ddc2-6617-11e7-9eb5-881fb6e4e7d2.png)

As seen on my machine with "too much mostly-useless info".

---

> I'm using htop to watch a [OS X Application with deep-nested executable], or otherwise very long command names  (java procs in particular).
> -- alexjurkiewicz

**Comment by Explorer09** [comment]
Please me if the "Show program path" option (Setup -> Display options -> Show program path) is not enough for you, and why.

**Comment by sughodke** [comment]
Thanks @Explorer09! That is perfect.

Just for completeness, you can also update the htop rc-file with the following.
```
show_program_path=0
```
