### ISSUE TITLE
MacOS - VMWare Fusion processes not showing proper CPU usage

### ISSUE THREAD

**Issue by edrozenberg** [hishamhm/htop#653]
The CPU counters are showing the proper usage, but the process list doesn't show any entries using up this CPU - process list shows only very light usage. The process is VMWare Fusion.
![vmware fusion procs not showing cpu](https://user-images.githubusercontent.com/2648417/28295524-08ed4a28-6b16-11e7-84c8-2586504ea4d7.png)

**Comment by Explorer09** [comment]
Your stats on the right of the screenshot shows that user processes only occupies 2% of CPU time. And the 27% of CPU time is used by the kernel. Since your process list on htop only shows user processes, there's nothing wrong.

**Comment by edrozenberg** [comment]
You're totally right, I keep forgetting that I need to do "sudo htop" to see all processes! Thanks.
