### ISSUE TITLE
Macos process state undefined in 2.0.2

### ISSUE THREAD

**Issue by avindra** [hishamhm/htop#661]
```bash
$  htop --version
htop 2.0.2 - (C) 2004-2017 Hisham Muhammad

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

![image](https://user-images.githubusercontent.com/126848/28693366-3e5e9ade-72f2-11e7-8ac7-ff2d39ee9475.png)

Here, you can see the `S` column is showing `?` for all processes, instead of the actual state.

I should mention that I installed with the curses option mentioned here https://github.com/hishamhm/htop/issues/421#issuecomment-189045964

**Comment by hishamhm** [comment]
I think this may be a permissions problem. Some threading APIs (which htop uses to obtain process state) became unavailable for non-signed binaries.

**Comment by Explorer09** [comment]
May I suggest adding a warning screen if htop fails to get permission to read any column of the process list? This way it can be more user-friendly than just showing dummy entries like "?" or "no perm" (users won't be obvious what "no perm" means).

**Comment by hishamhm** [comment]
Thanks for the suggestion, but I'm not a fan of warning screens (neither appearing every time or the infamous `[x] Do not show this message again`), especially for an app like this.
