### ISSUE TITLE
Enhancing the memory meter

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#67]
I'm using the current git of htop and have thought a little about the memory meter:
- The amount of memory is the same as MemTotal from /proc/meminfo. In my case htop is showing me 16048 MiB while 16384 MiB are installed. Currently I'm assuming the missing 336 MiB are reserved by the BIOS + the kernel. Maybe htop is able to determine the physical installed memory and could replace the current value with it while showing the difference as "reserved" or with a similar name.
- The slab cache is counted towards "used". In my opinion the slab cache should get its own entry like "buffers" and "cache" as it is very similar to them (like "buffers" and "cache" it gets dropped if  the correct value is passed to /proc/sys/vm/drop_caches but interestingly it doesn't get much freed if the system runs out of physical memory (but I'm assuming that this is a bug and have opened a bug report for this: https://bugzilla.kernel.org/show_bug.cgi?id=74771 )) and not informative about the real used memory.

**Comment by MartinSavc** [comment]
What was the final decission on this issue?

Depending on the system, slab can grow to considerable size. I have 16Gb of memory, which doesn't get much use lately. When updating my system to Fedora 22, htop started showing 13Gb+ memory used, with system more or less idling. It seems the new kernel has started making more use of the available space, which in meminfo shows up as Slab, most of it as SReclaimable. HTop rather unforunately assigned this to used memory instead of cache (or maybe something more specific).

**Comment by hishamhm** [comment]
Hi, sorry about the long delay in answering this. I am reopening this and I will take a closer look at this issue of memory reporting.

**Comment by OmegaPhil** [comment]
This is not a 'wishlist' item, this is a bug - htop is misreporting a cache (reclaimable part of the kernel slab, SReclaimable) as part of actual used memory - see [the recent change to free for presumably the best example](https://gitlab.com/procps-ng/procps/commit/05d751c4f076a2f0118b914c5e51cfbb4762ad8e).

Sorry I wasn't aware this had been reported before (and even a pull request!), my original comments [here](https://github.com/hishamhm/htop/issues/242#issuecomment-158660553).

**Comment by OmegaPhil** [comment]
Is there anything I can do to get the fix (or similar) into mainline?

**Comment by IgnorantGuru** [comment]
OmegaPhil does meticulous work, just to recommend.  I would like to see this aspect of htop resolved as well - thanks for looking at it.
