### ISSUE TITLE
Network usage on available meters

### ISSUE THREAD

**Issue by pabloab** [hishamhm/htop#670]
Added to current available meters would be great to have network usage of each process. Even filter which process are listening and the port. Something like [nettop](https://github.com/Emanem/nettop) but inside the glorious `htop`:

![image](https://user-images.githubusercontent.com/657836/29483037-411ab99a-8474-11e7-901f-92a63abd5c40.png)

**Comment by hishamhm** [comment]
Request labeled and archived (this repo keeps open bugs only; feature requests are available via the Label view). Thank you for the feedback!
