### ISSUE TITLE
needs process name refreshed for PostgreSQL

### ISSUE THREAD

**Issue by hvisage** [hishamhm/htop#672]
Good day,

 PostgreSQL renames/changes it's process name/command/argument strings to indicate the current query running.

 HTOP doesn't refresh that, so you have a case where it shows an "idle" transaction doing high CPU, or an UPDATE doing nothing.

**Comment by hishamhm** [comment]
Press <kbd>F2</kbd> `Setup` -> `Display Options` -> `[x] Update process names on every refresh`

Enjoy!
