### ISSUE TITLE
lsof exit code not detected correctly

### ISSUE THREAD

**Issue by wasamasa** [hishamhm/htop#675]
I've tried using `l` and `s` on a box with neither `lsof` nor `strace` installed and noticed that while I got an error message for `s`, there was none for `l`.  This seems to be the fault of how both programs are spawned, for `lsof` a pipe is opened with `popen(3)` and a return value of null is interpreted as exit code 127.  This is wrong as `popen(3)` starts a shell and failure other than memory allocation is related to whether the shell could be opened.  Furthermore the return value of `pclose(3)` is interpreted as the `lsof` exit code which is wrong as well, according to `wait(3)` it contains far more information than that to allow telling whether the process did exit normally or by a signal, you'll have to use the `WIFEXITED` and `WEXITSTATUS` macros to extract it from that value.  I've created a small example demonstrating this in a hopefully portable way:

```c
#include <stdio.h>
#include <sys/wait.h>

int main() {
   FILE* fd = popen("not-lsof", "r");
   int ret, exit_code;

   if (fd) {
      printf("Success!\n");
      ret = pclose(fd);
      if (ret < 0) {
         printf("Failed closing fd\n");
      } else {
         if (WIFEXITED(ret)) {
            printf("Process did exit with %d\n", WEXITSTATUS(ret));
         } else {
            printf("Process terminated by a signal\n");
         }
      }
   } else {
      printf("Fail!\n");
   }

   return 0;
}
```

I'm not sure how to rework `OpenFilesScreen.c` so that it takes the more precise error handling into account and would be happy about any suggestions.

**Comment by shevegen** [comment]
Since about 2 weeks have passed, I guess others are also stumped. :-)

**Comment by wasamasa** [comment]
No, the simpler explanation is that they don't care.  This bug is fairly low-priority because how often does someone without lsof try using lsof in htop?  I merely invested the effort because I finally figured out why exactly it happens and like having a project use more correct C code, no matter how trivial the matter is.

**Comment by hishamhm** [comment]
Lately, I haven't been able to devote a lot of time to htop, so yeah, I haven't been able to go through this in the last 2 weeks but it doesn't mean that I don't care. :) I will return eventually to this when I go through the next round of htop hacking, thanks @wasamasa for reporting and sharing code!

**Comment by timofonic** [comment]
@hishamhm Have you considered to accept more contributors to the project and form a team? htop is very used, maybe even people from Red Hat and SuSE can help on it.
