### ISSUE TITLE
Add reptyr support

### ISSUE THREAD

**Issue by timofonic** [hishamhm/htop#680]
Hello.

What about adding @nelhage's [reptyr](https://github.com/nelhage/reptyr/issues) support so processes can be "moved" easily within the TUI?

Kind regards.

**Comment by Explorer09** [comment]
What code changes are needed in order for htop to support reptyr? From reptyr's read me, I don't understand if there is need to change htop code.

**Comment by hishamhm** [comment]
Thank you for making a feature request! The issues page keeps open bugs only; feature requests are filed in the [`feature requests`](https://github.com/hishamhm/htop/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22feature+request%22+) label. More info [here](https://github.com/hishamhm/htop/blob/master/CONTRIBUTING.md#feature-requests)! Thank you for the feedback!
