### ISSUE TITLE
Feature request: Highlight self (htop process)

### ISSUE THREAD

**Issue by Ape** [hishamhm/htop#681]
I think it would be useful to highlight the current htop process in the process list. I am thinking about using some special color for this. Additionally or alternatively, there could be a hotkey that goes to (i.e. selects) the htop process on the list.

My reasoning is that I might be in a terminal or shell with multiple child processes where htop is one of the children. I like using the tree view where processes are grouped. If I could quickly find the current htop process on the list, I could also locate other processes in my current session. Sometimes the process list is quite big and I find myself using the search to find either htop or one of the children.

**Comment by tedzhu** [comment]
Just saw this after opening #722, might be related.

**Comment by hishamhm** [comment]
Thank you for making a feature request! The issues page keeps open bugs only; feature requests are filed in the [`feature requests`](https://github.com/hishamhm/htop/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22feature+request%22+) label. More info [here](https://github.com/hishamhm/htop/blob/master/CONTRIBUTING.md#feature-requests)! Thank you for the feedback!
