### ISSUE TITLE
Error in memory usage graphic

### ISSUE THREAD

**Issue by cybernova** [hishamhm/htop#684]
![screenshot_2017-09-29_19-47-28](https://user-images.githubusercontent.com/5947674/31029891-ae1e73ec-a553-11e7-909e-73062b36d492.png)

In version 2.0.2
Linux Debian

**Comment by wangqr** [comment]
The green part of the memory bar is 'used memory', which is 2.04G in the picture. Blue part is buffer and orange part is cache. These 2 parts are not counted as used memory.

**Comment by cybernova** [comment]
Ok, understood, cool.
But why the used memory / total memory is orange colored? Seems like a "warning" to me... it should be gray, for a better reading of the system's state.

**Comment by wangqr** [comment]
The orange color is just indicating it is cache. So for example, if you used 100% of a CPU core in user mode, then the '100.0%' in the CPU bar will be green.

**Comment by cybernova** [comment]
I was talking about the 2.04G/11.2G write that is orange colored, I've understood the orange vertical bar ( | ) is cache.

**Comment by wangqr** [comment]
The text covered underlying vertical bars, but kept the color of the original bars.

**Comment by cybernova** [comment]
Ok, now it's all clear, thanks for the infos.
