### ISSUE TITLE
Feature Request: Specify different config file on command line

### ISSUE THREAD

**Issue by ses-rwsmith** [hishamhm/htop#685]
I use htop with tmux to monitor 20 - 30 servers at once on one screen. Even with really small font the display is crowded with into that I do not need. So that I do not have to create a new user to just have use of a different config (fewer columns) it would be nice to specify which config to use. This way when I ssh to server I have the all the columns and when used with tmux in tiny windows I have fewer columns.

**Comment by hishamhm** [comment]
Hi!

You can use the HTOPRC environment variable. You can even do something like:

```
export HTOPRC=$HOME/.config/htop/htoprc-$HOST
```

in your shell profile.
