### ISSUE TITLE
Feature suggestion: 8 column cpu meters

### ISSUE THREAD

**Issue by edrozenberg** [hishamhm/htop#687]
With the large number of cores in servers (for ex. 48 cores/96 hyperthreads), and the limited vertical space on laptops, it would be very useful to have a cpu meters option that uses 8 columns (currently 4 columns is max).

Even on 80 column xterm/terminals there would still be enough room to show a little bit of a bar meter for each core, and the cpu percentage is great info even if the bar is small. On laptops it's easy for the user to just make the terminal window wider if they want to see more of each cpu bar (but stretching the lcd display to make it taller is hard :).

**Comment by Explorer09** [comment]
I would consider this a duplicate of #628.

**Comment by edrozenberg** [comment]
It's a duplicate thanks.
