### ISSUE TITLE
display nothing on mac os 10.13 lastest version

### ISSUE THREAD

**Issue by cxwx** [hishamhm/htop#688]
display nothing.

**Comment by Explorer09** [comment]
We have a lot of "displays nothing" issue reports here. Can you give a more detailed explanation of your issue?

**Comment by edrozenberg** [comment]
It's working for me on 10.13.1 Beta (17B25c).

I am seeing a delay of 3-4 seconds when starting htop as a regular user. This is new. Interestingly ```sudo htop``` launches htop instantly.

**Comment by hishamhm** [comment]
@edrozenberg That is interesting. I may get access to some Mac boxes this week, but I don't know if they're running the latest version. I'll try to diagnose this!

**Comment by edrozenberg** [comment]
On a another Mac, High Sierra 10.13 (17A405), seeing  about a 2 second delay for regular user htop.

On a Mac with Sierra 10.12.6 (16G1023), seeing a 1 second delay for regular user compared to sudo.

So it seems there is always some delay running htop as a regular user, and maybe the delay has gotten bigger on High Sierra for some reason.

In any case htop still works!

**Comment by dylib** [comment]
**htop** successfully builds on 10.13 from the git repo with autotools installed, however, when executing the htop command it's definitely not displaying correctly:
![broken_htop_10 13 0](https://user-images.githubusercontent.com/17288131/32131065-eca4ca8c-bb59-11e7-9a6c-4d6d510e5cf6.png)
_**Terminal.app:**_
```
$ ./autogen.sh && ./configure && make
$ sudo make install
$ htop
```

**Comment by wataash** [comment]
@edrozenberg 
How about after pressing "t" key? I guess htop will get frozen.
And I think the issue can be reproduced by setting `tree_view=1` in `~/.config/htop/htoprc`.

**Comment by bjorke** [comment]
I have release version 2.0.2 installed and compiled another from master, if you start the 2.0.2 version press "t" exit it and start the one from master it will run.
If you press "t" in the one compiled from master it will freeze, but if you halt it and run it again it still works i.e did not switch over to the tree view.

**Comment by edrozenberg** [comment]
@wataash problem confirmed running the latest. Pressing 't' freezes htop requiring CTRL-C. Changing config to ```tree_view=1``` prevents htop from starting - black screen.

```
/usr/local/Cellar/htop/HEAD-b7b66b7_1 (11 files, 185.5KB) *
  Built from source on 2018-01-06 at 09:24:04 with: --with-ncurses
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/htop.rb
```
