### ISSUE TITLE
htop-git vs. tmux 2.6 (crash on resize?)

### ISSUE THREAD

**Issue by mkoskar** [hishamhm/htop#691]
So this is related to <https://github.com/tmux/tmux/issues/1112>.

I have this test script:
```bash
#!/usr/bin/env bash

socket='test'
session='test'

tmux -vv -L "$socket" -f /dev/null new -d -s "$session" \
    \; setw remain-on-exit on \
    \; splitw -h htop

exec tmux -L "$socket" attach -t "=$session"
```
Running it, `htop` wont't start and `tmux` server will crash.
Now the latter has been resolved leaving me with dead `htop` in the right tmux pane.

It was noted in the issue linked above that (quoting @nicm):

> I suspect that htop is exiting, probably when tmux tries to resize it (2.5 would not resize when you attach, but 2.6 will)

Versions:
```
Linux mirci 4.13.4-1-ARCH #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017 x86_64 GNU/Linux
tmux 2.6 (will crash; fixed on master in d10def5b0b5a4d000b1a34efd32cc4a2613f66c7)
htop - master (e3f65c8ec2fe81c50514dcf21c335e5d39c1a223)
```

**Comment by mkoskar** [comment]
I should have added that this is the problem with git master version, `2.0.2` is not affected.

**Comment by hishamhm** [comment]
@mkoskar hi, could you test it with the latest master? thank you!

**Comment by mkoskar** [comment]
Seems fixed. Thanks! Closing...
