### ISSUE TITLE
Embeded views for iotop, iftop and sysdig

### ISSUE THREAD

**Issue by amosbird** [hishamhm/htop#697]
Hi, htop has a decent TUI for system monitoring. Is there a way to make htop an entrypoint for similar tools such as iotop, iftop and sysdig? I'm very pleased by the way lsof and strace work inside htop.

**Comment by hishamhm** [comment]
@amosbird htop already supports all columns displayed by iotop. I haven't checked iftop in detail yet, and sysdig has a very htop-influenced UI itself. I have toyed with the idea of making htop plugin-extensible but haven't gone that way yet. Thanks for the suggestion!

**Comment by amosbird** [comment]
@hishamhm Hi! Thanks for the support. 

> htop already supports all columns displayed by iotop. 

Hmm, i couldn't find it.

![img-2017-11-21-095545](https://user-images.githubusercontent.com/5085485/33050891-4484d8f4-cea2-11e7-827e-48f073675f93.png)
