### ISSUE TITLE
Configure/compiler warnings

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#70]
On the current git I'm seeing a few warnings on ./configure and make with Ubuntu 14.10 dev and the GCC 4.8.2:

	sworddragon@ubuntu:~/tmp/htop-master$ ./autogen.sh > /dev/null
	configure.ac:8: installing './compile'
	configure.ac:9: installing './config.guess'
	configure.ac:9: installing './config.sub'
	configure.ac:11: installing './install-sh'
	configure.ac:11: installing './missing'
	Makefile.am: installing './depcomp'
	sworddragon@ubuntu:~/tmp/htop-master$ ./configure > /dev/null
	/bin/bash: /home/sworddragon/missing: No such file or directory
	configure: WARNING: 'missing' script is too old or missing
	sworddragon@ubuntu:~/tmp/htop-master$ make > /dev/null
	/bin/bash: /home/sworddragon/missing: No such file or directory
	configure: WARNING: 'missing' script is too old or missing
	BatteryMeter.c: In function ‘procAcpiCheck’:
	BatteryMeter.c:140:12: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
	       fgets(line, sizeof line, file);
		    ^
	Process.c: In function ‘Process_getMaxPid’:
	Process.c:293:10: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
	    fscanf(file, "%32d", &maxPid);
		  ^
	ProcessList.c: In function ‘ProcessList_new’:
	ProcessList.c:217:12: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
	       fgets(buffer, 255, file);
		    ^
	ProcessList.c: In function ‘ProcessList_scan’:
	ProcessList.c:940:12: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
	       fgets(buffer, 255, file);
		    ^
	TraceScreen.c: In function ‘TraceScreen_run’:
	TraceScreen.c:96:12: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
	       write(fdpair[1], message, strlen(message));
		    ^
	UptimeMeter.c: In function ‘UptimeMeter_setValues’:
	UptimeMeter.c:27:13: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
	       fscanf(fd, "%64lf", &uptime);
		     ^

I think the script wants to access ./missing instead of ~/missing.

**Comment by hishamhm** [comment]
I could not reproduce the "missing" problem. Might be an issue with your version of autotools.
I pushed code to my work branch to silence these warnings. Thanks for the report!
