### ISSUE TITLE
RAMdisk not reflected in total memory usage

### ISSUE THREAD

**Issue by boogybren** [hishamhm/htop#703]
htop does not show memory reserved for a mounted RAMdisk.  Because the memory allocated to the RAMdisk is not available for the OS to use outside of writing to the file system, shouldn't it show up in htop as being allocated?

**Comment by boogybren** [comment]
In other words, if I’m using 30GB of RAMdisk, that 30GB does not show up in htop as being used.

**Comment by hishamhm** [comment]
> RAMdisk is not available for the OS to use outside of writing to the file system

That is incorrect. The OS can use "free space" in the tmpfs for disk cache (the area marked in yellow in htop)

> shouldn't it show up in htop as being allocated?

It shows as allocated when the tmpfs space is filled with files (then it's really not available for the OS to do anything else). In other words, if you fill your tmpfs it will appear as green. If it is empty, it will appear as black or yellow, depending whether the kernel is using the area for disk cache. Note also that the kernel may decide to swap out parts of the tmpfs, so there isn't really a fixed "reserved spece" for it in RAM.

Hope that clears things up!
