### ISSUE TITLE
Faster access that /proc with task-diag

### ISSUE THREAD

**Issue by shawnl** [hishamhm/htop#705]
The /proc interface on Linux is the main API that htop uses to get information. It requires at least three syscalls for each process. The CRIU people were working on a `/proc/task_diag` file that exports this information more performance.

https://criu.org/Task-diag

**Comment by hishamhm** [comment]
Nice, thanks for the link! But even if/when it gets accepted in mainline kernel it doesn't mean we can drop support for reading from /proc/PID as that is what's available on every existing Linux system out there. So, I think this can only be considered once task-diag gets merged into mainline.
