### ISSUE TITLE
Releases should have autoconf already run.

### ISSUE THREAD

**Issue by shawnl** [hishamhm/htop#706]
The releases should include manually packaged source tarballs that have had ./autogen.sh run already.

That way they can be built without autoconf.

**Comment by hishamhm** [comment]
They do. Releases are available at http://hisham.hm/htop

The "release" files at Github are automatically generated by Github and are not the official tarballs. Unfortunately there is no way to switch them off, as far as I know.

**Comment by shawnl** [comment]
Thanks
