### ISSUE TITLE
Libnl 3 not found

### ISSUE THREAD

**Issue by florian2833z** [hishamhm/htop#710]
I cant compile htop from git rep anymore, it says that libnl3 is not found although it is installed.
./configure: line 6504: syntax error near unexpected token `LIBNL3,'
./configure: line 6504: `   PKG_CHECK_MODULES(LIBNL3, libnl-3.0, , missing_libraries="$missing_libraries libnl-3")'

OS: Debian Stretch

**Comment by JDevlieghere** [comment]
I'm experiencing the exact same issue on macOS.

**Comment by andrestc** [comment]
I'm **not** being able to reproduce this. 

I'm able to configure htop with and without delay accounting support on debian stretch using the following minimal dockerfile:

```
FROM debian:stretch

RUN apt update && apt install dh-autoreconf pkg-config gcc \
        libncursesw5-dev make python libnl-3-dev libnl-genl-3-dev -y

COPY . /htop

WORKDIR /htop

RUN ./autogen.sh && ./configure --enable-delayacct && make

CMD [ "/htop/htop" ]
```

I'm also able to compile this on macOS using: `./autogen.sh && ./configure && make` (note that it is not possible to compile htop with `--enable-delayacct` on non linux systems).

Can you give some details on how have you installed libnl and how are you running `configure` and `make`?

**Comment by florian2833z** [comment]
PKG-config was wissing :( Somehow i didnt need it for previous versions ...

**Comment by andrestc** [comment]
Yeah, I think `pkg-config` is required by `PKG_CHECK_MODULES` (which is the recommended way to check for libnl). Maybe I should document this somewhere? (cc @hishamhm)

**Comment by hishamhm** [comment]
I just added an explicit check for pkgconfig. Thank you for reporting!

**Comment by alessiosavi** [comment]
for ubuntu 16.04 -> 
apt-fast install  libnl-3-dev  pkg-config   libhwloc5 libhwloc-dev libnl-genl-3-dev
apt-fast install  libhwloc-common ibnl-3-200-dbg  <- if you still get error during configure, install this 2 too
