### ISSUE TITLE
htop shows any cpu usage as full CPU usage

### ISSUE THREAD

**Issue by nielsole** [hishamhm/htop#715]
On one machine, htop shows any processes with any CPU usage as if they were using the entire CPU:

![screenshot from 2018-01-09 12-53-10](https://user-images.githubusercontent.com/8849712/34720196-20491762-f53e-11e7-8696-22ac4fc0172d.png)

htop -v: `htop 2.0.2`
uname -r: `4.9.0-4-amd64`

**Comment by Explorer09** [comment]
Can you do us a favor and try to figure out which commit caused this error? (`git bisect` is your friend) It looks like you were building htop from master and not from the release version.

**Comment by nielsole** [comment]
Hey, thanks for the reply.
This is the debian package version with SHA256: ecdea08f4996ff50264427c592e3fc5d4b4d962c3e6e82c9c4752c04289ead24
I'll try to find the time, to build from source and bisect it.

**Comment by nielsole** [comment]
I just tried it and I couldn't find a 'good' version to bisect against. happens all the way down to 0.8.3 even though it looks a little different:
![screenshot from 2018-01-17 10-17-41](https://user-images.githubusercontent.com/8849712/35034821-b5531a42-fb6f-11e7-9364-27f859d7625c.png)

**Comment by nielsole** [comment]
I rebooted the machine and it went away. ¯\_(ツ)_/¯
I'll reopen this, when I can reproduce this more reliably.
