### ISSUE TITLE
Changing settings results in a crash.

### ISSUE THREAD

**Issue by hastysun** [hishamhm/htop#717]
Pressing F2, I change some of the settings. However when I press escape, it results in a crash. The error is below.
I'm on Arch with kernel 4.14.13, using zsh.

`
htop 2.0.2 aborting. Please report bug at http://hisham.hm/htop

 Please include in your report the following backtrace: 
htop(CRT_handleSIGSEGV+0x36)[0x562c0d6e8986]
/usr/lib/libc.so.6(+0x348e0)[0x7f80f8f1b8e0]
htop(String_freeArray+0x9)[0x562c0d6e05c9]
htop(Header_writeBackToSettings+0x4f)[0x562c0d6d8def]
htop(+0x19a7b)[0x562c0d6e3a7b]
htop(+0xde5a)[0x562c0d6d7e5a]
htop(ScreenManager_run+0x279)[0x562c0d6deb69]
htop(main+0x414)[0x562c0d6d5604]
/usr/lib/libc.so.6(__libc_start_main+0xea)[0x7f80f8f07f4a]
htop(_start+0x2a)[0x562c0d6d583a]

Additionally, in order to make the above backtrace useful,
please also run the following command to generate a disassembly of your binary:

   objdump -d `which htop` > ~/htop.objdump

and then attach the file ~/htop.objdump to your bug report.

Thank you for helping to improve htop!

zsh: abort (core dumped)  htop
`

**Comment by hishamhm** [comment]
Fixed in 2.1.0! Thank you for reporting!
