### ISSUE TITLE
Search (F4) doesn't display the search pattern

### ISSUE THREAD

**Issue by yurivict** [hishamhm/htop#718]
The user can enter the search pattern after pressing F4, in the top-left corner, but the pattern text isn't shown.

It should look and work like an edit box.

htop-2.0.2 on FreeBSD

**Comment by hishamhm** [comment]
It does show the pattern being written in the bottom line... am I missing something?

**Comment by yurivict** [comment]
I see what the problem is.
Cursor needs to be in the same place where the filter pattern is entered. Cursor is in the top-left corner which makes it confusing.

**Comment by hishamhm** [comment]
@yurivict Ah, I see... I have this already fixed in the new `perfcounters` branch! Thank you for the feedback!
