### ISSUE TITLE
Time for a 2.0.3 release?

### ISSUE THREAD

**Issue by cpaelzer** [hishamhm/htop#720]
Hi,
I've seen plenty of fixes being committed since the last release on  Jul 21, 2016.
I came by checking for some security fixes which are in, but there is way more fixed.

I haven't found an already documented release plan (nor a similar issue to the one I open) that I could align myself on, so I wanted to ask if maybe the changes collected would justify a 2.0.3 release soon?

Or were there other long term big change plans towards 2.1/3.0 or anything that I might not know of?

**Comment by fasterit** [comment]
Just FYI this request is related to the ACK from the Ubuntu security team for the fixes @hishamhm committed and the request for inclusion on 18.04 server release media (aka ISOs etc.).
Cf. https://bugs.launchpad.net/ubuntu/+source/htop/+bug/1644364

**Comment by eworm-de** [comment]
We have a tag `2.1.0` in repository, but the associated commit is missing from all branches.
Also there is no source tarball yet.

**Comment by hishamhm** [comment]
@eworm-de the official release tarball is here! :)

* http://hisham.hm/htop/releases/2.1.0/htop-2.1.0.tar.gz
* http://hisham.hm/htop/releases/2.1.0/htop-2.1.0.tar.gz.asc

(There was a permissions mistake in 2.1.0/ — it's now fixed, thanks for the heads up!)

**Comment by eworm-de** [comment]
I will look into this later and package for ArchLinux soon.
Thanks a lot!
