### ISSUE TITLE
Error: An unsatisfied requirement failed this build

### ISSUE THREAD

**Issue by julianoferretti** [hishamhm/htop#725]
>$ brew upgrade  
>$ ==> Upgrading 1 outdated package, with result:
>$ htop 2.0.2_1
>$ htop: This formula either does not compile or function as expected on macOS
>$ versions newer than Sierra due to an upstream incompatibility.
>$ Error: htop: An unsatisfied requirement failed this build.

This message appear when I run upgrade command

**Comment by hishamhm** [comment]
This is not an htop issue, but a macOS bug. The homebrew formula has been updated with a workaround.
