### ISSUE TITLE
Fn keys cannot use in screen

### ISSUE THREAD

**Issue by dizzam** [hishamhm/htop#732]
Software version:
    
    [root@VM_153_61_centos ~]# screen -v
    Screen version 4.00.03 (FAU) 23-Oct-06
    [root@VM_153_61_centos ~]# htop -v
    htop 2.1.0 - (C) 2004-2018 Hisham Muhammad
    Released under the GNU GPL.

Now I connect to the server using putty (Release 0.67). When I use htop in screen mode, the some of the Fn keys (F1~F4, precisely) won't work. How can I prevent this? 

Thank you!

**Comment by hishamhm** [comment]
htop uses ncurses, which is library usually included with the operating system, to get the key codes for F1-F4. This means that when those keys don't work, it's usually not htop's fault, but rather a misconfiguration somewhere in the system (typically a mismatch between system and terminal configuration). Please check your Putty and Screen configuration!
