### ISSUE TITLE
Building htop-3.0.0beta1; No rule to make target 'linux/PerfCounter.c'

### ISSUE THREAD

**Issue by maq123** [hishamhm/htop#734]
1. Downloaded the htop-3.0.0beta1 release from github.
2. `./autogen.sh ; ./configure`
3. Make complains about: `make: *** No rule to make target 'linux/PerfCounter.c', needed by 'linux/PerfCounter.h'.  Stop.`

**Comment by hishamhm** [comment]
Pushed a new tag, `3.0.0beta2` -- please try that instead!
