### ISSUE TITLE
Version 2.1.0 - LDFLAGS doesn't make it to the Makefile

### ISSUE THREAD

**Issue by lancethepants** [hishamhm/htop#738]
LDFLAGS="-L/path/to/lib -Wl,-rpath,/path/to/lib" \
CPPFLAGS="-I/path/to/include" \
CFLAGS="-cpuarchstuff" \
./configure

When running ./configure, I can see in config.log that it is using the LDFLAGS value I pass to it.  However, the LDFLAGS value doesn't make it into the Makefile.

**Comment by hishamhm** [comment]
Fixed in `master`, thank you for the report!
