### ISSUE TITLE
[regression] 2.1.0 shows a blank screen on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [hishamhm/htop#742]
2.0.2 works fine.

![htop-blank](https://user-images.githubusercontent.com/271906/36451701-c8ddb1a2-1646-11e8-9415-6dfe0dd56fb0.png)

This is a show-stopper for the FreeBSD port that I tried to update.
bug#743 is another reason.

**Comment by willvousden** [comment]
I'm getting this on RHEL as well.  Back to 2.0.2 for now!

**Comment by yurivict** [comment]
Good to know that I am not alone. -)

**Comment by hishamhm** [comment]
@yurivict @willvousden Are you getting this on `master` as well?

**Comment by willvousden** [comment]
@hishamhm Yep.

**Comment by hishamhm** [comment]
@willvousden strange, I can't reproduce it. Any chance you could `git bisect` and find which commits stops working for you? Thank you!

**Comment by willvousden** [comment]
According to `git bisect` it was b258d6e5 that introduced this one!

**Comment by mklein-de** [comment]
that commit was also the culprit for #695, maybe related root cause?

**Comment by hishamhm** [comment]
@yurivict please test current `master`!

**Comment by yurivict** [comment]
@hishamhm It works now.
Could you please make a release so that I can update the FreeBSD port?
Thanks!

**Comment by donileo** [comment]
Had to disable unicode on the configure script for it to install on FreeBSD.

```
./configure --disable-unicode
```

**Comment by yurivict** [comment]
It shouldn't be this way.

**Comment by yurivict** [comment]
This regression has been fixed, the FreeBSD port has been updated a while ago, and now works fine.
Closing.

**Comment by donileo** [comment]
@yurivict Just to be clear yes the port works fine. My comment on disabling unicode on the configure is when building directly from the repo from git clone (not the tarball).

**Comment by yurivict** [comment]
> My comment on disabling unicode on the configure is when building directly from the repo from git clone (not the tarball).

I see. Thanks for clarifying.
