### ISSUE TITLE
Please merge dragonflybsd/ into freebsd/

### ISSUE THREAD

**Issue by yurivict** [hishamhm/htop#743]
DragonFly BSD is a fork of FreeBSD. There should be no reason why DragonFly should have special treatment in a package like ```htop```.

Also please note that dragonflybsd/ does use backtrace_xx and freebsd/ doesn't. This also doesn't make sense.

**Comment by hishamhm** [comment]
@yurivict these ports were provided by different contributors. I only maintain personally the Linux backend. Contributions bringing the `freebsd/` port up to speed are more than welcome!

**Comment by yurivict** [comment]
Ok, I will submit a pull request that merges them under freebsd/.

**Comment by yurivict** [comment]
I reviewed the differences, and came to a conclusion that this isn't worth the effort. There are some deeper changes than I thought. FreeBSD support itself is fine.

@hishamhm Are you planning to make a release any time soon?
