### ISSUE TITLE
Network stats for each process

### ISSUE THREAD

**Issue by amosbird** [hishamhm/htop#748]
Hello, htop is really a nice tool as a system info portal which is almost feature complete. I'm confused why we don't have network stats for each process. I saw people implementing network meters for htop which is cool. But having columns for network stats for each process is huge. And we can order by the network usage just like cpu, mem, disk.

**Comment by hishamhm** [comment]
Thank you for making a feature request! The issues page keeps open bugs only; feature requests are filed in the [`feature requests`](https://github.com/hishamhm/htop/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22feature+request%22+) label. More info [here](https://github.com/hishamhm/htop/blob/master/CONTRIBUTING.md#feature-requests)! Thank you for the feedback!
