### ISSUE TITLE
ncurses.h can't be found without supplying path to the build

### ISSUE THREAD

**Issue by yurivict** [hishamhm/htop#755]
I suggest you should use ```pkg-config``` for the headers path so that there will be no need to supply the path in ```CFLAGS```.

**Comment by Explorer09** [comment]
Did you try building from the latest master branch? It looks like the commit 11ccd0d16e23d1ee4e49e77365d64052bc3d0227 should have fixed it, and your problem looks like a duplicate of #695.

**Comment by hishamhm** [comment]
Closing this since the problem seems to be solved (as per pointers given by @Explorer09). @yurivict feel free to reopen in case it still causes problems in your OS. Thanks!
