### ISSUE TITLE
Update process title if it changes

### ISSUE THREAD

**Issue by martinmarques** [hishamhm/htop#759]
If a process title changes, htop should reflect that.

Servers like postgres have backend process which manage the client connections. The title of the process may contain valuable information for the DBA/SysAdmin and if update_process_title is on in postgresql.conf that title will change with the state of the connection and the command it's executing if any.

Htop doesn't refresh the command and so shows bogus information

**Comment by hishamhm** [comment]
<kbd>F2</kbd> (Setup) :arrow_right: Display Options :arrow_right: [x] Update process names on every refresh

:)
