### ISSUE TITLE
Tree view doesn't show anything

### ISSUE THREAD

**Issue by Sweets** [hishamhm/htop#761]
Switching to tree view mode in htop shows nothing. Terminal is `st`. Version is 2.1.0-2.

With sorted https://my.mixtape.moe/zvopbp.png

With tree https://my.mixtape.moe/ioosyc.png

**Comment by Sweets** [comment]
I've got a theory for this now. My system uses openrc for init, and after talking with some friends who use systemd, because tree view shows child processes, and because the init script is PID 1, everything is a child of PID 1.

All that being said, for some reason the init is not shown in htop with openrc (/usr/bin/init in my specific case), and thus, none of the child processes are shown.

**Comment by hishamhm** [comment]
@Sweets What's the output of `ps -ax -o pid,ppid,cmd` in your system? (You can post a link to a pastbin/gist with that)

**Comment by Sweets** [comment]
https://gist.github.com/Sweets/f5bf447adfc6f9a863bc7959a678316b

**Comment by wangqr** [comment]
Can you find the init process (PID=1) in htop sorted mode? You may try turning on/off the `Hide xxx` options in the Display options panel.

**Comment by Sweets** [comment]
When I last looked (see second comment), I could not. I'll double check when I get home and reply again when I get home, though.

**Comment by Sweets** [comment]
Sorry for such a late reply. @wangqr No, it doesn't show anything at all. The lowest PID it shows is 1949.

**Comment by wangqr** [comment]
I have added some debug logging in [`wangqr:debug-log-tree-build`](https://github.com/wangqr/htop/tree/debug-log-tree-build).
Can you try using that commit and run it with `./htop 2> htop.log` for a few seconds, then post the htop.log file?

**Comment by Sweets** [comment]
The log file's a bit lengthy. I believe the most relevant bit of it is `Setting show=false for PID=1 isKernelThread=true`, but here's the full file, should you need it @wangqr.

https://gist.github.com/Sweets/7a16a9699eb528ff62517a81aa6ffe1e

**Comment by wangqr** [comment]
In that case you should be able to see the tree if `Hide kernel threads` in Display options is unchecked. But it is still strange that the `init` process is a kernel thread.

**Comment by Sweets** [comment]
Tree view is shown now

**Comment by wangqr** [comment]
So the problem here is how to identify kernel threads.
Currently htop [checks if `PGID == 0`](https://github.com/hishamhm/htop/blob/master/linux/LinuxProcess.h#L137). However [this answer](https://stackoverflow.com/a/12231039/3342190) suggests that we should check if `/proc/$pid/cmdline` is empty to distinguish a kernel-thread from a user-thread.

**Comment by hishamhm** [comment]
@Sweets Thank you for the report, and @wangqr thank you a lot for the investigation! I'm changing the method to determine kernel threads on Linux.

**Comment by kongdd** [comment]
This problem reoccurs in WSL2 under the win10 2004.

**Comment by wangqr** [comment]
@kongdd have you tried the method above, i.e. toggling the settings?

**Comment by kongdd** [comment]
@wangqr Thanks. It works with the “Tree view” checked in the display option.
