### ISSUE TITLE
implement the equivalent of top -n

### ISSUE THREAD

**Issue by UnixJunkie** [hishamhm/htop#762]
-n  :Number-of-iterations limit as:  -n number
            Specifies  the  maximum  number of iterations, or frames, top
            should produce before ending.

On a loaded machine, you would prefer to not launch htop (or top).
You just want it to be fired once and show you the stats.

**Comment by hishamhm** [comment]
Thank you for making a feature request! The issues page keeps open bugs only; feature requests are filed in the [`feature requests`](https://github.com/hishamhm/htop/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22feature+request%22+) label. More info [here](https://github.com/hishamhm/htop/blob/master/CONTRIBUTING.md#feature-requests)! Thank you for the feedback!
