### ISSUE TITLE
htop shows firefox plug-in using 98G(!) of virtual memory

### ISSUE THREAD

**Issue by bozonius** [hishamhm/htop#766]
I am running firefox (any version does this) and htop 2.1.0 on CentOS 6.  Firefox fires up plugin-container subprocesses, and after some time (idk, maybe days?) htop will report those containers having 98G of virtual space.   This is obviously incorrect.

My hardware has 12GB physical core memory, and about 12GB of swap available (only 8GB swap currently enabled).  Is this simply MMU page tables run amok, or is firefox storing more data on disk somewhere?

Either way, my system does start to drag after a while, and I end up killing these processes (htop does this well, thank you; killall works the charm also).  That almost always seems to do the trick, and restores stability to my system while not having to restart firefox.

I recognize that this is probably symptomatic of some other issue, but I'd like to understand what htop is thinking and why it is reporting processes that are so oversize.  I will try to include a screen shot.

![screenshot-admin solon](https://user-images.githubusercontent.com/13354690/37800376-ceae1ff8-2ddf-11e8-8349-deac0ad69ad9.png)

**Comment by bozonius** [comment]
Nvm.  Found this:  https://stackoverflow.com/questions/23187228/what-is-virt-column-in-htop-memory-overhead

So I will get rid of VIRT from the output.

**Comment by kenorb** [comment]
Same here, 532G of Virt for Docker, fresh start just after the restart.

<img width="740" alt="screen shot 2018-04-30 at 16 10 46" src="https://user-images.githubusercontent.com/266306/39434715-44e27500-4c91-11e8-82b4-990b705696d3.png">
