### ISSUE TITLE
./configure Error on OpenIndiana

### ISSUE THREAD

**Issue by schenklklopfer** [hishamhm/htop#774]
My system: OpenIndiana The Illumos Project SunOS 5.11 illumos-17f11284b4 April 2018

Just run autogen.sh - perfect

After that ./configures throws 

> ./configure: line 6745: syntax error at line 6751: `(' unexpected

needed to uncomment the affected if clause

```
if test "x$enable_delayacct" = xyes
then
   PKG_PROG_PKG_CONFIG()
   PKG_CHECK_MODULES(LIBNL3, libnl-3.0, , missing_libraries="$missing_libraries libnl-3")
   PKG_CHECK_MODULES(LIBNL3GENL, libnl-genl-3.0, , missing_libraries="$missing_libraries libnl-genl-3")
   CFLAGS="$CFLAGS $LIBNL3_CFLAGS $LIBNL3GENL_CFLAGS"
   LIBS="$LIBS $LIBNL3_LIBS $LIBNL3GENL_LIBS"

$as_echo "#define HAVE_DELAYACCT 1" >>confdefs.h

fi
```

After that `./configure` as well as `make `and `make install` worked.
Binary also works.

**Comment by Explorer09** [comment]
Workaround:
1. Download pkg-config.
2. Unpack pkg-config tarball.
3. Run its configure script inside (no need to do `make` on it).
4. Copy the generated pkg.m4, to the htop source `m4/` subdirectory.
5. Re-run `autogen.sh` in htop.
