### ISSUE TITLE
htop-3.0.0beta4: Doesn't (correctly?) save customized CPU bar

### ISSUE THREAD

**Issue by Polynomial-C** [hishamhm/htop#778]
After upgrading from `htop-2.1.0` to `htop-3.0.0beta4` the CPU meters always get reset to `CPUs (1&2/4)` on left column and `CPUs (3&4/4)` on right column. 
Removing both CPU bars and replacing them with `CPU average` on left column seems to be not saved on exit. As soon as I start htop again, the orignal CPU bars are back. This is quite annyoing on my system with 16 cores where those default CPU bars consume lots of space in 80x25 sized terminals.
This already happened with `htop-3.0.0beta3`. Didn't check older beta releases.

**Comment by dtzWill** [comment]
FWIW I was having problems with beta4 not saving my settings -- even after deleting my htoprc and such.  Eventually gave up and went to 2.2.0 instead which doesn't have this problem for me, maybe that'll help you as well.

**Comment by hishamhm** [comment]
This should be fixed by now in the `next` branch now, thanks for reporting!
