### ISSUE TITLE
Solaris build broken in 3.0.0beta4

### ISSUE THREAD

**Issue by gmbroome** [hishamhm/htop#779]
Making default screen config portable in 3.0.0beta4 broke Solaris build.

The { } template block in solaris/Platform.c for generating solaris/Platform.h should be adjusted from:
`#include "SignalsPanel.h"`
`#include <signal.h>`

to

`#include "SignalsPanel.h"`
`#include "SolarisProcess.h"`
`#include <signal.h>`

and references SolarisProcess.c to `settings->sortKey` and `settings->direction` should be updated to `settings->ss->sortKey` and `settings->ss->direction` respectively.

**Comment by hishamhm** [comment]
Fixed in `next` (which I had forgotten to push) using your patch, thank you!

**Comment by gmbroome** [comment]
@hishamhm Just realized that my patch changed solaris/Platform.h without making the corresponding change in solaris/Platform.c - so the change will get clobbered the next time that solaris/Platform.h is regenerated.
