### ISSUE TITLE
~/apps/htop/bin/htop -s PERCENT_ MEM segfaults in 2.2.0

### ISSUE THREAD

**Issue by shlomif** [hishamhm/htop#787]
Hi!

```
shlomif[fcs]:$trunk/fc-solve/0fc-b$ /home/shlomif/apps/htop/bin/htop -s PERCENT_MEM
Segmentation fault (core dumped)

```

Built from source with `./configure --prefix` on Mageia Linux v7 x86-64.

**Comment by shlomif** [comment]
I should note that without any flags, it starts fine.

**Comment by shlomif** [comment]
Please see https://github.com/shlomif/htop/tree/crash-on-dash-s for a tentative fix.

**Comment by Explorer09** [comment]
Does it crash if htop is launched like this? `~/apps/htop/bin/htop dummy_arg`
I see at least two problems here:
1. `-s` option lacks the colon specified in getopt().
2. htop did not handle non-option argument properly. It should error instead of crash.

**Comment by shlomif** [comment]
On Thu, 26 Apr 2018 01:31:09 +0000 (UTC)
Kang-Che Sung (宋岡哲) <notifications@github.com> wrote:

> Does it crash if htop is launched like this? `~/apps/htop/bin/htop dummy_arg`
> I see at least two problems here:
> 1. `-s` option lacks the colon specified in getopt().
> 2. htop did not handle non-option argument properly. It should error instead
> of crash.
> 

shlomif@telaviv1:~/Download/unpack/to-del/htop$ /home/shlomif/apps/htop/bin/htop
dummy_arg
# Starts normally
shlomif@telaviv1:~/Download/unpack/to-del/htop$ /home/shlomif/apps/htop/bin/htop
--dummy_arg
/home/shlomif/apps/htop/bin/htop: unrecognized option '--dummy_arg'
shlomif@telaviv1:~/Download/unpack/to-del/htop$ 


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
https://youtu.be/GoEn1YfYTBM - Tiffany Alvord - “Fall Together”

I can imagine the headline: “Sarah Michelle Gellar, who played
Buffy the vampire slayer, murdered in cold blood by child daughter.”
    — http://www.shlomifish.org/humour/Summerschool-at-the-NSA/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
hi, any news?

**Comment by hishamhm** [comment]
Fixed in current master!

**Comment by shlomif** [comment]
On Wed, 23 May 2018 04:40:22 -0700
Hisham Muhammad <notifications@github.com> wrote:

> Fixed in current master!
> 

thanks!


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/bits/Can-I-SCO-Now/ - “Can I SCO Now?”

“I simply hate, detest, loathe, despise, and abhor redundancy.”
    — http://uncyclopedia.org/wiki/Redundancy

Please reply to list if it's a mailing list post - http://shlom.in/reply .
