### ISSUE TITLE
Snap and Deb version show different Task/Thread count

### ISSUE THREAD

**Issue by SycamoreFox** [hishamhm/htop#795]
Snap and Debian package versions showing different task/thread counts.  Both installed from the Software app in Ubuntu 18.04.

![screenshot from 2018-06-01 07-40-47](https://user-images.githubusercontent.com/18396681/40839448-99e0797e-6570-11e8-9902-0790806c0c74.png)
![screenshot from 2018-06-01 07-36-04](https://user-images.githubusercontent.com/18396681/40839542-0688dd6e-6571-11e8-99a0-982bf14eb53a.png)

**Comment by hishamhm** [comment]
They're just using different settings: press uppercase K to show/hide kernel threads :) (option also available via the Setup screen with F2)
