### ISSUE TITLE
Unstage/gitignore INSTALL since it's regenerated by autogen.sh

### ISSUE THREAD

**Issue by marcelpaulo** [hishamhm/htop#800]
When building from the git repository, *autogensh* regenerates ***INSTALL***, so it should be unstaged and added to *.gitignore*.

**Comment by hishamhm** [comment]
@marcelpaulo Thank you for the heads up! Obrigado! :)

**Comment by marcelpaulo** [comment]
Thanks to you for htop: can't live without it !

**Comment by Explorer09** [comment]
Good work of getting rid of it. I was about to propose git-ignoring INSTALL file before you filed it here.
Just to note that this INSTALL file is from Automake, so its content changes depending on Automake version you installed.
