### ISSUE TITLE
Color bug on ubuntu 18.04

### ISSUE THREAD

**Issue by ArashPartow** [hishamhm/htop#840]
I'm using the following version of htop on ubuntu 18.04:

> htop 2.1.0 - (C) 2004-2018 Hisham Muhammad
> Released under the GNU GPL.
> 

However it seems the background colours of the meters are buggy when compared to previous versions.

The following are two screenshots with default and Broken Gray color modes:

![image](https://user-images.githubusercontent.com/513642/45988386-03807380-c0ba-11e8-9ddc-ca7950f80798.png)

![image](https://user-images.githubusercontent.com/513642/45988388-08ddbe00-c0ba-11e8-89bb-93a209418335.png)

Is there way to configure htop to provide a view similar to the previous versions, something like this:

![image](https://user-images.githubusercontent.com/513642/45988447-50644a00-c0ba-11e8-856d-c5e648e98e3c.png)

**Comment by Explorer09** [comment]
Looks like a duplicate of #635.

**Comment by Explorer09** [comment]
We had a lot of color bugs reported and fixed in upstream htop already. Please build an upstream version (this master branch) of htop and check if the bug still exists. If not, report Debian or Ubuntu or whoever maintains distro versions of htop and tell them to pull patches.

**Comment by ArashPartow** [comment]
@Explorer09  Thank-you for the suggestion, I did rebuild htop as recommended and the issue went away.
