### ISSUE TITLE
Missing permissions causing confusing

### ISSUE THREAD

**Issue by Sworddragon** [hishamhm/htop#88]
I'm using htop 1.0.3 and have noticed that if the user haven't enough permission he doesn't see the values like IORR and IOWR from other users. In this case these columns will always show 0 but this can get a little confusing as 0 can be also the correct value (which is especially for these columns not uncommon). So the user may not be able to say if it is the correct value or not. It would be helpful if htop would show something different than a potential correct value (maybe a reserved character) if a value can't be get.

**Comment by hishamhm** [comment]
Revisiting old issues: this one can be closed, it has been fixed in htop 2.x; when there is no permission in shows "no perm" in the column, and not 0.

**Comment by Sworddragon** [comment]
I'm using now htop 2.0.2 and am still noticing that this is not the case for every column. On checking this a bit more I'm noticing that this issue still exists for RD_CHAR, WR_CHAR, WR_SYSC, IO_RBYTES, IO_WBYTES and IO_CANCEL. But since values might be ambiguous I can't tell if other columns are still affected too. Likely RD_SYSC is affected too and maybe you want to recheck this also for other columns.

**Comment by hishamhm** [comment]
@Sworddragon thanks for the note. I rechecked all columns and added more "no perm" messages.
