### ISSUE TITLE
Suggestion: Compact numbers display.

### ISSUE THREAD

**Issue by pthfdr-42** [hishamhm/htop#901]
Only use the first 3 digits, and use k/M/G to replace the decimal point.
In this way, the columns are more compact (only 4 characters), and more recognizable when colors are unavailable.
Example:
0-9999 bytes is not changed.
10000->10k0
1230k->1M23
12300k->12M3
123000k->123M
1230000k->1G23

**Comment by dodona2** [comment]
like unix df -h command:
1.8G   
162G 
379M

**Comment by pthfdr-42** [comment]
I think that mine is better, since it always has 3 effective digits. Plus You can easily tell that "12M3" is about 12M.
(It is particularly inspired by how the Chinese say numbers unofficially.)
