### ISSUE TITLE
Command-line option to start Maximized

### ISSUE THREAD

**Issue by AIsage** [hishamhm/htop#907]
If possible, please add a command-line option to start maximized like :
htop --start-max

I'd like to make a custom menu item using alacarte to start htop maximized, but it's not possible without workarounds like devilspie scripts as far as I know.

**Comment by Explorer09** [comment]
@AIsage You know, as a terminal application, htop has little control on the behavior of the terminal emulator window (htop has no abillity to start its own X11 window). Perhaps what you need is a custom script that maximizes terminal window automatically when starting htop. Such a thing is currently out of htop's scope.

**Comment by AIsage** [comment]
> @AIsage You know, as a terminal application, htop has little control on the behavior of the terminal emulator window (htop has no abillity to start its own X11 window). Perhaps what you need is a custom script that maximizes terminal window automatically when starting htop. Such a thing is currently out of htop's scope.

Yes. sorry about that. The fix was as easy as using "xfce4-terminal --maximize -x htop" to call htop in a maximized terminal (xfce4-terminal in my case). Thank you for your time.
