### ISSUE TITLE
'no perm' IO_RATE in Tiny Core Linux

### ISSUE THREAD

**Issue by webbp** [hishamhm/htop#938]
In Tiny Core Linux, htop shows 'no perm' for IO_RATE, IO_READ_RATE, and IO_WRITE_RATE. Likewise sudo htop. Same for htop 2.1.0 and htop 3.0.0beta5 .

I've not seen this exact issue in other distros. I want to fix the package. What could cause this? Tiny Core doesn't have systemd nor cgroups, and the root filesystem is a ramdisk.

4.19.10-tinycore64 #1999 SMP Tue Dec 18 15:18:54 UTC 2018 x86_64 GNU/Linux

**Comment by wangqr** [comment]
Can you provide the output of
```shell
cat /proc/$$/io
ls -lF /proc/$$/io
```

**Comment by webbp** [comment]
There is no /proc/<PID>/io . A bit of research suggests that this is because
of a missing kernel config:
# CONFIG_TASK_XACCT is not set
I put in a request to the Tiny Core devs to add CONFIG_TASK_XACCT=y
Thanks for the info!
