### ISSUE TITLE
Display RAM Usage In Absolute Number Instead Of Percentage

### ISSUE THREAD

**Issue by TakuyaSama** [hishamhm/htop#939]
I would like to ask for the option to set the RAM usage display at absolute values, instead of percentage above the total quantity of RAM installed. It's more interesting to me, at least, to allow that choice. I don't know if that would be a pain feature to include or not, please, let me know as an answer.

Thank you very much for your great work, the program is really nice.

Receive a huge hug mate ^^.

**Comment by eduardocanellas** [comment]
@TakuyaSama I think the option you'd like to have in the application already exists. It's possible to add columns for different stuff and one of those is M_RESIDENT, which is the amount of RAM being used. You just have to go to _setup_ through _F2_ and go down to the _columns_ options. In _available columns_, you should find M_RESIDENT.

**Comment by TakuyaSama** [comment]
> @TakuyaSama I think the option you'd like to have in the application already exists. It's possible to add columns for different stuff and one of those is M_RESIDENT, which is the amount of RAM being used. You just have to go to _setup_ through _F2_ and go down to the _columns_ options. In _available columns_, you should find M_RESIDENT.

OK, i'll check that out as soon as i can.

Thank you very much mate.

Bests ˆˆ.

**Comment by TakuyaSama** [comment]
Checked and that found thanks to @eduardocanellas, though the number is not human-readable/friendly at all.
Closing the issue.
