### ISSUE TITLE
Feature: Show cpu serial start from Zero

### ISSUE THREAD

**Issue by Leslie-Fang** [hishamhm/htop#947]
When use htop shows the cpu utilization, the cpu serial number is started from 1 instead of 0. It's not user-friendly, since when we use numactl to bind cpu, the serial starts from 0.
So we have to make a conversion when use htop.
Is it possible to make a change?

**Comment by wangqr** [comment]
You can press F2 to enter the Setup menu. From there, select `Display options` and check `Count CPUs from 0 instead of 1`.

**Comment by Leslie-Fang** [comment]
> You can press F2 to enter the Setup menu. From there, select `Display options` and check `Count CPUs from 0 instead of 1`.

@wangqr  Great, Thanks:).
