### ISSUE TITLE
CPU meter doesn't show SIRQ %

### ISSUE THREAD

**Issue by brianjmurrell** [hishamhm/htop#995]
I'm using htop 2.2.0 on OpenWRT.

In doing some reading, I have come to understand that the CPU meter should show soft irq % as magenta.  I'm not seeing that.  I'm only seeing _sys_, _low_, and _user_ (normal).

Seeing the sirq% is something I really miss in htop.  I find I often quit out of htop and run top to see that.

**Comment by Fail-Safe** [comment]
@brianjmurrell I also use htop 2.2.0 a lot on OpenWrt. I believe it does have what you are looking for, but you have to toggle that a setting to have a detailed CPU time visible. See here:

![Screen Shot 2020-08-30 at 2 49 02 PM](https://user-images.githubusercontent.com/10307870/91667163-62359f80-ead0-11ea-848f-af45fed495ee.png)

**Comment by brianjmurrell** [comment]
@Fail-Safe So I enabled that.  Where am I supposed to see the additional details?
