### ISSUE TITLE
F10 Doesn't working on fedora.

### ISSUE THREAD

**Issue by yunusozd** [hishamhm/htop#998]
I can't quit htop with f10+fn buttons. It's not working on my pc. I can only quit w,th close button.

**Comment by hugomg** [comment]
F10 works for me on Fedora 32.

If you are using GNOME Terminal you might want to go to Preferences->General and uncheck the option that makes the F10 key the menu accelerator key. The F10 hotkey won't work for htop if it is already being used by GNOME Terminal. https://help.gnome.org/users/gnome-terminal/stable/pref-keyboard-access.html.en

**Comment by yunusozd** [comment]
thanks, I forgot to uncheck that option. Now, It's working :)
